### PR TITLE
Fix #3155 font loading errors

### LINKED ISSUE #3155: First point annotation has unknown icon [ ]
### Description
font-awsome icon is not correctly render on first Annotation point

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v68

*Steps to reproduce*

- open a map
- refresh the page
- open annotations panel from burger menu
- add a new point Annotation
- add a point geometry on map
- click on map

*Expected Result*

-  The icon should be the one showed in the select form

*Current Result*

-  2018-08-09 14_45_59-mapstore homepage

### PR DESCRIPTION
**Pull request by MV88**
## Description
This pr fixes those problems of font loading with notification errors

## Issues
 - Fix #3155

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
notification error appear even if the font has been loaded correctly

**What is the new behavior?**
no problem of loading font and notification error at the same time

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
i had to clone part of the [onforntready](https://github.com/dwighthouse/onfontready/blob/master/docs/README.md) library because there was a syntax error requiring it.

### CODE REVIEW

File: web/client/plugins/Map.jsx [hunk 1]
```diff
@@ -117,17 +119,13 @@ const {handleCreationLayerError, handleCreationBackgroundError, resetMapOnInit}
  *
  * You can also specify a list if fonts that will be loaded before map is rendered (on willMount lyfe) and
```
Comment (offtherailz) [inline web/client/plugins/Map.jsx]:
```suggestion
 * You can also specify a list of fonts that have to be loaded before map rendering
```

File: web/client/plugins/Map.jsx [hunk 2]
```diff
@@ -117,17 +119,13 @@ const {handleCreationLayerError, handleCreationBackgroundError, resetMapOnInit}
...
  * if the shouldLoadFont is true
- * For each font you can specify an object describing the variation. The object can contain weight, style, and stretch properties.
- * If a property is not present it will default to normal.
+ * For each font you can specify the Fontname used in the `@font-face` declaration which must be included otherwise a notification error will appear:
```
Comment (offtherailz) [inline web/client/plugins/Map.jsx]:
```suggestion
 * This font pre-load list is required if you're using canvas based mapping libraries (e.g. OpenLayers) and you need to show markers with symbols (e.g. Annotations). 
  * For each font you must specify the font name used in the `@font-face` inside the "fonts" array property. Note: the `@font-face` declaration must be present in css of the page, otherwise the font can not be loaded anyway. 
```

File: web/client/utils/AgentUtils.js [hunk 3]
```diff
@@ -18,7 +18,332 @@ const AgentUtils = {
                 || document.body.clientHeight;
 
         return {maxWidth: width, maxHeight: height};
-    }
+    },
+    /**
+     * This has been cloned from https://github.com/dwighthouse/onfontready
```
[the remark this answers is not in the document]
Comment (MV88) [reply web/client/utils/AgentUtils.js]: i tried to do that, but it throws a syntax error on IE11 when requiring it via 
`const onfontready = require('onfontready');`
maybe i can open an issue on that repo to see if anybody has the same issue
