### PR TITLE
Fix #9075. Handle cases when domain isnot in format start--end

### LINKED ISSUE #9075: Timeline crash if time layer has few data
## Description
If a layer do not have any data, the timline shows 
"nan-nan-nan" in date fields.
If you try to expand the timeline, it crashes

## How to reproduce

(the original test was a little different. I had a context configured for the timeline with a custom resource access manager that filters the data. For users with no data access, the app crashes when timeline is expanded. Anyway I think it could happen in similar conditions like the ones following. To check).
-  Create a time layer on geoserver with 0, 1, or 2 features (GeoServer needs WMTS mutlidim extension to work with timeline)
- Add the layer to the map
- Expand the timeline

*Expected Result*
- No data shown

*Current Result*
- NaN values in current date fields 
- The application crashes

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This PR fixes #9075 handling the cases when DescribeDomain does not return "start--end" format. 

- No data: empty string (range is set as for saved data)
- 1 value only: only current time is set, range is set to default interval
- list of values, getting start and end value to set the range. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9075
**What is the new behavior?**

Timeline do not crash. Current value is not null.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/epics/timeline.js [hunk 1]
```diff
@@ -202,22 +202,41 @@ const loadRangeData = (id, timeData, getState) => {
 /**
  * Update timeline with current, offset and the range data
  * on range initialization
- * @param state
- * @param {string} value
+ * @param state application state
+ * @param {string|string[]} values the range values. It can be an array or a domain string. (`start--end`, `start,x1,x2,x3,end` or `start,end`)
```
Comment (dsuren1) [inline web/client/epics/timeline.js:206]:
```suggestion
 * @param {string|string[]} value the range values. It can be an array or a domain string. (`start--end`, `start,x1,x2,x3,end` or `start,end`)
```
Parameter name doesn't match in jsdoc

**Review by dsuren1 — COMMENTED** [review]
@offtherailz 
LGTM!

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test it in Dev and let us know if it can be backported. Thanks!

**Comment by offtherailz** [comment]
Going to backport it.

**Comment by ElenaGallo** [comment]
Test passed, @offtherailz it is possible to backport this PR.
