### PR TITLE
fix #2151 removed full screen button if safari is detected

### LINKED ISSUE #2151: Full Screen button does not work on IPhone
Not sure this happens on Android but on IPhone it does nothing, see below.

**Nothing happens :( **
file 07-09-17 15 17 20

### PR DESCRIPTION
**Pull request by MV88**
#2151

### CODE REVIEW

File: web/client/components/app/StandardApp.jsx [hunk 1]
```diff
@@ -105,6 +106,11 @@ class StandardApp extends React.Component {
     }
     init = (config) => {
         this.store.dispatch(changeBrowserProperties(ConfigUtils.getBrowserProperties()));
+        if (navigator.userAgent.indexOf('Safari') !== -1 && navigator.userAgent.indexOf('Chrome') === -1) {
```
Comment (mbarto) [inline web/client/components/app/StandardApp.jsx]: can't we amend the browser state slice with safari info, instead of doing this?

File: web/client/components/buttons/FullScreenButton.jsx [hunk 2]
```diff
@@ -44,6 +45,7 @@ class FullScreenButton extends React.Component {
         help: PropTypes.oneOfType([PropTypes.string, PropTypes.element]),
         glyphicon: PropTypes.string,
         active: PropTypes.bool,
+        hide: PropTypes.bool,
```
Comment (mbarto) [inline web/client/components/buttons/FullScreenButton.jsx]: Can we use disablePluginIf?

Comment (MV88) [reply web/client/components/buttons/FullScreenButton.jsx]: sure, it is better
