### PR TITLE
fix #1326 : Added limits for group name and desc and a message

### LINKED ISSUE #1326: Groups cannot be created if the entered description is too long
In group manager, if the users inputs a long description the save can fail, so the error message appears:  

> "There was an error saving this groupInternal Server Error"

Is there a way to display the user the reason of the failure (description too long) ?

### PR DESCRIPTION
**Pull request by MV88**
fixed #1326
- provided a maxLength to the input field
- provided a localized message when the limit is reached for both the name and the description
- Header now display a long message correctly if there are some spaces

### CODE REVIEW

File: web/client/components/manager/users/GroupDialog.jsx [hunk 1]
```diff
@@ -56,6 +57,7 @@ const GroupDialog = React.createClass({
           options: {},
           useModal: true,
           closeGlyph: "",
+          descLimit: 255,
```
Comment (mbarto) [inline web/client/components/manager/users/GroupDialog.jsx]: This is not used. You repeat 255 everywhere

Comment (MV88) [inline web/client/components/manager/users/GroupDialog.jsx]: I tried to use it but it was undefined and wasn't working
