### PR TITLE
Do not ignore url params. Fixes #786

### LINKED ISSUE #786: MapServer wms resources are loaded incorrectly
url parameters are stripped

### PR DESCRIPTION
**Pull request by Gnafu**

### CODE REVIEW

File: web/client/components/map/leaflet/plugins/WMSLayer.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ L.tileLayer.multipleUrlWMS = function(urls, options) {
 function wmsToLeafletOptions(options) {
     var opacity = options.opacity !== undefined ? options.opacity : 1;
     // NOTE: can we use opacity to manage visibility?
-    return objectAssign({
+    return objectAssign( options.baseParams || {}, {
```
Comment (mbarto) [inline web/client/components/map/leaflet/plugins/WMSLayer.js]: objectAssign({}, options.baseParams, ...

File: web/client/components/map/openlayers/plugins/WMSLayer.js [hunk 2]
```diff
@@ -16,7 +16,7 @@ const {isArray} = require('lodash');
 
 function wmsToOpenlayersOptions(options) {
     // NOTE: can we use opacity to manage visibility?
-    return objectAssign({
+    return objectAssign(options.baseParams || {}, {
```
Comment (mbarto) [inline web/client/components/map/openlayers/plugins/WMSLayer.js]: objectAssign({}, options.baseParams, ...
