### PR TITLE
fixes #7554 annotations circle radius changing

### LINKED ISSUE #7554: Annotations - circle radius is changing when users clicks on a different geometries in the list
## Description
Circle radius changes under specific circumstances when user click on a set of newly created geometries in the sidebar.

## How to reproduce
1. Create new annotation or edit existing one.
2. Create polygon or marker.
3. Create new circle.
4. Switch back to previously created marker by click on it in annotations sidebar.
5. Switch back to the circle by click on it.

*Expected Result*
Circle is rendered with the consistent radius.

*Current Result*
Circle radius changes when user switch to another geometry and then back to the circle.

https://user-images.githubusercontent.com/4226620/141852102-ee863429-246c-4bd6-9de8-fbd90cf37094.mp4

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by barema4**
## Description
* This PR fixes annotations - circle radius changing when users clicks on a different geometries in the list

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

* #7554
* Circle radius changes when user switch to another geometry and then back to the circle.

**What is the new behavior?**
* Circle is rendered with the consistent radius.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/epics/annotations.js [hunk 1]
```diff
@@ -122,8 +122,8 @@ const validateFeatureCollection = (feature) => {
  * @param drawMethod
  * @return {boolean}
  */
-const getGeodesicProperty = (state, drawMethod = "Circle") => {
-    return drawMethod === "Circle" && get(state.annotations, "config.geodesic", false);
+const getGeodesicProperty = (state) => {
+    return get(state.annotations, "config.geodesic");
```
Comment (MV88) [inline web/client/epics/annotations.js:126]: I would preserve the false default value here
```suggestion
    return get(state.annotations, "config.geodesic", false);
```

File: web/client/epics/annotations.js [hunk 2]
```diff
@@ -122,8 +122,8 @@ const validateFeatureCollection = (feature) => {
  * @param drawMethod
  * @return {boolean}
  */
-const getGeodesicProperty = (state, drawMethod = "Circle") => {
-    return drawMethod === "Circle" && get(state.annotations, "config.geodesic", false);
+const getGeodesicProperty = (state) => {
```
Comment (MV88) [inline web/client/epics/annotations.js:125]: this function is used in many parts in this file can you fix also their call, we are no longer using a second parameter.

File: web/client/epics/__tests__/annotations-test.js [hunk 3]
```diff
@@ -284,10 +284,18 @@ describe('annotations Epics', () => {
...
+                    config: {
+                        geodesic: true
+                    }
+                }
+            };
             if (actions.length >= 2) {
                 expect(actions[0].type).toBe(SET_STYLE);
                 expect(actions[1].type).toBe(CHANGE_DRAWING_STATUS);
                 expect(actions[1].status).toBe("updateStyle");
+                expect(state.annotations.config.geodesic).toBe(true);
```
Comment (MV88) [inline web/client/epics/__tests__/annotations-test.js:298]: this is wrong and it does not makes sense to test a local object 

I suggest to check how others tests are done with "testEpic" util function when they pass a mocked state
like ` it('MAP_CONFIG_LOADED with missing annotations layer', (done) => {`

Also why are you changing this test instead of editing the one we have discussed 
`it('clicked on map selecting a feature LineString ', (done) => {`

if you need clarification on how to write tests for the epics, please let me know

Comment (MV88) [reply web/client/epics/__tests__/annotations-test.js:298]: this could be a solution for the test

```
it('clicked on map selecting a Circle ', (done) => {
        store = mockStore( {
            ...defaultState,
            annotations: {
                ...defaultState.annotations,
                config: {
                    geodesic: true
                },
                editing: {
                    ...defaultState.annotations.editing,
                    features: [{
                        type: "Feature",
                        geometry: {
                            type: "Polygon",
                            coordinates: [[[1, 2], [1, 3], [1, undefined], [1, 5], [1, 2]]]
                        },
                        properties: {
                            id: "is a circle",
                            isCircle: true
                        }
                    }
                    ]

                }
            }
        } );

        store.subscribe(() => {
            const actions = store.getActions();
            if (actions.length >= 3) {
                expect(actions[1].type).toBe(CHANGE_DRAWING_STATUS);
                expect(actions[2].type).toBe(CHANGE_DRAWING_STATUS);
                expect(actions[2].options.geodesic).toBe(true);
                done();
            }
        });
        const action = selectFeatures([ft]);
        store.dispatch(action);
    });
```

File: web/client/epics/annotations.js [hunk 4]
```diff
@@ -137,7 +137,7 @@ const getSelectDrawStatus = (state) => {
         drawEnabled: false,
         translateEnabled: false,
         transformToFeatureCollection: true,
-        geodesic: getGeodesicProperty(state, state.draw.drawMethod)
+        geodesic: getGeodesicProperty(state)
```
Comment (MV88) [inline web/client/epics/annotations.js:140]: please fix every usage of getGeodesicProperty

**Review by MV88 — CHANGES_REQUESTED** [review]
@barema4 hi, I've found something to fix and amend
can you please take a look and let me know if you need clarifications

File: web/client/epics/__tests__/annotations-test.js (hunk 3 above)
Comment (barema4) [reply web/client/epics/__tests__/annotations-test.js]: I am  going through the testEpic and  I am understanding  how they done.

File: web/client/epics/annotations.js (hunk 2 above)
Comment (barema4) [reply web/client/epics/annotations.js:125]: Done

File: web/client/epics/__tests__/annotations-test.js [hunk 5]
```diff
@@ -1043,6 +1043,45 @@ describe('annotations Epics', () => {
...
+                config: {
+                    geodesic: true
+                },
+                editing: {
+                    ...defaultState.annotations.editing,
+                    features: [{
+                        type: "Feature",
+                        geometry: {
+                            type: "Polygon",
+                            coordinates: [[[1, 2], [1, 3], [1, undefined], [1, 5], [1, 2]]]
```
Comment (MV88) [inline web/client/epics/__tests__/annotations-test.js:1060]: let's use number in mocked coords
```suggestion
                            coordinates: [[[1, 2], [1, 3], [1, 1], [1, 5], [1, 2]]]
```

**Review by MV88 — CHANGES_REQUESTED** [review]

**Review by MV88 — APPROVED** [review]

**Comment by ElenaGallo** [comment]
Test passed, @barema4 please backport to 2022.01.xx. Thanks
