### PR TITLE
Fix #3439 Layer properties Fails if the Layer's has domain sharding

### LINKED ISSUE #3439: Layer properties Fails if the Layer's has domain sharding
### Description
There is an error trying to open the layer properties for a layer configured with domain sharding. The properties do not open.
Actually the only way to setup domain-sharding is by manual configuration, so is not a problem that is reproducible using simply the UI. Only [ a map on dev ](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/8208) contans this setting

depends on #3208 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Open  [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/8208)
- Open layers' properties

*Expected Result*

- Layer properties open

*Current Result*

- Error in console, no properties open

### Other useful information (optional):
The layer properties do not open for layers with domain sharding (trying to use URL as a string to guess capabilities URL, but it is an array). Probably we should check all the functionalities that inspect Layer's URL URL 
Error in console: 
```
LayersUtils.js:34 Uncaught TypeError: url.match is not a function
    at findGeoServerName (LayersUtils.js:34)
    at Object.getCapabilitiesUrl (LayersUtils.js:495)
    at getLayerCapabilities (layerCapabilities.js:66)
    at eval (bindActionCreators.js:4)
    at Lifecycle.componentWillReceiveProps (tocItemsSettings.js:142)
    at eval (ReactCompositeComponent.js:608)
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:607)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:751)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:721)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:751)
```

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix layer properties fails if the Layer's has domain sharding

## Issues
 - #3439 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3439 

**What is the new behavior?**
No layer property failure

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/utils/__tests__/LayersUtils-test.js [hunk 1]
```diff
@@ -1000,4 +1000,22 @@ describe('LayersUtils', () => {
                 availableStyles: [{ name: 'generic' }]
             });
     });
+
+    it('test findGeoServerName with array url', () => {
```
Comment (MV88) [inline web/client/utils/__tests__/LayersUtils-test.js]: just a minor thing:
can you move new tests near the one that are testing findGeoServerName func ?
thanks

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to 2019.02.xx stable branch ?

**Comment by kasongoyo** [comment]
> @kasongoyo please, can you backport this to 2019.02.xx stable branch ?

Yes, I will.
