### PR TITLE
Fix #9575 Avoid full rerender in filterRenderer

### LINKED ISSUE #9575: Issue to write a word on attribute table quick filter
## Description

It is not possible to write whole word using the quick filter in the attribute table. 
Every time you enter a word on the quick filter,  a wfs request is performed.

https://github.com/geosolutions-it/MapStore2/assets/56537133/44c79813-abe9-468b-a11c-fc19affe5173

## How to reproduce

- Open a map
- Select a layer on TOC
-  Open an attribute table
- Try to enter a text on the quick filter

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

On Prod, QA and DEV.

**Regression introduced by https://github.com/geosolutions-it/MapStore2/pull/9330**

### PR DESCRIPTION
**Pull request by offtherailz**
## Description

The issue happens when fields is not defined. In selector the "[]" was regenerated everytime.
I fixed the selector and added an additional security in featureEditor to avoid regeneration of filterRenderers (and so loss of focus) when the values are equal.
This guarantees that if the feature grid receives them dynamically for some reason, the filter renderers are not re-computed.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9575

**What is the new behavior?**

Fix #9575
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@offtherailz 
The fix works fine. But it introduces a new issue where the filter row is _hidden on first load_ of feature grid. Kindly check if this is happening. Thanks!

https://github.com/geosolutions-it/MapStore2/assets/26929983/577be0df-75c4-46eb-a130-62d1ca32d185

**Comment by offtherailz** [comment]
Thank you @dsuren1 , I didn't noticed it. 
This is because I used wrongly `useMemo` API. Actually there is no way to pass a custom comare function to it. So I removed it and the test for it.

File: web/client/plugins/featuregrid/__tests__/FeatureEditor-test.jsx [hunk 1]
```diff
@@ -104,6 +104,7 @@ describe('FeatureEditor plugin component', () => {
             expect(result.fields).toEqual(FIELDS);
         });
     });
+
```
Comment (offtherailz) [inline web/client/plugins/featuregrid/__tests__/FeatureEditor-test.jsx:107]:
```suggestion
```

File: web/client/plugins/featuregrid/FeatureEditor.jsx [hunk 2]
```diff
@@ -187,6 +186,8 @@ const FeatureDock = (props = {
     };
     const items = props?.items ?? [];
     const toolbarItems = items.filter(({target}) => target === 'toolbar');
+    // ensure to avoid re-rendering of the feature grid (lost focus on every render) in any case if for some
+    // reason the describeFeatureType or fields are generated but equal.
```
Comment (offtherailz) [inline web/client/plugins/featuregrid/FeatureEditor.jsx:190]:
```suggestion
```

**Review by dsuren1 — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please test in DEV and QA

**Comment by ElenaGallo** [comment]
Test passed on DEV, @offtherailz please backport to the stable branch. Thanks
