### PR TITLE
Fix #3473 - Style Editor - Style list shows missing styles alert after back to homepage

### LINKED ISSUE #3473: Style Editor - Style list  shows missing styles alert after back to homepage
### Description
Style list  shows missing styles alert after back to homepage

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a new map
- add a layer from catalog (eg: USA Population)
- save the map
- select the layer in TOC
- open settings and select style tab
- leave the panel open and go to homepage (Home button)
- open the same map
- open settings and select style tab

*Expected Result*

- loading spinner and after the list of styles

*Current Result*

- Missing style alert

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
Style list shows missing styles alert after back to homepage

## Issues
 - Fix #3473

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
issues #3473

**What is the new behavior?**
Style Editor will try to load style list if availableStyles are missing from settings

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/__tests__/styleeditor-test.js [hunk 1]
```diff
@@ -145,6 +145,58 @@ describe('styleeditor Epics', () => {
             results,
         state);
 
+    });
+    it('test toggleStyleEditorEpic enabled in state true but availableStyles missing from settings', (done) => {
```
Comment (offtherailz) [inline web/client/epics/__tests__/styleeditor-test.js]:
```suggestion
    it('toggleStyleEditorEpic: missing availableStyles starts the styles retrieval', (done) => {
```
