### PR TITLE
Fixes #3155 and Fixes #3266 and loads fontAwesome when the application starts

### LINKED ISSUE #3155: First point annotation has unknown icon [ ]
### Description
font-awsome icon is not correctly render on first Annotation point

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v68

*Steps to reproduce*

- open a map
- refresh the page
- open annotations panel from burger menu
- add a new point Annotation
- add a point geometry on map
- click on map

*Expected Result*

-  The icon should be the one showed in the select form

*Current Result*

-  2018-08-09 14_45_59-mapstore homepage

### LINKED ISSUE #3266: Introduce a loading font mechanism
### Description
The issue #3155 has shown the need to preload esternal fonts before rendering.

We need to introduce a load font mechanism based on the fonts being used by openlayers when rendering vector layers. This is not stricly correlated to the annotations plugin because you can load a map with annotations on the embedded mode.

### Other useful information (optional):

check out these resources
- https://hacks.mozilla.org/2016/06/webfont-preloading-for-html5-games/
- https://stackoverflow.com/questions/41852594/dynamically-load-fonts
- https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API ( only a draft atm)
- https://fontawesome.com/how-to-use/on-the-web/using-with/react

### PR DESCRIPTION
**Pull request by MV88**
## Description
This PR will temporarily fix the wrong render of the marker when : 
- loading a map with annotation
- after drawing a marker from the annotations plugin

and it will introduce a loading font mechanism configurable using fonts cfg in Map plugin
and it will check by default if the maptype is openlayers, but it can be overridden by the shouldLoadFont flag from configuration for the map plugin in general.

**NOTE** :  i also added the possibility to use a template string and passing the values to be used to substitute in the string.

**NOTE** :  Now the map Plugin is connected with the connect taken from PluginsUtils, be aware of that

## Issues
 - Fix #3155 
 - Fix #3266

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
a [] is displayed instead of the glyph inside the marker. because the font is not available on the very first render.

**What is the new behavior?**
The first marker you insert it shows correctly the gliph
if you load a map with annotation after cleaning the cache it loads the marker correctly

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by MV88** [comment]
@offtherailz @mbarto 

You are right, we can move it in a better place.

since there is this problem only in openlayers we can : 
1. move it to the render method op openlayers/Map.jsx (tested and working)
1. move it to openlayers/plugins/VectorLayers.js (tested and **not** working)

we can add a check in the Map component to see if the annotations layer will be rendered, but i see some caveats:
- you have to pass layers info to the map component
- this does not prevent this problem when you create an annotation for the first time and the font is not loaded yet.

In my opinion we can leave it in the map render, but we have to add a the same div also to the AnnotationsEditor for example.  

fontAwesome size is 75 kB

**Comment by offtherailz** [comment]
It is a little ugly to see some code specific for annotations in VectorLayer.
Anyway if we want the annotations to work also with existing maps, we have to do it, if otherwise this is not a problem, we can somehow add to vector layer the ability to pre-load some fonts for instance and in annotation's object provide the a fontUsed entry that is used in the vector's layer render method (adding something that effectively pre-load the font before rendering the layer).

**Comment by MV88** [comment]
Ok, for the moment we decided to move it to the map component. 

in the future we will implement a cleaner solution. See #3266

**Comment by offtherailz** [comment]
@mbarto good notes. This was a quick fix, but if using FontObservable is enough fast, we can do it. Please sync with @MV88 about implementation details.
Yes placing it in the plugin instead of the component is a good idea, if you don't have to use react to render anything.

**Comment by tdipisa** [comment]
@mbarto, can you please review? Thank you.

File: web/client/components/notifications/NotificationContainer.jsx [hunk 1]
```diff
@@ -78,10 +83,25 @@ class NotificationContainer extends React.Component {
         });
         notifications.forEach(notification => {
             if (systemNotifications.indexOf(notification.uid) < 0) {
+                let id = notification.message;
+                let str = LocaleUtils.getMessageById(this.context.messages, id);
```
Comment (mbarto) [inline web/client/components/notifications/NotificationContainer.jsx]: I would add formatting support with values directly in LocaleUtils.getMessageById(context, id, values)

File: web/client/plugins/Map.jsx [hunk 2]
```diff
@@ -146,10 +168,12 @@ class MapPlugin extends React.Component {
         loadingSpinner: PropTypes.bool,
         loadingError: PropTypes.string,
         tools: PropTypes.array,
+        fonts: PropTypes.array,
         options: PropTypes.object,
         mapOptions: PropTypes.object,
         projectionDefs: PropTypes.array,
         toolsOptions: PropTypes.object,
+        onErrorFont: PropTypes.func,
```
Comment (mbarto) [inline web/client/plugins/Map.jsx]: onFontError

File: web/client/plugins/Map.jsx [hunk 3]
```diff
@@ -165,6 +189,10 @@ class MapPlugin extends React.Component {
         tools: ["measurement", "locate", "scalebar", "draw", "highlight"],
         options: {},
         mapOptions: {},
+        fonts: {
+            'ThisFontDoesNotExist': {},
```
Comment (mbarto) [inline web/client/plugins/Map.jsx]: remove

File: web/client/plugins/Map.jsx [hunk 4]
```diff
@@ -186,10 +214,35 @@ class MapPlugin extends React.Component {
...
+    };
+    state = {
+        canRender: true
     };
 
     componentWillMount() {
+        const {mapType, fonts} = this.props;
+
+        // load each font before rendering (see issue #3155)
+        if (mapType === "openlayers" && fonts) {
```
Comment (mbarto) [inline web/client/plugins/Map.jsx]: The Map plugin is not aware of openlayers

File: web/client/plugins/Map.jsx [hunk 5]
```diff
@@ -112,29 +114,49 @@ const {handleCreationLayerError, handleCreationBackgroundError, resetMapOnInit}
...
+ *         "useForElevation": true,
+ *         "nodata": -9999,
+ *         "hidden": true
+ *      }]
+ *   }
+ * }
  *
  */
+
+const updateCanRenderState = (canRender) => () => ({
```
Comment (mbarto) [inline web/client/plugins/Map.jsx]: ???

Comment (MV88) [reply web/client/plugins/Map.jsx]: This function updates the internal state, [setState accepts also functions](https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b).
since i use it twice, i've created a function, i'll add a description above.

File: web/client/plugins/Map.jsx (hunk 3 above)
Comment (MV88) [reply web/client/plugins/Map.jsx]: Sure, it was there for testing

File: web/client/components/notifications/NotificationContainer.jsx (hunk 1 above)
Comment (MV88) [reply web/client/components/notifications/NotificationContainer.jsx]: you cannot do that with react-int api, because they are injected from an HOC and can't be used in the LocaleUtils.
for what you are suggesting we should look at [Intl MessageFormat](https://github.com/yahoo/intl-messageformat)

Comment (mbarto) [reply web/client/components/notifications/NotificationContainer.jsx]: ok, for now
