### PR TITLE
3548 fix ui drag menu for coordinate editor (c125_annotations)

### LINKED ISSUE #3548: GFI via coordinate input
### Description
Add the possibility to use a coordinate editor for the GFI tool.
With all coordinate valid using Enter from keyboard will perform the GFI search.

We will also add two flags:
* enabledCoordEditorButton set to true by default
* showCoordEditor set to false by default

### PR DESCRIPTION
**Pull request by MV88**
## Description
This pr updates the drag button visibility in the various coordinate editor in the 

It also fixes the problem with focus when form goes invalid.

## Issues
 - Fix #3548

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
the drag menu appears in GFI panel even if there is only on row present

**What is the new behavior?**
now in the GFI the drag button does not option

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/misc/coordinateeditors/CoordinatesRow.jsx [hunk 1]
```diff
@@ -41,15 +42,17 @@ class CoordinatesRow extends React.Component {
...
-        const dragButton = (<div
-            className="square-button-md no-border btn btn-default"
-            style={{display: "flex" /*workaround for firefox*/}}
-            >
-            <Glyphicon
-            glyph="menu-hamburger"
-            disabled={!this.props.isDraggable}
-            style={{pointerEvents: !this.props.isDraggable ? "none" : "auto"}}
-        /></div>);
+        // drag button must be a button in order to shwo the disabled state
```
Comment (offtherailz) [inline web/client/components/misc/coordinateeditors/CoordinatesRow.jsx]: typo
```suggestion
        // drag button must be a button in order to show the disabled state
```

File: web/client/components/misc/coordinateeditors/CoordinatesRow.jsx [hunk 2]
```diff
@@ -25,28 +25,34 @@ class CoordinatesRow extends React.Component {
...
+        const dragButton = (
+            <div><Button
+                disabled={!this.props.isDraggableEnabled}
+                className="square-button-md no-border btn btn-default"
+                style={{display: "flex"/*workaround for firefox*/}}>
```
Comment (offtherailz) [inline web/client/components/misc/coordinateeditors/CoordinatesRow.jsx]: Cursor for draggable handle
```suggestion
                style={{display: "flex", cursor: this.props.isDraggableEnabled && 'grab'}}>
```
