### PR TITLE
Fix #1612. Extent calculation for GeoJson supported

### LINKED ISSUE #1612: Improve and Fix GeoJSon Extent calculation
GeoJson extent calculation is wrong and limited to the geometry (not supported feature and featurecollection).
We should support it and fix issues with validity of bounding box.

### PR DESCRIPTION
**Pull request by offtherailz**
Now GeoJson extent calculation support also `Feature` and `FeatureCollection` (before this only geometry was supported).

### CODE REVIEW

File: web/client/utils/CoordinatesUtils.js [hunk 1]
```diff
@@ -254,15 +255,34 @@ const CoordinatesUtils = {
...
-                geoJSON.geometies.reduce((extent, geometry) => {
+                return geoJSON.geometies.reduce((extent, geometry) => {
                     let ext = this.getGeoJSONExtent(geometry);
                     if (this.isValidExtent(ext)) {
-                        extent[0] = (ext[0] < newExtent[0]) ? ext[0] : newExtent[0];
-                        extent[1] = (ext[1] < newExtent[1]) ? ext[1] : newExtent[1];
-                        extent[2] = (ext[2] > newExtent[2]) ? ext[2] : newExtent[2];
-                        extent[3] = (ext[3] > newExtent[3]) ? ext[3] : newExtent[3];
+                        return [
+                            (ext[0] < extent[0]) ? ext[0] : extent[0],
```
Comment (mbarto) [inline web/client/utils/CoordinatesUtils.js]: can we create a function with this stuff, that is repeated many times?

Comment (offtherailz) [inline web/client/utils/CoordinatesUtils.js]: Sure, as you see the original one had many side effects. I didn't noticed they become exactly the same function after my refactor.
