### PR TITLE
fixed #1563 catalog pagination

### LINKED ISSUE #1563: Catalog pagination is not working
To reproduce on DEV

- Open the catalog
- Click search
- When the results are displayed, click on the pages numbers

Expected result: results pages changes

Actual result: nothing changes, no even the selected page

### PR DESCRIPTION
**Pull request by MV88**
The pageEvent.eventkey was undefined so I used the mousevent

see #1563

### CODE REVIEW

File: web/client/components/catalog/Catalog.jsx [hunk 1]
```diff
@@ -236,9 +236,9 @@ const Catalog = React.createClass({
     setCatalogUrl(e) {
         this.setState({catalogURL: e.target.value});
     },
-    handlePage(mouseEvent, pageEvent) {
-        if (pageEvent && pageEvent.eventKey !== undefined) {
-            let start = ((pageEvent.eventKey - 1) * this.props.pageSize) + 1;
+    handlePage(mouseEvent) {
+        if (mouseEvent) {
```
Comment (offtherailz) [inline web/client/components/catalog/Catalog.jsx]: Call it `eventKey

**Comment by Gnafu** [comment]
Can you redo the PR on the 2017.02.00 branch? (maybe squashed)

**Comment by MV88** [comment]
@Gnafu Sure. It was already planned
