### PR TITLE
#12237: fix the background selector show an error in console

### LINKED ISSUE #12237: The background selector show an error in console
## Description

There are issues 

## How to reproduce

- run mapstore locally
- open map

*Expected Result*

no error in console

*Current Result*

this error in console

Image

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by mahmoudadel54**
## Description

This PR includes resolving "Cannot update during an existing state transition" console error in BackgroundSelector. It includes:
- Refactored **BackgroundSelector.jsx**
- Moved the logic for detecting and adding the missing **Ellipsoid terrain** from the main function body into a **React.useEffect** hook

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#12237 

**What is the new behavior?**

The console error of background selector has been gone, resolved by the fix.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/background/BackgroundSelector.jsx [hunk 1]
```diff
@@ -89,14 +82,35 @@ function BackgroundSelector({
...
+            updateNode(layerToAdd.id, 'layers', layerToAdd);
+        } else {
+            addLayer(layerToAdd);
+            onPropertiesChange(layerToAdd.id, {visibility: true});
+        }
     };
     const currentBackground = getCurrentBackground();
     const currentTerrain = getCurrentTerrainLayer();
+    // Include the ellipsoidal terrain if missing
+    React.useEffect(() => {
```
Comment (MV88) [inline web/client/components/background/BackgroundSelector.jsx:96]: fix import 
```suggestion
    useEffect(() => {
```

**Review by MV88 — CHANGES_REQUESTED** [review]

**Review by MV88 — APPROVED** [review]

**Comment by offtherailz** [comment]
Successfully created backport PR for `2026.01.xx`:
- #12297
