### PR TITLE
Fix #2222. Support for circle reprojection in leaflet

### LINKED ISSUE #2222: Circle spatial filter shows different selections on high denominator scales
tested on leaflet.
to reproduce:
- select a WMS layer
- open feature grid
- select advanced search
- select circle spatial filter and draw on map
- click on search
- back to advanced search
now the circle has a different geometry (high denominator scales)

while drawing the filter
circle1

back to advanced search
circle2

difference between above images
circle

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This changes make the DrawSupport mask the different radius management for circles in leaflet. 
From the external point of view, draw support now is identical to openlayer's one, and circle is virtually drawn on projected system (so the geometry will be a real circle on EPS:3857).
Internal conversion provides proper scaling of leaflet radius to draw circles in leaflet.
## Issues
 - Fix #2222

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
 - Circles are not reloaded correctly in leaflet. 
 - Switching from OL to leaflet doesn't preserve the same circle as filter
 - Searching using the circle drawn provides wrong results (e.g. some features that seems to be inside the circle on the map are not shown in results). 

**What is the new behavior?**
 - The circle is correctly reloaded (I noticed on first load the `DrawSupport` shows the 100 points polygon, then when you change, for instance from the query panel, some parameter, you will see again a real circle. I wasn't able to remove this behavior this time. Anyway is doesn't seems to create any problem)
 - You can switch from OL to Leaflet preserving the circle filter
 - Search results are now consistent with the map

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

**NOTE**: Don't think it is a breaking change at all. The filter in leaflet now will be generated as with openlayers, ad a geometry in EPSG:3857, before it was a circle in EPSG:4326 that caused many issues in terms of search result expectation, for instance. 

**Other information**:
`DrawSupport` is a little too complicated. We should define and document an API to interact with it and reduce duplication.

### CODE REVIEW

File: web/client/components/map/leaflet/DrawSupport.jsx [hunk 1]
```diff
@@ -17,7 +17,72 @@ const assign = require('object-assign');
...
+            radius: mRadius
+        };
+    }
+
+    // calculate
+    const lonRadius = (mRadius / 40075017) * 360 / Math.cos(L.LatLng.DEG_TO_RAD * (center[1]));
+    const projCenter = CoordinatesUtils.reproject(center, "EPSG:4326", projection);
+    if (lonRadius) {
+        const checkPoint = CoordinatesUtils.reproject([center[0] + lonRadius, center[1]], "EPSG:4326", projection);
+        return {
```
Comment (mbarto) [inline web/client/components/map/leaflet/DrawSupport.jsx]: srs is missing
