### PR TITLE
Closes geosolutions-it/austrocontrol-C125#26

### LINKED ISSUE #2619: Problem downloading KML file format
### Description
Problem with KML file format (when you download and reimport it). 
The problem seem to be in the downloaded file format.

### Bug:

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*

- open mapstore and login
- open a new map
- add from the WMS demo catalog a layer (example this one: Unesco Items)
- open the TOC and download using KML file format 
- click home button and open a NEW MAP
- using the burger menù import the downloaded KML file as a LOCAL VECTOR FILE
- verify that you can add this KML file (a problem is if you have an error message and you can't add the file to the map).

*note this other point observed: you can import this dowloaded file on QGIS but you can't do the same on Google Earth

*Expected Result*

- you can add this KML file to the map

*Current Result*

- you can't add it

### PR DESCRIPTION
**Pull request by kappu72**
## Description
Added more file types to FileFormatUtils.
## Issues
 - Fix  geosolutions-it/austrocontrol-C125#26
 - Fix #2619

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [X] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Some types of exported files were missing file ext. This generate a issue when importing i.e. kml exported file.

**What is the new behavior?**
The ext is correctly added to the exported file

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [X] No

### CODE REVIEW

**Comment by mbarto** [comment]
Didn't we talked about introducing a default (calculated) extension for unrecognized formats?

File: web/client/utils/FileFormatUtils.js [hunk 1]
```diff
@@ -1,4 +1,10 @@
 const {head} = require('lodash');
+
+const getFormatByName = (outF) => {
+    const extension = outF.split('-')[1];
```
Comment (mbarto) [inline web/client/utils/FileFormatUtils.js]: I would split on "any non word char" to consider more special symbols.

outF.split(/[^\w]/)

Comment (kappu72) [reply web/client/utils/FileFormatUtils.js]: ok
