### PR TITLE
Fix #1873 Wrong Font Family and Size on Print plugin

### LINKED ISSUE #1873: Wrong Font Family and Size on Print plugin
The print output displays the wrong font family and size

### PR DESCRIPTION
**Pull request by allyoucanmap**

### CODE REVIEW

File: web/client/plugins/print/index.js [hunk 1]
```diff
@@ -119,6 +119,7 @@ const Font = connect((state) => ({
     italic: state.print && state.print.spec && state.print.spec.italic
 }), {
     onChangeFamily: setPrintParameter.bind(null, 'fontFamily'),
+    onChangeName: setPrintParameter.bind(null, 'fontName'),
```
Comment (mbarto) [inline web/client/plugins/print/index.js]: fontName is not used, I think. You still use only fontFamily in PrintUtils. Maybe we don't need a duplicated property at all
