### PR TITLE
Adding tests for increasing coverage on c125_annotations branch and other fixes

### LINKED ISSUE #3601: add to Measure tool the coordinate editor
### Description
Add the possibility to use a coordinate editor for measure tool.
If present it will render as a side panel, if not it will render in a dialog.

### PR DESCRIPTION
**Pull request by MV88**
## Description
This pr wants to increase the coverage

## Issues

Fix #3601

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: tests for coverage

**What is the current behavior?** (You can also link to an open issue here)
coverage < 80%

**What is the new behavior?**
coverage >= 81%

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
- add a missing translation.
- fixed an error thrown when editing an annotation (you have an invalid coordinate and you go to the annotations styler)

### CODE REVIEW

File: web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx [hunk 1]
```diff
@@ -13,6 +13,57 @@ const assign = require('object-assign');
...
+        drawStatus: "drawOrEdit",
+        features: [props.feature],
+        options: {
+            drawEnabled: false,
+            editEnabled: true,
+            addClickCallback: true
+        },
+        ...props
+    });
+    support.props.map.dispatchEvent({
```
[the remark this answers is not in the document]
Comment (MV88) [reply web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx]: i would not call it renderFeature because it does not render a feature. instead it renders the DrawSupport component that "does things" like drawing or enabling draw/modify interactions only.. and so on.
i'll remove the second dispatch.

i've created renderThenClick which includes the line "renderDrawSupport();" because it needs to enter will receive props and by doing this i'm saving it to being written every time i need renderThenClick.
eventually i can have two props one for the first on for the second.

File: web/client/test-resources/drawsupport/features.js [hunk 2]
```diff
@@ -52,5 +52,498 @@ module.exports = {
...
+            type: 'Feature',
+            geometry: {
+                type: 'Polygon',
+                coordinates: [
+                [
+                  [
+                    -7.066692092065635,
+                    47.17477833929903
+                  ],
+                  [
```
Comment (offtherailz) [inline web/client/test-resources/drawsupport/features.js]: I think 4 points are enough (the first and last of course should remain)

**Comment by offtherailz** [comment]
Some things to do: 
 - [ ] Document styling rules
 - [ ] Cicular dependencies detected: 
```
WARNING in Circular dependency detected:
web/client/utils/MapInfoUtils.js -> web/client/components/data/identify/viewers/JSONViewer.jsx -> web/client/components/data/identify/viewers/TemplateViewer.jsx -> web/client/utils/MapInfoUtils.js

WARNING in Circular dependency detected:
web/client/components/data/identify/viewers/JSONViewer.jsx -> web/client/components/data/identify/viewers/TemplateViewer.jsx -> web/client/utils/MapInfoUtils.js -> web/client/components/data/identify/viewers/JSONViewer.jsx

WARNING in Circular dependency detected:
web/client/components/data/identify/viewers/TemplateViewer.jsx -> web/client/utils/MapInfoUtils.js -> web/client/components/data/identify/viewers/JSONViewer.jsx -> web/client/components/data/identify/viewers/TemplateViewer.jsx

WARNING in Circular dependency detected:
web/client/utils/AnnotationsUtils.js -> web/client/utils/DrawSupportUtils.jsx -> web/client/utils/AnnotationsUtils.js

WARNING in Circular dependency detected:
web/client/utils/DrawSupportUtils.jsx -> web/client/utils/AnnotationsUtils.js -> web/client/utils/DrawSupportUtils.jsx

WARNING in Circular dependency detected:
web/client/utils/featuregrid/EditorRegistry.jsx -> web/client/components/data/featuregrid/editors/customEditors.jsx -> web/client/components/data/featuregrid/editors/DropDownEditor.jsx -> web/client/utils/featuregrid/EditorRegistry.jsx

WARNING in Circular dependency detected:
web/client/components/data/featuregrid/editors/customEditors.jsx -> web/client/components/data/featuregrid/editors/DropDownEditor.jsx -> web/client/utils/featuregrid/EditorRegistry.jsx -> web/client/components/data/featuregrid/editors/customEditors.jsx

WARNING in Circular dependency detected:
web/client/components/data/featuregrid/editors/DropDownEditor.jsx -> web/client/utils/featuregrid/EditorRegistry.jsx -> web/client/components/data/featuregrid/editors/customEditors.jsx -> web/client/components/data/featuregrid/editors/DropDownEditor.jsx
```

File: web/client/test-resources/drawsupport/features.js (hunk 2 above)
Comment (MV88) [reply web/client/test-resources/drawsupport/features.js]: this is a circle transformed into a polygon with 100 points and it is needed.
maybe we can add a function that generates random coords or reuse [transformLineToArcs](https://github.com/geosolutions-it/MapStore2/blob/c125_annotations/web/client/utils/CoordinatesUtils.js#L554)

File: web/client/components/map/openlayers/MeasurementSupport.jsx [hunk 3]
```diff
@@ -90,7 +90,11 @@ class MeasurementSupport extends React.Component {
                 }
             ), newProps);
             if (isPolygon(ft)) {
-                props = set("measurement.feature.geometry.coordinates", [props.measurement.feature.geometry.coordinates], props);
+                if (props.measurement.feature.geometry.coordinates.length >= 4 && isEqual(head(props.measurement.feature.geometry.coordinates), last(props.measurement.feature.geometry.coordinates))) {
```
Comment (offtherailz) [inline web/client/components/map/openlayers/MeasurementSupport.jsx]: Explain why remove the last coordinate for polygons.
