### PR TITLE
Fix #2685. Removed for of statements

### LINKED ISSUE #2685: Can not open certain maps with OpenLayers / IE11
### Description
Maps with tileXYZ layers that contain subdomains can not be opened in IE11

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- 10 and 11

*Steps to reproduce*

- Use Internet Explorer 11 to open [this map]( https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/2698)

*Expected Result*

- The map can open

*Current Result*

- The map remain in loading

### Other useful information (optional):
It seems to be due to usage of `of` (2 times)
 https://github.com/geosolutions-it/MapStore2/blob/a1ff7d26ad3996bff413812c873fd5b6573dc168/web/client/components/map/openlayers/plugins/TileProviderLayer.js#L35
not supported in IE 11

something like 
```
if (opt.subdomains) {
        opt.subdomains.map( c => urls.push(template(url.replace("{s}", c), opt)));
    } else {
        ['a', 'b', 'c'].map( c => urls.push(template(url.replace("{s}", c), opt)));
    }
``` 
make the application work in IE11.

Check my temp work at:
https://github.com/offtherailz/MapStore2/tree/fix_%232685

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
IE11 does not support for...of statements. I removed all of them. See notes below.
## Issues
 - Fix #2685

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** 

 - [x] Bugfix
 
**What is the current behavior?** 
 - see  #2685

**What is the new behavior?**
- the map referred in #2685 works

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

**Other information**:
I didn't find a way in lint to skip for...of statements 
 - ecmaFeatures.forOf doesn't seem to work
 - I found also ForOfStatement for entry no-restricted-syntax but probably belongs to a most recent version of eslint) 
 - babel [transform-es2015-for-of/](https://babeljs.io/docs/plugins/transform-es2015-for-of/) uses interable so is not usable too. 
So I wasn't able create a test or avoid future problems of this kind

### CODE REVIEW

File: web/client/api/GeoStoreDAO.js [hunk 1]
```diff
@@ -164,7 +164,7 @@ const Api = {
     },
     updateResourcePermissions: function(resourceId, securityRules) {
         let payload = "<SecurityRuleList>";
-        for (let rule of securityRules.SecurityRuleList.SecurityRule) {
+        (securityRules && securityRules.SecurityRuleList && _.castArray(securityRules.SecurityRuleList.SecurityRule) || []).forEach( rule => {
```
Comment (mbarto) [inline web/client/api/GeoStoreDAO.js]: let's use a reduce

Comment (offtherailz) [reply web/client/api/GeoStoreDAO.js]: Yes, I didn't want to change this part not covered by a test. going to externalize SecurityRule and test it
