### PR TITLE
Fix #5750 Map Catalog remains empty

### LINKED ISSUE #5750: Map Catalog remains empty
## Description

If I search for a map in Home and then I delete that map, the map catalog remains empty also if I perform a new search leaving the search field empty. 

test_map_save

## How to reproduce

- Create a map
- From home page search for that map (**the map is the only one available in the search result**)
- Delete the map

*Expected Result*

The search field should:

- Maintain the search text or
- Maintain the current bheavior (the field is cleaned up) but the map catalog should be properly refreshed 

*Current Result*

- The search input field is cleaned up and the map catalog remains empty also performing new searches laving the search field empty

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Properly account for empty results in getMapsResourcesByCategoryEpic.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#5750 

**What is the current behavior?**

#5750 

**What is the new behavior?**

The search text is maintained.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/epics/maps.js [hunk 1]
```diff
@@ -295,7 +295,12 @@ const getMapsResourcesByCategoryEpic = (action$, store) =>
                     .switchMap((response) => getContextNames(response).switchMap(responseWithContext => {
                         // category is required to identify maps for detail card. It's missing from this entry point
                         return Rx.Observable.of(
-                            mapsLoaded({...responseWithContext, results: responseWithContext?.results?.map(res => ({...res, category: {name: "MAP"}}))}, opts.params, searchText)
+                            mapsLoaded({
+                                ...responseWithContext,
+                                results: isArray(responseWithContext.results) ?
```
Comment (offtherailz) [inline web/client/epics/maps.js:300]: responseWithContext.results is "" in case of empty results. I suggest to use [] as default, to avoid other errors in the future.

Comment (vlt1) [reply web/client/epics/maps.js:300]: @offtherailz it should be noted that the server in case of empty results returns an empty string for some reason which is not very sensible, and probably should also be fixed.

Comment (offtherailz) [reply web/client/epics/maps.js:300]: Yes, the server has 2 problems with lists.  
- With only one elements it returns the single element, not an array with 1 element
- With 0 elements, it returns an empty string

There is an issue [open](https://github.com/geosolutions-it/geostore/issues/56) for a lot of time, but wasn't fixed yet.

This issues should be work-arounded anyway at GeoStoreAPI level, or I see that it is solved in `getContextNames` (line 249). 
```
const maps = isArray(results) ? results : (results === "" ? [] : [results]);
```

**Comment by offtherailz** [comment]
Please @vlt1 backport this PR for 2020.02.xx
