### PR TITLE
Fix #4205 Run-time error when creating charts from Attribute Table

### LINKED ISSUE #4205: Run-time error when creating charts from Attribute Table
### Description
If I set a column filter in the Attribute Table (quick filter), I run-time error is thrown while creating a chart with the given filter if a try to open the query panel to define an additional filter.

landmark_chart

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10828) as Admin
- Open the Attribute Table for the layer **poly_landmarks_permissions**
- Set a quick filter in one column of the Attribute Table
- Generate a chart from the Attribute Table trying to define an aditional filter by opening the Query Panel inside the Chart wizard

*Expected Result*

- I can create a Chart using the given quick filter

*Current Result*

- I cannot create a chart, a run-time error is thrown

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Run-time error when creating charts from Attribute Table

## Issues
 - #4205

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/geosolutions-it/MapStore2/issues/4205

Cannot create a chart, a run-time error is thrown while creating new chart with attribute filter.

**What is the new behavior?**

   After you filled the attribute filter, we've updated the static filter field values such as (attribute name, groping default options, filter value), but not the dynamic (filtered options), because they loaded from the API after triggered event updateFilterField for autocomplete. Because of dynamic options was undefined, this bug is appeared. And paginated autocomplete expect non-empty filterField options.
   Fixed, by check options field.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/data/query/AutocompleteFieldHOC.jsx [hunk 1]
```diff
@@ -56,6 +56,10 @@ class AutocompleteFieldHOC extends React.Component {
     };
 
     getPagination = (options) => {
+        if (!this.props.filterField.options) {
```
Comment (MV88) [inline web/client/components/data/query/AutocompleteFieldHOC.jsx]: hi, Can you add a unit test?
in this case seems needed to prevent future  run time error

Comment (vlt1) [reply web/client/components/data/query/AutocompleteFieldHOC.jsx]: @MV88 test is provided

**Comment by tdipisa** [comment]
@vlt1 please, can you backport this to the stable branch 2019.02.xx?
