### PR TITLE
fix #2931 added {onMouseEnter, onMouseLeave} mouse events to side card

### LINKED ISSUE #2931: Side card is no longer passing mouse events
### Description
this cause highlight for annotations not being triggered

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open annotation panel and pass over an annotations

*Expected Result*

- style of geometry changes

*Current Result*

- it does not change

### PR DESCRIPTION
**Pull request by MV88**
## Description
fix mouse events for side card

## Issues
 - Fix #2931

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
mouse events not passed to side card

**What is the new behavior?**
{onMouseEnter, onMouseLeave} are passed to the side card enabling highlight for annotations for example.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/misc/cardgrids/SideCard.jsx [hunk 1]
```diff
@@ -26,30 +26,33 @@ const React = require('react');
...
-    <div className="ms-head">
-        {preview && <div className="mapstore-side-preview">
-            {preview}
-        </div>}
-        <div className="mapstore-side-card-info">
-            <div className="mapstore-side-card-title">
-                <span>{title}</span>
+
+module.exports = ({body, className = '', style = {}, onClick=() => {}, size, title, preview, description, caption, tools, selected, ...more} = {}) => {
+    const {onMouseEnter, onMouseLeave} = more;
```
Comment (offtherailz) [inline web/client/components/misc/cardgrids/SideCard.jsx]: To avoid to pass these 2 methods to onClick, destructure props instead of `more`
