### PR TITLE
Fix #2951 circle draw and styles annotations

### LINKED ISSUE #2951: Problem with style for annotations and circle drawing functionality
### Description
see title

this affects only branch c125_annotations

*Steps to reproduce*

- see issues:
https://github.com/geosolutions-it/austrocontrol-C125/issues/60
https://github.com/geosolutions-it/austrocontrol-C125/issues/61

### PR DESCRIPTION
**Pull request by MV88**
## Description
Fix styles for annotations and circle drawing functionality

## Issues
 - Fix #2951 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
you can't draw a circle, 
you can't change style for an annotations

**What is the new behavior?**
you can do both

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/utils/ColorUtils.js [hunk 1]
```diff
@@ -159,6 +159,57 @@ const ColorUtils = {
         }
     },
     colorToHexStr: (color = 'red') => tinycolor(color).toHexString(),
+    /**
```
Comment (mbarto) [inline web/client/utils/ColorUtils.js]: We already include tinycolor2 that should have all these functions available
