### PR TITLE
IFC position controller no longer working #11086

### LINKED ISSUE #11086: IFC position controller no longer working
## Description

IFC position controller no longer works. This is a regression for 2024.02 series

## How to reproduce

- Open https://qa-mapstore.geosolutionsgroup.com/mapstore/#/context/demo_context/44920
- Switch to 3D 
- Zoom to the IFC layer in TOC
- Open layer settings and go to the display tab to change the IFC position

Image

*Expected Result*

The position changes according to user changes in the form (e.g. the height)

*Current Result*

The IFC doesn't move

Working as expected in 2024.02.02 see [here the same map](https://mapstore.geosolutionsgroup.com/mapstore/#/context/demo_context/9954).

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by rowheat02**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 

 
fixes #11086
**What is the current behavior?**

#11086
Changes to the modal properties, such as updating the center latitude and longitude, did not reflect on the map.

**What is the new behavior?**
Now, any changes made to the modal properties are correctly applied and reflected on the map.

https://github.com/user-attachments/assets/b597546a-8166-4729-a9b2-16f6cdc0ae75

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/map/cesium/plugins/ModelLayer.js [hunk 1]
```diff
@@ -154,12 +154,11 @@ const createLayer = (options, map) => {
             add: () => {}
         };
     }
-    let primitives;
+    let primitives = new Cesium.PrimitiveCollection({ destroyPrimitives: true });
     return {
         detached: true,
         primitives,
```
Comment (allyoucanmap) [inline web/client/components/map/cesium/plugins/ModelLayer.js:160]: I think we should take the initialization  `new Cesium.PrimitiveCollection` inside the add method and instead we should replace primitives with a getPrimitives function so we are able to get the latest updated primitives inside the update function of the layer

```js
    let primitives;
    return {
        detached: true,
        getPrimitives: () => primitives,
```

Could you please test if this approach works?

**Review by allyoucanmap — CHANGES_REQUESTED** [review]

File: web/client/components/map/cesium/plugins/ModelLayer.js (hunk 1 above)
Comment (rowheat02) [reply web/client/components/map/cesium/plugins/ModelLayer.js]: Updated!

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this fix on dev and let us know when we can backport on 2025.01.xx, thanks

**Comment by ElenaGallo** [comment]
Test passed, @rowheat02 please backport to 2025.01.xx. Thanks
