### PR TITLE
Fix #3415 Layer properties are not accessible if its style is invalid

### LINKED ISSUE #3415: Layer properties are not accessible if its style is invalid
### Description
In some cases styles are created and updated correctly but when apply to the layer return an exception.
If GetMap has exception TOCItemSettings is not accessible and the style parameters can't be changed.

* Following style cause the issue
```
@styleTitle 'Solid fill';
@styleAbstract '';

[this_is_not_a_param = 'a'] {
	fill: #aaaaaa;
}
```

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map with vector layer
- select the layer and open the settings of layer
- select style tab
- create a new style and edit it
- write the style* that cause the error

*Expected Result*

- There should be a way to access the parameters to update the layer parameters or at least reset the layer parameters to ensure that the error depends on wrong paramaters

*Current Result*

- Layer parameters can't be chaged and settings aren't accessible

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
This PR introduces the possibility to access the settings of a layer even if it has error so if a setting causes an error is possible to update it.

## Issues
 - Fix #3415

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
#3415 

**What is the new behavior?**
It's possible to access layer properties even if there is an error

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/TOC/Toolbar.jsx [hunk 1]
```diff
@@ -133,7 +133,7 @@ class Toolbar extends React.Component {
         status = isSingleGroup ? 'GROUP' : status;
         status = selectedLayers.length > 1 & selectedGroups.length === 0 ? 'LAYERS' : status;
         status = selectedGroups.length > 1 && !isSingleGroup ? 'GROUPS' : status;
-        status = this.props.selectedLayers.length > 0 && this.props.selectedLayers.filter(l => l.loadingError === 'Error').length === this.props.selectedLayers.length ? 'LAYERS_LOAD_ERROR' : status;
+        status = this.props.selectedLayers.length > 0 && this.props.selectedLayers.filter(l => l.loadingError === 'Error').length === this.props.selectedLayers.length ? `${status}_LOAD_ERROR` : status;
```
Comment (offtherailz) [inline web/client/components/TOC/Toolbar.jsx]: please document getStatus. Is not too much clear what are the possible states of status. Please include all the definitions

**Comment by tdipisa** [comment]
@allyoucanmap please provide a backport to 2019.01.xx
