### PR TITLE
Fix #2990 solve problem to import/export and print for annotation

### LINKED ISSUE #2990: Import/Export and Print for Annotations should support FeatureCollection
### Description
We will change the annotation from a Feature with a GeometryCollection into a Feature with type FeatureCollection

This has broken the import/export and print functionalities for Annotations

other bugs:
- when entering in 3d mode it was showing annotations tool from burge menu , now are also hidden from the toc
- custom style for length great circle are not applied

### PR DESCRIPTION
**Pull request by MV88**
## Description
Fixed:
- Import/export annotations
- Print and print preview now works correctly
- Disabled annotations for cesium
- Fixed GFI for feature collections
- Changed style for length and bearing measures
here is a preview
image

- Added documentation to local-config for measurement customization

## Issues
 - Fix #2990

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see issue #2990 
other bugs:
- when entering in 3d mode it was showing annotations tool from burge menu , now are also hidden from the toc
- custom style for length great circle are not applied

**What is the new behavior?**
all those have been fixed.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

if you do not want to enabled the custom style for the annotation you have to set this in the configuration:
```
"initialState": {
  "defaultState": {
    "measurement": {
      "customStartEndPoint": false
    }
  }
}
```

### CODE REVIEW

File: web/client/components/map/openlayers/MeasurementSupport.jsx [hunk 1]
```diff
@@ -84,6 +98,16 @@ class MeasurementSupport extends React.Component {
         var vector;
         var draw;
         var geometryType;
+        let {customStartEndPoint} = newProps.measurement;
```
Comment (offtherailz) [inline web/client/components/map/openlayers/MeasurementSupport.jsx]: Why do you need these checks? You can not simply set customStartEndPoint (style)? I should name it startEndPointStyle
