### PR TITLE
Fix #3075 legend missing message

### LINKED ISSUE #3075: Legend no more shows the missing message
### Description
If you try to load the legend from layer MARCIAPIEDE it should show the message error "Legend is not available"
This layer is available only on Genova test env

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Login and open a new map
- Add MARCIAPIEDE layer and open TOC
- Click on > to show the legend of that layer

*Expected Result*

- The message "Legend is not available" should appear

*Current Result*

An image of 1px x 2 px is shown (i.e you can't see it because has the same color of the background)

### PR DESCRIPTION
**Pull request by MV88**
## Description
fix legend messages

## Issues
 - Fix #3075

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see issue

**What is the new behavior?**
see issue

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/TOC/fragments/legend/Legend.jsx [hunk 1]
```diff
@@ -74,10 +74,15 @@ class Legend extends React.Component {
     }
     render() {
         if (!this.state.error && this.props.layer && this.props.layer.type === "wms" && this.props.layer.url) {
-            return <img onError={this.onImgError} src={this.getUrl(this.props)} style={this.props.style}/>;
+            return <img onError={this.onImgError} onLoad={(e) => this.validateImg(e.target)} src={this.getUrl(this.props)} style={this.props.style}/>;
         }
         return <Message msgId="layerProperties.legenderror" />;
     }
+    validateImg = (img) => {
+        if (img.height <= 1 && img.width <= 2) {
```
Comment (mbarto) [inline web/client/components/TOC/fragments/legend/Legend.jsx]: are we using random numbers?
