### PR TITLE
Fix #3913 GFI window does not close when opening the catalog (#3913)

### LINKED ISSUE #3913: Annotations - GFI window does not close when opening the catalog from the TOC
### Description
When clicking any annotation on the map the GFI tool window open. If you try to add some layer from the 'Add Layer' button of the TOC, the GFI window should close and the catalog window should become visible. The GFI window does not close and the catalog window is not visible (it is behind the GFI one).

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open mapstore
- open a map with some annotations
- click on one (or more) annotation
- verify the GFI window open (do not close it)
- open the TOC
- click on 'Add Layer'
- verify the Catalog window opens and the GFI one closes

*Expected Result*

- When clicking on 'Add Layer' the Catalog window opens and the GFI one closes

*Current Result*

- When clicking on 'Add Layer' the Catalog window opens but the GFI does not close

### Other useful information (optional):
The problem can be generalized, it happens not only with annotations layer but with any layer.

### PR DESCRIPTION
**Pull request by kasongoyo**
fix #3913

## Description
Fix GFI window fails to close when opening the catalog from TOC, see #3913

## Issues
 - #3913
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3913 

**What is the new behavior?**
GIF close on opening catalog from TOC

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/controls.js [hunk 1]
```diff
@@ -16,5 +18,13 @@ module.exports = {
                 return Rx.Observable.of(action.action);
             }
             return Rx.Observable.of(action.elseAction.call());
-        })
+        }),
+
+    setControlPropertiesEpic: (action$) =>
+        action$
```
Comment (allyoucanmap) [inline web/client/epics/controls.js]: I think this epic belongs to GFI because it's related to the behaviour of Identify. 
I think it's better to move this epic in identify epic and use a more specific name eg. `enabledCatalogClosesIdentifyEpic`
@offtherailz what do you think?

Comment (kasongoyo) [reply web/client/epics/controls.js]: Noted
