### PR TITLE
Fix #3932 zoom to feature selected on search result extends beyond viewport

### LINKED ISSUE #3932: Zoom to feature taken from nominatim results does not fit the viewer
### Description
the features such as cities added from nominatim are not zoomed correctly after being selected

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- search "liguria, genova"
- click on first result
image

*Expected Result*

image

*Current Result*

- Describe here the current behavior
image
image

### Other useful information (optional):
this happen also on prod
this is a good issue for @offtherailz

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix 3932

## Issues
 - #3932 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3932 

**What is the new behavior?**
Screenshot 2019-09-02 at 12 15 01

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/search.js [hunk 1]
```diff
@@ -149,24 +148,9 @@ export const searchItemSelected = action$ =>
                 }
 
                 let bbox = item.bbox || item.properties.bbox || toBbox(item);
-                let mapSize = action.mapConfig.size;
-                // zoom by the max. extent defined in the map's config
-                let newZoom = mapUtils.getZoomForExtent(CoordinatesUtils.reprojectBbox(bbox, "EPSG:4326", action.mapConfig.projection), mapSize, 0, 21, null);
```
Comment (offtherailz) [inline web/client/epics/search.js]: Please use the maxZoom (21) in this line in the zoomToExtent action (see API).
It's useful in case of points, so test it with single points.

File: web/client/epics/__tests__/search-test.js [hunk 2]
```diff
@@ -219,7 +219,7 @@ describe('search Epics', () => {
 
         let actions = store.getActions();
         expect(actions.length).toBe(6);
-        let expectedActions = [CHANGE_MAP_VIEW, TEXT_SEARCH_ADD_MARKER, TEXT_SEARCH_RESULTS_PURGE, TEXT_SEARCH_NESTED_SERVICES_SELECTED, TEXT_SEARCH_TEXT_CHANGE ];
+        let expectedActions = [ZOOM_TO_EXTENT, TEXT_SEARCH_ADD_MARKER, TEXT_SEARCH_RESULTS_PURGE, TEXT_SEARCH_NESTED_SERVICES_SELECTED, TEXT_SEARCH_TEXT_CHANGE ];
         let actionsType = actions.map(a => a.type);
```
Comment (offtherailz) [inline web/client/epics/__tests__/search-test.js]: Please check also maxZoom and bbox presence. 
This feature was present but not tested, so please check it.

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to the stable branch 2019.02.xx?
