### PR TITLE
5506. add page reload if location the same. 5503. Issue with Map Catalog

### LINKED ISSUE #5503: Issue with Map Catalog
## Description

If I select a map that is referencing an app context where the right sidepanel is not present for some reason but the nav toolbar yes,  the nav toolbar remains in a wrong position.

## How to reproduce

-  Open a context with the Map Catalog tool (for example [this one](https://dev.mapstore2.geo-solutions.it/mapstore/#/context/plui_advanced))
-  Using the Map Catalog tool open a map belonging to a context where the Nav toolbar is present (for esample the map with name **test_nav_map**, that belongs to the context [TestNav](https://dev.mapstore2.geo-solutions.it/mapstore/#/context/TestNav))

*Expected Result*

The map loads with the Nav Toolbar properly positioned.

*Current Result*

toolbar_issue

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by jstrR**
## Description

Reloads page if router is the same. See #5506 
Fixes #5503 by adding a toggleCatalog.
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#5506 
#5503 

**What is the new behavior?**

Page reloads if location changes to the same
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by jstrR** [comment]
This PR fixes both #5503 and #5506

File: web/client/components/mapcatalog/MapCatalogPanel.jsx [hunk 1]
```diff
@@ -69,6 +69,22 @@ const loadPage = ({searchText = '', limit = 12} = {}, page = 0) => searchMaps({
     }
 });
 
+const onClickHandler = (map, router, mapType, toggleCatalog) => {
```
Comment (MV88) [inline web/client/components/mapcatalog/MapCatalogPanel.jsx:72]: is it possible to add a unit test at least for the reload behaviour?

**Comment by tdipisa** [comment]
@jstrR can you please provide a backport PR to the 2020.02.xx branch for the next release? Thank you.
