### PR TITLE
Fix #3311 fix mouse positions roundings

### LINKED ISSUE #3311: Mouse position shows wrong coordinates
### Description
The coordinates of the mouse position are wrong!!
When showing coordinates based on the mouse position, minutes are increased and decreased whenever a threshold of 30 seconds is reached. The wrong position is shown for latitude and longitude.

### In case of Bug (otherwise remove this paragraph)
*Browser Tested*
- [x] Edge
- [x] Chrome
- [x] Firefox

*Steps to reproduce*
-switch on show/hide position
-zoom in until the mouse movement range is within one minute
-move the mouse from below 30" to slightly above 30" and observe the displayed minutes
-do the movement along latitude and longitude

*Expected Result*
Minutes should be increased when reaching 60 seconds

### PR DESCRIPTION
**Pull request by MV88**
## Description
There was an unintended rounding when using 0 fractional digits in numberFormat when the values were fractional like 25.506 and so on.

## Issues
 - Fix #3311

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
there are problems with mouse position where minutes are not updated correctly (see issue #3311)
because it were using a fractional number 

**What is the new behavior?**
It does not rounds up the number if MaximumFractionalDigits is set to 0, but it uses an integer number

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No 

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

One possible alternative solution were to put the roundingBehaviour inside numberParams object.

### CODE REVIEW

File: web/client/utils/CoordinatesUtils.js [hunk 1]
```diff
@@ -791,6 +791,16 @@ const CoordinatesUtils = {
             zoom: map.zoom,
             crs: 'EPSG:4326'
         };
+    },
+    /**
+     * choose to round or floor value incase of 0 fractional digits
+     * @return the rounded value or the orignal one
+    */
+    checkRounding: ({ roundingBehaviour = "round", value = 0, maximumFractionDigits = 0 } = {}) => {
+        if (maximumFractionDigits === 0 && !!Math[roundingBehaviour]) {
```
Comment (mbarto) [inline web/client/utils/CoordinatesUtils.js]: Math[roundingBehaviour] is truthy, you don't need the !! operator,  think

Comment (MV88) [reply web/client/utils/CoordinatesUtils.js]: yes i know, i wanted to make it more clear (to newBies).  going to change it.
