### PR TITLE
C125 annotations

### LINKED ISSUE #2733: Printing a map with vector style changed (Stroke and Fill) you still get a map with deafult blue style in the end
### Description
Printing a map with vector style changed (Stroke and Fill) you still get a map with deafult blue style in the end

### In case of Bug
*Browser Affected*
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- import a shape file (.kml, .gpx or .shp) changing the default Stroke and Fill using other colors
- open the print tool 
- note that the first page has the previow with changed color
- click print 
- note that in the second page of the print tool colors are not as ypu have changed but are blue as default style

*Expected Result*
- you can print the map using other vector colors 

*Current Result*
- now you can print only using default blue color in the end

### Other useful information (optional):
immagine

### PR DESCRIPTION
**Pull request by kappu72**
## Description
Fix Chiara's comments on issue geosolutions-it/austrocontrol-C125#31.
It's now possible to edit vector style in the importer.
The vector style is correctly rendered when a map is loaded.

## Issues
 Fix geosolutions-it/austrocontrol-C125#31.
 Fix #2733

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
It's impossible to edit vector style in vector importer
The vector style isn't correctly rendered when a map is loaded

**What is the new behavior?**
It's now possible to edit vector style in the importer.
The vector style is correctly rendered when a map is loaded.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/utils/ColorUtils.js [hunk 1]
```diff
@@ -206,6 +207,14 @@ const ColorUtils = {
             g: rgb[1],
             b: rgb[2]
         };
-    }
+    },
+    /**
+    * convert any valid css color to rgba str
+    * @param (String) color any valid css colo
+    * @param (number) opacity 0 - 100 alpha value
```
Comment (MV88) [inline web/client/utils/ColorUtils.js]: Alpha should go from 0 to 1

File: web/client/utils/ColorUtils.js [hunk 2]
```diff
@@ -206,6 +207,14 @@ const ColorUtils = {
...
+    * @return (String) rgba string
+    */
+    colorToRgbaStr: (color = "#0000FF", alpha = 1) => tinycolor(color).setAlpha(toNumber(alpha)).toRgbString()
```
Comment (MV88) [inline web/client/utils/ColorUtils.js]: can you add a test for this function?

File: web/client/utils/ColorUtils.js [hunk 3]
```diff
@@ -206,6 +207,14 @@ const ColorUtils = {
             g: rgb[1],
             b: rgb[2]
         };
-    }
+    },
+    /**
+    * convert any valid css color to rgba str
+    * @param (String) color any valid css colo
```
Comment (MV88) [inline web/client/utils/ColorUtils.js]: typo: "css color"
