### PR TITLE
Fixed #2219 zoom to page

### LINKED ISSUE #2219: Zoom to page extent doesn't work with null geometry in feature grid
tested on MultiPolygon.
to reproduce:
- login as admin
- open the feature grid of a WMS layer
- enable edit mode
- remove the geometry from a feature and save
- disable edit mode
- click on zoom to page extent
now an error will throw because of null geometry

### PR DESCRIPTION
**Pull request by MV88**
## Description
Zoom to page fails if a feature in the pages has no geometry

## Issues
 - Fix #2219 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
actually it does not soozm because it fails internally to create the bbox

**What is the new behavior?**
now it does not fails and it zooms to the page

**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

File: web/client/components/data/featuregrid/toolbars/Toolbar.jsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const getSaveMessageId = ({saving, saved}) => {
     return "featuregrid.toolbar.saveChanges";
 };
 
-module.exports = ({events = {}, mode = "VIEW", selectedCount, hasChanges, hasGeometry, hasNewFeatures, isSimpleGeom, isDrawing = false, isEditingAllowed, saving = false, saved = false, isDownloadOpen, isColumnsOpen, disableToolbar, isSearchAllowed, disableDownload, displayDownload, isSyncActive = false, hasSupportedGeometry = true} = {}) =>
+module.exports = ({events = {}, mode = "VIEW", selectedCount, hasChanges, hasGeometry, hasNewFeatures, isSimpleGeom, isDrawing = false, isEditingAllowed, saving = false, saved = false, isDownloadOpen, isColumnsOpen, disableToolbar, isSearchAllowed, disableDownload, displayDownload, isSyncActive = false, hasSupportedGeometry = true, allFeaturesWithNoGeometry = false} = {}) =>
```
Comment (offtherailz) [inline web/client/components/data/featuregrid/toolbars/Toolbar.jsx]: maybe we could rename this parameter disableZoomTo

Comment (MV88) [reply web/client/components/data/featuregrid/toolbars/Toolbar.jsx]: i'll go for disableZoomAll because iis id is "zoom-all"
