### PR TITLE
Fix #3917 Widgets builder - layer filter

### LINKED ISSUE #3917: Widgets builder - layer filter
### Description
A widget based on a filtered layer doesn't update Itself on layer filter change. To update It a user should edit and save it again
This is related to #3785 

*Steps to reproduce*

- Create a filter on layer and save it.
- Create a table widget on filtered layer ad save it.
- Update the filter layer
Widget_issue

*Expected Result*
The table widget update accordingly 

*Current Result*

The widget doesn't update accordingly

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Widget objects have their own copy of properties of the layer that they belong to. It looks like when
layerFilter gets updated it only alters the main layer object in state.layers, but not any of the widgets.
I introduced an action that takes a layer object, goes through all widgets in DEFAULT_TARGET target,
finds those that have the same layer.id and updates their layer property with a new one, and an epic
that manages CHANGE_LAYER_PROPERTIES action and produces updateWidgetLayer action whenever
needed. For now it does that only on layerFilter updates.

## Issues
 - #3917 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Widgets don't update on filter changes of the layer that they belong to

**What is the new behavior?**
Widgets update their output on filter changes

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/epics/layers.js [hunk 1]
```diff
@@ -148,8 +149,25 @@ const updateSettingsParamsEpic = (action$, store) =>
             );
         });
 
+/**
```
Comment (offtherailz) [inline web/client/epics/layers.js]: move this epic to the widgets epics.js file

File: web/client/epics/layers.js [hunk 2]
```diff
@@ -148,8 +149,25 @@ const updateSettingsParamsEpic = (action$, store) =>
...
+ * Triggers updates of the layer property of widgets on layerFilter change
+ * @memberof epics.layers
+ * @param {external:Observable} action$ manages `CHANGE_LAYER_PROPERTIES`
+ * @return {external:Observable}
+ */
+const changeLayerPropertiesEpic = (action$, store) =>
```
Comment (offtherailz) [inline web/client/epics/layers.js]: move this epic in the widgets file, because is an effect of that concerns widgets, not layers

**Comment by tdipisa** [comment]
@vlt1 please, can you backport this to the stable branch 2019.02.xx?
