### PR TITLE
Fix #3243 circle radius problem for openlayers

### LINKED ISSUE #3243: Circle radius calculated after confirm in geometry details is wrong (OL only)
### Description
This problem happens if you have configurated to draw a geodesic Circle 
The radius is re-calculated from the approximated polygon and it is different from the starting one use to create that polygon.

inside spatialMethodOptions of cfg of QueryPanel add geodesic :true
`{"id": "Circle", "name": "queryform.spatialfilter.methods.circle", "geodesic": true},`

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
Chrome 69.0.3497.100

*Steps to reproduce*
- Open any map with a queryable layer "US Population Statistics" for example.
- Open featureGrid and query form
- Draw a Circle
- Enter geometry details and change its value to 10000 (zoom in/out to see it comfortably)
- Click on confirm ( the V icon)
- Re-enter the geometry details

*Expected Result*
- To see the same radius previously inserted

*Current Result*
- a different value is present. 

### Other useful information (optional):

that is because of [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/DrawSupport.jsx#L565-L568)

### PR DESCRIPTION
**Pull request by MV88**
## Description
see title

## Issues
 - Fix #3243 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
now the radius keeps the value inserted  in the geometry details form.

**What is the new behavior?**
see #3243 

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx [hunk 1]
```diff
@@ -22,6 +23,14 @@ describe('Test DrawSupport', () => {
         setTimeout(done);
     });
 
+    /**
+     * used to reduce a bit the boilerplate and ReactDom stuff
+     * TODO extend it to the other tests
+    */
+    const renderDrawSupport = (props = {}) => {
+        ReactDOM.render(<DrawSupport {...props}/>, document.getElementById("container"));
```
Comment (mbarto) [inline web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx]: You don't reduce the boilerplate if you use it only in one place / test.
It's useful to refactor code in external functions if they are used at least in a bunch of different places, expecially in tests, where being able to read the full test at once is more important than duplication.
If you have too much code in one test it's better to split it in two different tests.

File: web/client/components/map/openlayers/DrawSupport.jsx [hunk 2]
```diff
@@ -175,6 +175,11 @@ class DrawSupport extends React.Component {
         const olFeature = this.replaceFeatures(newProps);
         if (olFeature) {
             const feature = this.fromOLFeature(olFeature);
+            if (newProps.drawMethod === "Circle" && newProps && newProps.features && newProps.features.length && newProps.features[0] && newProps.features[0].radius >= 0) {
+                // this is needed because the calculation of the radius is wrong
```
Comment (offtherailz) [inline web/client/components/map/openlayers/DrawSupport.jsx]:
```suggestion
                // this prevents the radius coming from `fromOLFeature` to override the radius set from an external tool
```

File: web/client/components/map/openlayers/DrawSupport.jsx [hunk 3]
```diff
@@ -175,6 +175,11 @@ class DrawSupport extends React.Component {
...
+                // because it is done starting from the approximated polygon
```
Comment (offtherailz) [inline web/client/components/map/openlayers/DrawSupport.jsx]:
```suggestion
                // this is because `endDrawing` need to impose the radius value, without any re-calculation or approximation
                // but fromOLFeature re-calculates the radius using some distance formula
                // TODO: externalize radius calculation out from `fromOLFeature`
```

File: web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx (hunk 1 above)
Comment (MV88) [reply web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx]: I created this function Because i wanted to write less code  in particular the parts
ReactDOM.render(<COMPONENT {props}/>, document.getElementById("container"));
I could generalize it so we can use it in general and also in other places, but I see that you prefer the older version.
Going to refactor this.
