### PR TITLE
Fix #3842 Switching CRS, circle annotations change size

### LINKED ISSUE #3842: Switching CRS, circle annotations change size
### Description
When switching CRS using the CRS selector, **circle annotations** (if present) change their size.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

Last

*Steps to reproduce*

- Open a map
- Add some layer
- Add a circle annotation
- switch CRS through the CRS selector

*Expected Result*

The circle annotation doesn't change size.

*Current Result*

The circle annotation changes size.

### PR DESCRIPTION
**Pull request by vlt1**
## Description
* Added featureCrs param to transformPolygonToCircle and calculateRadius
for correct radius calculations
* Radius is recalculated on every call to transformPolygonToCircle

## Issues
 - #3842 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#3842

**What is the new behavior?**
In description

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/utils/openlayers/DrawSupportUtils.js [hunk 1]
```diff
@@ -31,7 +34,7 @@ export const transformPolygonToCircle = (feature, mapCrs) => {
         } else {
             center = getCenter(extent);
         }
-        const radius = feature.getProperties().radius || calculateRadius(center, feature.getGeometry().getCoordinates());
```
Comment (MV88) [inline web/client/utils/openlayers/DrawSupportUtils.js]: Hi, why have you removed `feature.getProperties().radius` ?

File: web/client/utils/openlayers/DrawSupportUtils.js [hunk 2]
```diff
@@ -12,12 +12,15 @@ import { reproject } from '../CoordinatesUtils';
...
+    if (isArray(coordinates) && isArray(coordinates[0]) && isArray(coordinates[0][0])) {
+        const point = reproject(coordinates[0][0], featureCrs, mapCrs);
+        return Math.sqrt(Math.pow(center[0] - point.x, 2) + Math.pow(center[1] - point.y, 2));
+    }
+    return 100;
 };
 
-export const transformPolygonToCircle = (feature, mapCrs) => {
-
+export const transformPolygonToCircle = (feature, mapCrs, featureCrs = mapCrs) => {
```
Comment (MV88) [inline web/client/utils/openlayers/DrawSupportUtils.js]: What manual tests have you done related to this change?

For extra security I would check also circle areas in the spatial filter section of QueryPanel

File: web/client/utils/openlayers/DrawSupportUtils.js (hunk 1 above)
Comment (vlt1) [reply web/client/utils/openlayers/DrawSupportUtils.js]: Because when map projection changes that radius value is no longer valid

File: web/client/utils/openlayers/DrawSupportUtils.js (hunk 2 above)
Comment (vlt1) [reply web/client/utils/openlayers/DrawSupportUtils.js]: Not sure what you mean by checking circle areas in the spatial filter section. I could only find Filter Layer option where in the "Region of Interest" you can draw circle areas, but transfromPolygonToCircle is not called there so I don't quite understand how it is relevant to the issue. Could you please elaborate a little further on what you meant? I've tested the changes by adding Circle annotations in different projections then switching the CRS. Circle annotations now don't change their sizes.

Comment (MV88) [reply web/client/utils/openlayers/DrawSupportUtils.js]: Nevermind. While I was thinking to draw functionalities of circles in mapstore it came to my mind the one present in query panel (ROI). 
Since there is another issue https://github.com/geosolutions-it/MapStore2/issues/3922 already opened, you can ignore my previous comment. 
Anyway that issue could be related to your changes (query panel uses drawSupport to start drawing etc) and you can keep this in mind for the future

Comment (MV88) [inline web/client/utils/openlayers/DrawSupportUtils.js]: I know that you just changed the pre-existing code, but can you add some unit tests for the transformPolygonToCircle function as well of some documentation?

**Comment by tdipisa** [comment]
@vlt1 please, can you backport this to the stable branch 2019.02.xx?
