### PR TITLE
Closes #3385 After login on public map you can not save

### LINKED ISSUE #3385: After login on public map you can not save
### Description
If you open an existing map and login, you can not see the "Save" button, only "Save as". This because `mapInfo` are not reloaded. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Open a map
- login as owner or admin
- Open burger menu

*Expected Result*

- I have save button

*Current Result*

- save button is missing (only save as). If you refresh or go back and than open again the map, the save button disappears. 

### Other useful information (optional):
This issue is related to #1993 , probably the same cause ( `mapInfo` not reloaded ).

### PR DESCRIPTION
**Pull request by kappu72**
## Description
Update map permissions after login

## Issues
 - Fix #3385 
 - ...

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [X] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Map permissions aren't updated after login success

**What is the new behavior?**
Map permissions are updated after login

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/__tests__/map-test.js [hunk 1]
```diff
@@ -15,8 +15,10 @@ const {
     zoomToExtent
  } = require('../../actions/map');
 
+const {MAP_INFO_LOAD_START} = require('../../actions/config');
```
Comment (MV88) [inline web/client/epics/__tests__/map-test.js]: i think we have added the mapstore alias

do for new code we can use it
const {MAP_INFO_LOAD_START} = require('@mapstore/actions/config');

can you change that ?
can you do it also for other requires?

File: web/client/plugins/SaveAs.jsx [hunk 2]
```diff
@@ -13,7 +13,6 @@ const {createSelector, createStructuredSelector} = require('reselect');
 const assign = require('object-assign');
 const {Glyphicon} = require('react-bootstrap');
 const Message = require('../components/I18N/Message');
-const {loadMapInfo} = require('../actions/config');
```
Comment (MV88) [inline web/client/plugins/SaveAs.jsx]: this should affect also the component, can you check that?

File: web/client/epics/map.js [hunk 3]
```diff
@@ -16,7 +16,10 @@ const {
     ZOOM_TO_EXTENT,
     changeMapView
 } = require('../actions/map');
-const {mapSelector} = require('../selectors/map');
+const {mapSelector, mapIdSelector} = require('../selectors/map');
```
Comment (MV88) [inline web/client/epics/map.js]: same here @mapstore/  bla bla bla

File: web/client/epics/map.js [hunk 4]
```diff
@@ -178,7 +183,20 @@ const zoomToExtentEpic = (action$, {getState = () => {} }) =>
...
+/**
+ * It checks user's permissions on current map on LOGIN_SUCCESS event
+ * @memberof epics.map
+ * @param {object} action$
+ */
+const checkMapPermissions = (action$, {getState = () => {} }) =>
+        action$.ofType(LOGIN_SUCCESS)
+        .map(() => {
+            const mapId = mapIdSelector(getState());
+            return loadMapInfo(ConfigUtils.getConfigProp("geoStoreUrl") + "extjs/resource/" + mapId, mapId);
```
Comment (offtherailz) [inline web/client/epics/map.js]: Triggering a thunk in an epic do not work as far as I know. `loadMapInfo` is a thunk. 
Are you sure this works?

Comment (kappu72) [reply web/client/epics/map.js]: Since this f1f9a271ebce3c1719ee94ef1fc0d57166f8139f thunkmiddleware is applied before redux-observable and so It's possible to dispatch from an epic. [https://stackoverflow.com/questions/48510274/use-of-redux-thunk-with-redux-observable](url)

Comment (offtherailz) [reply web/client/epics/map.js]: Ok I verified that this issue was present during the first 6 months we used redux-observable, but due to the refactor, this usage is allowed. So I think it can be approved.

**Comment by tdipisa** [comment]
@kappu72 please backport this to the 2019.01.xx branch.
