### PR TITLE
Fix #10246 Issue adding layer when a group is present on TOC

### LINKED ISSUE #10246: Issue adding layer when a group is present on TOC
## Description

When a group exists in the TOC but is not selected, add a layer via the Add Layer button, a new Default group with the added layer appears in the TOC.

https://github.com/geosolutions-it/MapStore2/assets/56537133/1aacfc74-ee6d-49c4-be18-e494c2d1b090

## How to reproduce

-  Open a map
- Create a group on TOC
- Click on Add Layer button 
- Select layer on Catalog

*Expected Result*

The layer is added without any groups

*Current Result*

The added layer is located under a new default group

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR adds a control to add new groups to the Default one when there are not a target parent group

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#10246

**What is the new behavior?**

The new group will be added always to the default one if the parent target is not defined

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

File: web/client/reducers/layers.js [hunk 1]
```diff
@@ -258,17 +258,30 @@ function layers(state = { flat: [] }, action) {
...
     case ADD_GROUP: {
         const id = uuidv1();
+        const defaultGroup = {
+            id: DEFAULT_GROUP_ID,
+            name: DEFAULT_GROUP_ID,
+            title: DEFAULT_GROUP_ID,
+            expanded: true,
+            nodes: []
+        };
+        // ensure neew added group are included in the default
```
Comment (MV88) [inline web/client/reducers/layers.js:268]:
```suggestion
        // ensure new added group are included in the default
```

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
@ElenaGallo please test in DEV

**Comment by ElenaGallo** [comment]
Test passed, @allyoucanmap please backport to 2024.01.xx. Thanks
