### PR TITLE
Fix #4203 Widgets on protected data are not correctly reloaded

### LINKED ISSUE #4203: Widgets on protected data are not correctly reloaded
### Description
If a map contains a protected layer, widgets related to this layer are not correctly reloaded when an user with required rights (as ADMIN) login into MapStore.

states_permissions

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10828) map as anonymus user 
- Login as admin

*Expected Result*

- Widgets are updated according to the user rights

*Current Result*

- Widgets are updated only after a pan in the map

### Other useful information (optional):
To fix this probably the user integration with GeoServer needs to be set

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Added an epic to update widgets layer prop on LAYER_LOAD and various modifications
to ensure correct reloading of widgets.

## Issues
 - #4203 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#4203 

**What is the new behavior?**
Widgets are reloaded correctly

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/widgets/enhancers/dependenciesToFilter.js [hunk 1]
```diff
@@ -29,6 +29,7 @@ module.exports = compose(
             mapSync !== nextProps.mapSync
             || dependencies.viewport !== (nextProps.dependencies && nextProps.dependencies.viewport)
             || geomProp !== nextProps.geomProp
+            || (nextProps.layer && layer.loadingError !== nextProps.layer.loadingError)
```
Comment (offtherailz) [inline web/client/components/widgets/enhancers/dependenciesToFilter.js]: Can you add a test for mapSync change on loadingError change ?

File: web/client/epics/widgets.js [hunk 2]
```diff
@@ -176,5 +176,19 @@ module.exports = {
...
+            }),
+
+    /**
+     * Triggers updates of the layer property of widgets on LAYER_LOAD
+     * @memberof epics.widgets
+     * @param {external:Observable} action$ manages `LAYER_LOAD`
+     * @return {external:Observable}
+     */
+    updateLayerOnLoad: (action$, store) =>
+        action$.ofType(LAYER_LOAD)
```
Comment (offtherailz) [inline web/client/epics/widgets.js]: Layer load is called many times (one for each tile loaded, if I remember well). The only update needed is when error changed. Is there a way to avoid unnecessary actions flood ? 
I think a distinctUntilKeyChanged on error field could to the job. Please add this improvement and test.

Comment (vlt1) [reply web/client/epics/widgets.js]: Sounds like a good idea.

File: web/client/components/widgets/enhancers/dependenciesToFilter.js (hunk 1 above)
Comment (vlt1) [reply web/client/components/widgets/enhancers/dependenciesToFilter.js]: Will do.

File: web/client/epics/widgets.js (hunk 2 above)
Comment (vlt1) [reply web/client/epics/widgets.js]: Actually the update is needed when error property is changed for a particular layerId, so distinctUntilKeyChanged would have to be both on layerId and error fields. Would that be particularly useful?

File: web/client/components/widgets/enhancers/dependenciesToFilter.js (hunk 1 above)
Comment (vlt1) [reply web/client/components/widgets/enhancers/dependenciesToFilter.js]: Wait, I'm not sure what you mean. mapSync change? Why would mapSync change?

Comment (offtherailz) [reply web/client/components/widgets/enhancers/dependenciesToFilter.js]: Sorry I meant dependenciesToFilter

File: web/client/epics/widgets.js (hunk 2 above)
Comment (offtherailz) [reply web/client/epics/widgets.js]: note, i updated the example with take(1) after the first edit

Comment (offtherailz) [reply web/client/epics/widgets.js]: Edited again. What I'm trying to do is to create a stream for each layerid that errored waiting for load (maybe other checks) to trigger once the updateLayertWidget. Did you get my point?

Anyway this is an alternative solution. The problem is to avoid unnecessary widget's update, even if they don't cause, as far as I can see, reloads or other kind of problems.

**Comment by vlt1** [comment]
The update action will be performed anytime LAYER_ERROR or LAYER_LOAD action changes the value of a loadingError(which is every single time they are invoked), because in that case previousLoadingError !== loadingError. Also from the code it is evident , that LAYER_LOAD can both set and clear the error field, just as LAYER_ERROR, so I'm not sure that the last approach you've suggested would work. They also set them in different ways. Good point about switchMap though, I should probably groupBy by layerId and then switchMap on inner observables, as for a particular layer we care only about the latest change.
```javascript
action$.ofType(LAYER_LOAD, LAYER_ERROR)
    .groupBy(({layerId}) => layerId)
    .map(layerStream$ => layerStream$ 
        .switchMap(({layerId}) => {
            const state = store.getState();
            const flatLayer = getLayerFromId(state, layerId);
            return Rx.Observable.of(
                ...(flatLayer && flatLayer.previousLoadingError !== flatLayer.loadingError ?
                    [updateWidgetLayer(flatLayer)] :
                    [])
            );
        })
    ).mergeAll()
```

All in all I think that it is just safer to update widgets when loadingError changes, and it doesn't depend on any particular logic of setting that field. Maybe I'm missing something? I don't know. Sorry :(

**Comment by offtherailz** [comment]
Yes, I checked and the `lastLayerError` goes away as well as you pan. I didn't want to go into the condition when lastLayerError remains "Error" and the other error flag becomes again "Error" so the update is not triggered. 

layer_load

Yes, the solution is not optimal but acceptable. My proposed solution didn't save any other error in the state. 
I'd like to mutate layer objects less as possible, because they are read by many other tools, and their continuous mutation could slow down the whole application. 

Let's discuss it a little.

**Comment by offtherailz** [comment]
From my test seems to work, so please correct the switchMap issue and finalize the PR

**Comment by tdipisa** [comment]
@vlt1 please, can you backport this to the stable branch 2019.02.01?
