### PR TITLE
Fix #3927 Error in console when exporting an empty dashboard chart

### LINKED ISSUE #3927: Dashboard error in console when exporting a chart with no data
### Description
there is an error in console when exporting a chart with no data

the app continues to work though

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard/5728) dashboard as admin
- move the map where no us states are visible
- click on export of the poulation per region chart
image

*Expected Result*

- export of empty widgets does not provoke any error (even if harmless)
- probably the export should be disabled while no data are there (and the "download chart data" tool too)

*Current Result*

in console it appears this

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix the bug reported after merge of 4098, i.e disabled button remain clickable.

## Issues
 - #3927 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3927 

**What is the new behavior?**
No console error

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/widgets/enhancers/tools/__tests__/withMenu-test.js [hunk 1]
```diff
@@ -71,4 +71,23 @@ describe('withMenu enhancer', () => {
         ReactTestUtils.Simulate.click(document.querySelector("#test-menu"));
         expect(spyCallback).toHaveBeenCalled();
     });
+
+    it('Widgets callback should be called when menu disabled', () => {
```
Comment (MV88) [inline web/client/components/widgets/enhancers/tools/__tests__/withMenu-test.js]: should **not** be called

Comment (MV88) [inline web/client/components/widgets/enhancers/tools/__tests__/withMenu-test.js]:
```suggestion
    it('Widgets callback should not be called when menu disabled', () => {
```

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to the stable branch 2019.02.xx?
