### PR TITLE
 Fix #3660 Zoom to Extent on visible area

### LINKED ISSUE #3660: ZoomToExtent should zoom to visible area
### Description
When zoom to a specific extent, if some panel is open, MapStore should take them into account and zoom on the specific area fitting only the visible area. 
Now MapStore fits the entire viewport (full size of the page).

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Zoom To layer extent (TOC, select layer ,zoomButton) or zoom to feature from featuregrid

*Expected Result*

- The map zooms fitting the visible area
image

*Current Result*

- The map fit the whole page, so if you zoomed on a feature, a part of it goes behind current open panels (feature grid, TOC, catalog, featureinfo panel...)
image

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This PR uses OpenLayers and Leaflet (cesium doesn't have support for this) core functionalities to zoom to visible area, instead of fitting to the full screen size map. 
When not supported, the zoom acts as usual. 

## Issues
 - Fix  #3660 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 
**What is the current behavior?** (You can also link to an open issue here)
See #3660 

**What is the new behavior?**
Now, using openlayers or leaflet, the map will zoom to the required extent fitting only the visible area

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

### CODE REVIEW

File: web/client/components/map/cesium/__tests__/Map-test-chrome.jsx [hunk 1]
```diff
@@ -194,5 +193,31 @@ describe('CesiumMap', () => {
...
+            zoom={11}
+            onMapViewChanges={testHandlers.onMapViewChanges}
+        />, document.getElementById("container"));
+        // computing the bounding box for the new center and the new zoom
+        const hook = MapUtils.getHook(MapUtils.ZOOM_TO_EXTENT_HOOK);
+        // update the map with the new center and the new zoom so we can check our computed bouding box
+        expect(hook).toExist();
+
+        hook([10, 10, 20, 20], {crs: "EPSG:4326", duration: 0});
+        // unregister hook
```
Comment (MV88) [inline web/client/components/map/cesium/__tests__/Map-test-chrome.jsx]: you write "unregister hook" but then you call register, it is correct?

File: web/client/components/map/leaflet/__tests__/Map-test.jsx [hunk 2]
```diff
@@ -465,6 +468,67 @@ describe('LeafletMap', () => {
...
+        // center should be the same
+        expect(bounds1.getCenter().lng).toBeGreaterThan(9);
+        expect(bounds1.getCenter().lat).toBeGreaterThan(9);
+        expect(bounds1.getCenter().lng).toBeLessThan(11);
+        expect(bounds1.getCenter().lat).toBeLessThan(11);
+
+        hook([0, 0, 20, 20], {
+            crs: "EPSG:4326",
+            duration: 0,
+            padding: {
```
Comment (MV88) [inline web/client/components/map/leaflet/__tests__/Map-test.jsx]: are these padding values correct? you pan in every direction i.e. zooming ?

File: web/client/components/map/leaflet/__tests__/Map-test.jsx [hunk 3]
```diff
@@ -465,6 +468,67 @@ describe('LeafletMap', () => {
...
+            onMapViewChanges: () => {}
+        };
+        // fix size
+        document.querySelector('#container').setAttribute('style', "width: 200px; height: 200px");
+        const spy = expect.spyOn(testHandlers, 'onMapViewChanges');
+        const map = ReactDOM.render(<LeafletMap
+            id="mymap"
+            center={{ y: 0, x: 0 }}
+            zoom={11}
+            registerHooks
```
Comment (MV88) [inline web/client/components/map/leaflet/__tests__/Map-test.jsx]: register hook is true by default in every maptype, so this should not be needed. is that right?

File: web/client/epics/map.js [hunk 4]
```diff
@@ -71,8 +83,105 @@ const handleCreationLayerError = (action$, store) =>
 const resetMapOnInit = action$ =>
     action$.ofType(INIT_MAP).switchMap(() => Rx.Observable.of(removeAllAdditionalLayers(), resetControls(), clearLayers()));
 
+/**
+ * Convert and normalize the extent into an array `minx,miny,maxx, maxy`
+ * @param {object|array} extent extent object to normalize
+ */
+const toBoundsArray = extent => {
```
Comment (MV88) [inline web/client/epics/map.js]: Should this be moved in CoordinateUtils?

File: web/client/epics/map.js [hunk 5]
```diff
@@ -71,8 +83,105 @@ const handleCreationLayerError = (action$, store) =>
...
+const zoomToExtentEpic = (action$, {getState = () => {} }) =>
+    action$.ofType(ZOOM_TO_EXTENT).switchMap(( action ) => {
+        const extent = toBoundsArray(action.extent);
+        if (!extent) {
+            return Rx.Observable.empty();
+        }
+        const hook = MapUtils.getHook(MapUtils.ZOOM_TO_EXTENT_HOOK);
+        const padding = mapPaddingSelector(getState());
+        if (hook) {
+            // TODO: manage crs
```
Comment (MV88) [inline web/client/epics/map.js]: manage crs?
