### PR TITLE
#3808: custom sheet is not overridden by capabilities in print

### LINKED ISSUE #3808: Sheet name read from printing service overrides user configured one
### Description
If you configure an initial sheet size for printing in localConfig.json this is overridden by the first one found in printing service capabilities document.
We should check if the user-defined sheet size exists in the loaded capabilities, we should use it, and override only if doesn't exist.

*Steps to reproduce*

- Define a custom sheet size in localConfig.json:

```javascript
"initialState": {
      "defaultState": {
        "print": {
          "spec": {
            ...
            "sheet": "A4"
          }
        },
```

- start the app and try to print

*Expected Result*

- the chosen sheet size is selected by default

*Current Result*

- Another sheet size is chosen (A3)

### PR DESCRIPTION
**Pull request by mbarto**
## Description
If you configure an initial sheet size for printing in localConfig.json this is overridden by the first one found in printing service capabilities document.
We should check if the user-defined sheet size exists in the loaded capabilities, we should use it, and override only if doesn't exist.

## Issues
 - Fix #3808

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Default sheet is always the first one in the capabilities document.

**What is the new behavior?**
Default sheet is user custom defined if it exists in the capabilities document,  the first one in the capabilities document otherwise.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/reducers/print.js [hunk 1]
```diff
@@ -19,6 +19,8 @@ const {
     PRINT_CANCEL
 } = require('../actions/print');
 
+const {get} = require('lodash');
+
 const {TOGGLE_CONTROL} = require('../actions/controls');
 const {isObject} = require('lodash');
```
Comment (MV88) [inline web/client/reducers/print.js]: hi, can you move the "get" import here ?
