### PR TITLE
49 great circle annotations

### LINKED ISSUE #2874: Add Great circles in annotations
### Description
great circles change to a line when transformed into an annotation

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Create a distance measure
- Click on add as annotations

*Expected Result*

The great circles are maintained

*Current Result*

The great circles are changed to a polyline

### PR DESCRIPTION
**Pull request by MV88**
## Description
Great circles in measure tool are now maintained when transformed into annotations

## Issues
 - Fix #2874

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
great circles are lost when converted to annotations

**What is the new behavior?**
great circles are NOT lost when converted to annotations

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/leaflet/MeasurementSupport.jsx [hunk 1]
```diff
@@ -52,13 +52,21 @@ class MeasurementSupport extends React.Component {
         this.lastLayer = evt.layer;
 
         let feature = this.lastLayer && this.lastLayer.toGeoJSON() || {};
+        let newFeature = feature;
```
Comment (mbarto) [inline web/client/components/map/leaflet/MeasurementSupport.jsx]: Why don't you reassign feature directly? It's not a constant

File: web/client/components/map/openlayers/MeasurementSupport.jsx [hunk 2]
```diff
@@ -273,6 +273,14 @@ class MeasurementSupport extends React.Component {
         }
         const geojsonFormat = new ol.format.GeoJSON();
         let feature = reprojectGeoJson(geojsonFormat.writeFeatureObject(this.sketchFeature.clone()), this.props.map.getView().getProjection().getCode(), "EPSG:4326");
+        let newFeature = feature;
```
Comment (mbarto) [inline web/client/components/map/openlayers/MeasurementSupport.jsx]: Same here
