### PR TITLE
Fix #2321. Keep circle on change

### LINKED ISSUE #2321: Editing of circle spatial filter details fails
Editing of circle spatial filter details makes the search and the UI not consistent. 

### Steps to reproduce
 - open http://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/1740
 - Open the attribute table
 - Open advanced search
 - Select spatial filter type: circle
 - click on details
 - edit center or radius

#### Expected result 
the circle changes in radius and center

#### Effective result
 - When I edit the center or the radius I see a marker instead of the circle's moving on the map.
 - We I perform the search again I have no result. 
 - When I re-open the circle filter, I see an oval instead of a circle (maybe this is somehow correct, but it can be misleading)

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This pull request fixes 2 kind of issues in Advanced Search circle spatial filter: 
 - When you edit the circle's details the style doesn't change to marker
 - When you save the edited circle, the geometry is valid. 
## Issues
 - Fix #2321

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
In advanced search, when you try to edit the circle's details, a marker appears on the map instead of circle. When save the changes, the geometry is not valid and so the search produces no results.

**What is the new behavior?**
Now you can change the details and the geometry remains a circle. 

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

**Other information**:
The #2222 still exists. So the real geometry used for the filter is not the same of the one drown on the map.

### CODE REVIEW

File: web/client/components/data/query/GeometryDetails.jsx [hunk 1]
```diff
@@ -144,12 +144,20 @@ class GeometryDetails extends React.Component {
                 center.x - this.circle.radius, center.y - this.circle.radius,
                 center.x + this.circle.radius, center.y + this.circle.radius
             ];
-
+            let coordinates = CoordinatesUtils.calculateCircleCoordinates(center, this.circle.radius, 100);
+            if (this.props.geometry && this.props.geometry.projection === "EPSG:4326") {
```
Comment (mbarto) [inline web/client/components/data/query/GeometryDetails.jsx]: Can't we reproject from any projection that is not the current map projection to the current map projection?

Comment (offtherailz) [reply web/client/components/data/query/GeometryDetails.jsx]: I could try, but don't know if it works, because of #2222
