### PR TITLE
#12271: Rules manager - clear cache on standalone geofence and multiple gs instances does not work fully

### LINKED ISSUE #12271: Rules manager - clear cache on standalone geofence and multiple gs instances does not work fully
## Description

Currently MS is invoking a wrong base URL for invalidating the GF cache:
`https://host/MapStore2/rest/geofence/ruleCache/invalidate`

It should be something like as the cache rule is on the GS side:
`https://host/geoserver/rest/geofence/ruleCache/invalidate`

Rulemanager and the api code here are not considering multiple instances

https://github.com/geosolutions-it/MapStore2/blob/de55770d13eb703b5b6cfe31ae55f38fea0b9fcf/web/client/api/geoserver/GeoFence.js#L180-L192

Image

the migration guideline is good

in case of multiple instances the baseUrl here is undefined ending up in the error above
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/geoserver/GeoFence.js#L191

**ACs**

When clicking clear cache we:

- [ ] list in a menu item all instance names
  - [ ] clicking on an instance will open the modal
  - [ ] the modal will tell which instance you are clearing cache
  - [ ] click on confirm will delete cache on that instance only
- [ ] EXTRA add a voice in menu list that is called "clear all"
 - [ ] when clicked it will open the modal
 - [ ] it will show a message that will state "Do you want to clear cache of all geoserver instances?
 - [ ] if confirm an invalidate must be sent with correct url (/MapStore2 is not present)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### PR DESCRIPTION
**Pull request by mahmoudadel54**
## Description

This PR handles the ability to clear the cache for individual GeoServer instances or all instances simultaneously from the Rules Manager toolbar. This is specifically designed for **standalone GeoFence** deployments where multiple GeoServer instances are managed.

**Changes**

**UI/UX:**

- Replaced the direct "Clear Cache" modal with a dropdown menu (GSClearCacheMenu) that lists all available GeoServer instances.
- Added a "Clear For All Instances" option at the bottom of the menu.

image

**Actions & Epics:**
- Created onCacheCleanMulti action to handle bulk requests.
- Updated Epics to perform parallel cache invalidation using Rx.Observable.forkJoin.
- Error Handling: Improved feedback by aggregating successes and failures into separate notifications, listing the specific names of instances that failed.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#12271 

**What is the new behavior?**

https://github.com/user-attachments/assets/a99cc128-40ea-43cb-a5d7-ab4a415b33dd

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/api/geofence/__tests__/RuleService-test.js [hunk 1]
```diff
@@ -161,4 +162,46 @@ describe('RuleService API for GeoFence StandAlone', () => {
...
+
+        RuleService.cleanCache().then((data) => {
+            expect(data).toEqual(mockData);
+            done();
+        }).catch(done); // Ensure errors fail the test
+    });
+    it('cleanCache with gs instance [stand-alone geofence]', (done) => {
+        const mockData = { status: "success" };
+        mockAxios.onGet().reply(config => {
+            expect(config.url).toBe('rest/geofence/ruleCache/invalidate');
```
Comment (MV88) [inline web/client/api/geofence/__tests__/RuleService-test.js]: are you sure about this test?

like it is even triggered?

if you put this it fails?
expect(true).toBe(false);

please check better if these tests are really testing what we need

same for others

File: web/client/api/geofence/__tests__/RuleService-test.js [hunk 2]
```diff
@@ -161,4 +162,46 @@ describe('RuleService API for GeoFence StandAlone', () => {
...
+        RuleService.cleanCache("http://localhost:8080/geoserver").then((data) => {
+            expect(data).toEqual(mockData);
+            done();
+        }).catch(done); // Ensure errors fail the test
+    });
+    it('cleanCacheGSInstance', (done) => {
+        const gsUrl = 'http://localhost:8080/gs-instance.com';
+        const mockData = { status: "invalidated" };
+
+        mockAxios.onGet().reply(config => {
```
Comment (MV88) [inline web/client/api/geofence/__tests__/RuleService-test.js]: doing onGet() this way makes the test pointless i think because it will not validate the url and this is crucial

try to spend a little more time here do understand if these tests are well written or are false positives

File: web/client/api/geofence/RuleService.js [hunk 3]
```diff
@@ -108,6 +108,12 @@ const processFilterValues = (rulesFiltersValues) => {
  * @param {function} config.getGeoServerInstance function that returns the instance object `{id: 1, url: "some-url"}`
  */
 const Api = ({addBaseUrl, addBaseUrlGS, getGeoServerInstance}) => ({
+    cleanCacheGSInstance: (gsInstanceURL) => {
```
Comment (MV88) [inline web/client/api/geofence/RuleService.js]: couldn't you expand cleanCache method ?

File: web/client/api/geoserver/GeoFence.js [hunk 4]
```diff
@@ -77,7 +77,11 @@ const GS_INSTANCES_SERVICES = {
  */
 var Api = {
     // RULES
-    cleanCache: () => {
+    cleanCache: (gsUrl) => {
```
Comment (MV88) [inline web/client/api/geoserver/GeoFence.js:80]: same as https://github.com/geosolutions-it/MapStore2/pull/12279/changes#r3122595375

File: web/client/epics/rulesmanager.js [hunk 5]
```diff
@@ -43,14 +43,59 @@ export default {
...
+            return cleanCache(action?.gsInstanceUrl)
                 .mapTo(success({title: "rulesmanager.errorTitle", message: "rulesmanager.cacheCleaned"}))
                 .startWith(setLoading(true))
                 .catch(() => {
                     return Rx.Observable.of(error({title: "rulesmanager.errorTitle", message: "rulesmanager.errorCleaningCache"}));
                 })
-                .concat(Rx.Observable.of(setLoading(false)))),
+                .concat(Rx.Observable.of(setLoading(false)));
+        }),
+    onCacheCleanMulti: action$ => action$.ofType(CACHE_CLEAN_MULTI)
```
Comment (MV88) [inline web/client/epics/rulesmanager.js:55]: good job here

File: web/client/plugins/manager/GSCleanCacheMenu.jsx [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+    );
+};
+GSCleanCacheMenu.propTypes = {
+    gsInstances: PropTypes.array,
+    onSelectInstance: PropTypes.func,
+    onSelectAll: PropTypes.func,
+    show: PropTypes.bool,
+    onClose: PropTypes.func,
+    storeGSInstancesDDList: PropTypes.func,
+    onError: PropTypes.func
```
Comment (MV88) [inline web/client/plugins/manager/GSCleanCacheMenu.jsx]: sorted is better
```suggestion
    gsInstances: PropTypes.array,
    show: PropTypes.bool,
    storeGSInstancesDDList: PropTypes.func,
    onClose: PropTypes.func,
    onError: PropTypes.func,
    onSelectAll: PropTypes.func,
    onSelectInstance: PropTypes.func
```

File: web/client/plugins/manager/RulesToolbar.jsx [hunk 7]
```diff
@@ -103,23 +141,36 @@ const EditorToolbar = compose(
         {
             glyph: 'plus',
             tooltipId: 'rulesmanager.tooltip.addGSInstance',
-            visible: showAddGSInstance && activeGrid === 'gsInstances',
+            visible: showAddGSInstance && activeGrid === 'gsInstances' && isStandAloneGeofence,
```
Comment (MV88) [inline web/client/plugins/manager/RulesToolbar.jsx]: why editing plus pencil and trash visible attributes?

i understand you created a duplicated clear-brush for the standalone, but
make it closer to the other maybe

**Review by MV88 — CHANGES_REQUESTED** [review]
a few points to be checked

**Review by MV88 — APPROVED** [review]

**Comment by offtherailz** [comment]
Successfully created backport PR for `2026.01.xx`:
- #12285
