### PR TITLE
Fix #10295 fixed measure tool rendering in map

### LINKED ISSUE #10295: Incorrect UI when the Search by coordinates bar and Measurement tool are opened at the same time
## Description

When the Search by coordinates bar (DECIMAL and AERONAUTICAL) and the Measurement tool are open at the same time, one tool covers the other.

coordinate

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
* avoiding being covered by search tool and widgets
* both 2d and 3d
* done similarly as in annotationsEditor using portals
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10295

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/plugins/Measure.jsx [hunk 1]
```diff
@@ -163,14 +164,24 @@ const Measure = connect(
...
+        mapType,
+        coordsAeronauticalEnabled
     }))
-)((props) => {
-    return props.mapType === MapLibraries.CESIUM
-        ? null
-        : <Measure {...props} />;
+)(({coordsAeronauticalEnabled, ...props}) => {
+    return (
+        <div className={`measure-container${coordsAeronauticalEnabled ? " bottom-offset" : ""}`}>
```
Comment (allyoucanmap) [inline web/client/plugins/Measure.jsx:178]: Probably it's better top-offset from the point of view of the measure toolbar.
Another possibility is to use directly inline style

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev and let us know if we can backport, thanks
