### PR TITLE
Fix #4182 Remove all annotations geometry fail without initial state

### LINKED ISSUE #4182: 'Remove all annotations geometry' doesn't work properly without setting initial state
### Description
Without setting the initial state:

         "annotations": {
          "config": {
            "multiGeometry": true,
            "validationErrors": {}
          },
          "format": "decimal",
          "defaultTextAnnotation": "New"
        },

When I create a new annotation geometry and I save it, the buttom 'Remove all annotations geometry' doesn't remove the annotation immediatly. The annotation is only removed after clicking on 'back' and 'confirm'

Anno

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- localConfig.json should contain "Annotations" plugin, with no annotations initialState set.
- Open Mapstore
- Open a random map
- Open Burger Menu
- Click on 'Annotations'
- Click on 'New'
- Click on 'Add New Geometry'
- Click on 'Marker'
- Click on the map
- Click on 'Save'
- Click on 'Remove all annotations geometry'
- Click on ' Confirm'

*Expected Result*

- The geometry shouldn't be displayed

*Current Result*

- The geometry is still displayed

### Other useful information (optional):
See #3852

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix failure to remove annotation geometry when annotation initial state is not set

## Issue
 - #4182 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #4182 

**What is the new behavior?**
Remove all annotations works regardless of the initial state

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/annotations.js [hunk 1]
```diff
@@ -238,7 +238,7 @@ module.exports = (viewer) => ({
                 const feature = state.annotations.editing;
                 const drawing = state.annotations.drawing;
                 const type = state.annotations.featureType;
-                const multiGeom = state.annotations.config.multiGeometry;
+                const multiGeom = get(state, 'annotations.config.multiGeometry');
```
Comment (MV88) [inline web/client/epics/annotations.js]: Hi, please use a selector here (create it and test if necessary), since it not the first time you have to do this fix

Also, please check if this fix is needed in other epics

File: web/client/selectors/__tests__/annotations-test.js [hunk 2]
```diff
@@ -433,6 +434,10 @@ describe('Test annotations selectors', () => {
         const retVal = removingSelector(state);
         expect(retVal).toBe(null);
     });
+    it('test multiGeometrySelector', () => {
+        const multiGeometry = multiGeometrySelector(state);
+        expect(multiGeometry).toBeTruthy();
```
Comment (MV88) [inline web/client/selectors/__tests__/annotations-test.js]: please test default behaviour

File: web/client/selectors/annotations.js [hunk 3]
```diff
@@ -18,6 +18,7 @@ const annotationsLayerSelector = createSelector([
     ], (layers) => head(layers.filter(l => l.id === 'annotations'))
 );
 
+const multiGeometrySelector = (state) => get(state, 'annotations.config.multiGeometry');
```
Comment (MV88) [inline web/client/selectors/annotations.js]:
```suggestion
const multiGeometrySelector = (state) => get(state, 'annotations.config.multiGeometry', false);
```

File: web/client/selectors/__tests__/annotations-test.js (hunk 2 above)
Comment (MV88) [inline web/client/selectors/__tests__/annotations-test.js]:
```suggestion
        expect(multiGeometry).toBe(true);
```

Comment (kasongoyo) [reply web/client/selectors/__tests__/annotations-test.js]: Sorry, What's the default behaviour in this context? @MV88

Comment (MV88) [reply web/client/selectors/__tests__/annotations-test.js]: multiGeometry to be true

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to the stable branch 2019.02.xx?
