### PR TITLE
Fixes #2600 Wrong data id for details panel

### LINKED ISSUE #2600: Wrong data id for details panel
### Description
Current getIdFromUri function get the first digit and if the url contains number before data id the request fails

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v.63

*Steps to reproduce*

- Need geostore configuration with "/geoStoreUrl": "mapstore2/rest/geostore/",
- create a map details 
- close map details
- open map details 

*Expected Result*

- correct details in modal

*Current Result*

- no available details message

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
A few sentences describing the overall goals of the pull request' s commits.

## Issues
 - Fix #2600

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
issue #2600 

**What is the new behavior?**
details are visible with different geostore path

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/epics/maps.js [hunk 1]
```diff
@@ -249,5 +283,6 @@ module.exports = {
     deleteMapAndAssociatedResourcesEpic,
     setDetailsChangedEpic,
     fetchDetailsFromResourceEpic,
-    saveResourceDetailsEpic
+    saveResourceDetailsEpic,
+    getIdFromUri
```
Comment (offtherailz) [inline web/client/epics/maps.js]: The epic file should export only epics... Can you test it inside the epic?
