### PR TITLE
Fix #2746 leaflet drawing of linestring

### LINKED ISSUE #2746: Measure tool conflicts with other draw tool with leaflet
### Description
there is an error when you try to edit a layer with LineString (Linea_costa)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome 65.0.3325.162 
- [x] Firefox 59
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open a map
- login as admin
- load Linea_costa
- open the feature grid 
- add new feature
- start drawing

*Expected Result*
 you can draw a line

*Current Result*
you cant

### PR DESCRIPTION
**Pull request by MV88**
## Description
This PR fixes a problem when editing a layer made of LineString features (Linea_costa)

## Issues
 - Fix #2746

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/leaflet/MeasurementSupport.jsx [hunk 1]
```diff
@@ -55,6 +55,9 @@ L.getMeasureWithTreshold = (value, threshold, source, dest, precision, sourceLab
 */
 
 L.GeometryUtil.readableDistance = (distance, isMetric, isFeet, isNauticalMile, precision, options) => {
+    if (options === null) {
```
Comment (mbarto) [inline web/client/components/map/leaflet/MeasurementSupport.jsx]: This way, you are still breaking things.
You should mantain non-overridden behaviour by default. I think the best way is to provide a default for options that triggers the old behaviour.

File: web/client/components/map/leaflet/MeasurementSupport.jsx [hunk 2]
```diff
@@ -80,6 +83,9 @@ L.GeometryUtil.readableDistance = (distance, isMetric, isFeet, isNauticalMile, p
  supporting also the square nautical miles and square feets
  */
 L.GeometryUtil.readableArea = (area, isMetric, precision, options) => {
+    if (options === null) {
```
Comment (mbarto) [inline web/client/components/map/leaflet/MeasurementSupport.jsx]: Same as above
