### PR TITLE
Fix #2534 IE11 load problem (RELEASE 2017.06.00)

### LINKED ISSUE #2534: Cannot load map on IE11
### Description
The background of the map is white and it goes in infinite loading

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
image

*Steps to reproduce*
- use ie11
- Open [dev](https://dev.mapstore2.geo-solutions.it/mapstore/#/) env
- Try to open a map

*Expected Result*
map loads correctly

*Current Result*
Map doesn't load the background or any layer
an infinite loading appears in the middle
tools are not usable/working

### PR DESCRIPTION
**Pull request by MV88**
## Description
We used a method not supported for IE11

## Issues
 - Fix #2534

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#2534 

**What is the new behavior?**
maps loads correctly, and toc filters layes name correctly

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/plugins/TOC.jsx [hunk 1]
```diff
@@ -61,7 +61,8 @@ const addFilteredAttributesGroups = (nodes, filters) => {
 const filterLayersByTitle = (layer, filterText, currentLocale) => {
     const translation = isObject(layer.title) ? layer.title[currentLocale] || layer.title.default : layer.title;
     const title = translation || layer.name;
-    return title.toLowerCase().includes(filterText.toLowerCase());
+    const testRegex = new RegExp(filterText.toLowerCase());
```
Comment (mbarto) [inline web/client/plugins/TOC.jsx]: Same as above
