### PR TITLE
Fix #3928 widget builder color selector box shows wrong labels

### LINKED ISSUE #3928: When configuring the widget data, the 'Color' combo box shows wrong labels
### Description
When creating new (chart) widgets, the 'Color' ('Color Ramp' in case of Pie Chart) combo box of the 'Configure data' panel shows wrong labels (see the picture).

Menu_002

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map with vector layers
- open the TOC and select a vector layer
- click on 'Create widget for the selected layer'
- choose Chart widgets >> Bar/Line/Pie Chart
- see the 'Color'/'Color Ramp' combo box values

*Expected Result*

- The combo box shows readable values

*Current Result*

- The combo box shows values like this `global.colors.global.colors.blue`

### Other useful information (optional):

Thematic layers should be tested also.

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
This PR correct the widget builder color combobox option labels to proper values so that they have meaning to user. see #3928 

## Issues
 - #3928 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [x] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#3928 

**What is the new behavior?**
The widget builder color selector box shows colors properly

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by MV88** [comment]
hi @kasongoyo, I would like to leave you some points/suggestion on how to create a pr in general.
I feel that this can help you to align our conventions 😄 

- provide a quick recap on what the pr does in the description paragraph (sometimes you can write see title)
- do not write fix #number_issue but only the #number_issue in the Issues paragraph (not above)
- do not check tests if the pr does not contain any tests
- when possible add documentation (not this case)
- when pr are bigger suggest in the "Other information" pagragraph the most important point of the pr by providing some link (not this case)
- connect the issue with zenhub 
image


Thanks

File: web/client/components/style/EqualIntervalComponents/__tests__/ColorRampItem-test.jsx [hunk 1]
```diff
@@ -0,0 +1,44 @@
+const React = require('react');
```
Comment (MV88) [inline web/client/components/style/EqualIntervalComponents/__tests__/ColorRampItem-test.jsx]: tests are fine, 
please, add copyright section with current year (in every new file)

File: web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx [hunk 2]
```diff
@@ -1,23 +1,24 @@
...
-                {ramp.map(cell => <div className="color-cell" key={this.props.item && this.props.item.name + "-" + cell} style={{backgroundColor: cell}}/>)}
-                <div className="colorname-cell">
-                    {this.props.item && this.props.item.name
-                        ? <Message msgId={`global.colors.${this.props.item.name}`} msgParams={{number: ramp.length}} />
-                    : this.props.item && this.props.item.name}
-                </div>
-                </div>);
-    }
-}
+const ColorRampItem = ({ item }) => {
```
Comment (MV88) [inline web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx]: A curiosity.
What's the motivation for switching from class to functional component ?

Comment (kasongoyo) [reply web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx]: The component is dump, and pure. I think mapstore dev guide encourage to make component functional/stateless when possible and otherwise when it is real needed.

Comment (MV88) [reply web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx]: Yeah, that's fine

File: web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx [hunk 3]
```diff
@@ -1,23 +1,36 @@
...
+ * @description Simple component to display color label
+ */
+const ColorRampItem = ({ item }) => {
+    let ramp = item && (item.ramp || colors[item.name] && colors[item.name][5]) || [];
+    return (
+        <div className="color-ramp-item">
+            {ramp.map(cell => <div className="color-cell" key={item && item.name + "-" + cell} style={{ backgroundColor: cell }} />)}
+            <div className="colorname-cell">
+                {item && item.name
+                    ? <Message msgId={item.name.includes('global.colors') ? item.name : `global.colors.${item.name}`} msgParams={{ number: ramp.length }} />
```
Comment (offtherailz) [inline web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx]: I think this switch makes the component less generic. This way I can not customize labels for colors (that was the original way the component worked). If name of the layer is not in the global colors, you will always have an unreadable label, no way to customize it. 

Is it possible instead to add global.colors outside, when the original issue was happening, and remove the global.colors string concatenation (that should be the correct way to do the fix in https://github.com/geosolutions-it/MapStore2/pull/3900) ?

Comment (kasongoyo) [reply web/client/components/style/EqualIntervalComponents/ColorRampItem.jsx]: Noted. Will push the update shortly @offtherailz
