### PR TITLE
Fix #10805 JAXBException while updating an existing dashboard

### LINKED ISSUE #10805: JAXBException while updating an existing dashboard
## Description

There is an error while trying to update an existing 

Request to update an existing dashboard:
```
curl 'https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/resources/resource/21694' \
  -X 'PUT' \
  --data-raw $'<Resource><description><\u0021[CDATA[Filtering Capabilities]]></description><metadata></metadata><name><\u0021[CDATA[3 - Demo Dashboard]]></name><advertised>true</advertised><Attributes><attribute><name>detailsSettings</name><value>{"showAsModal":false,"showAtStartup":false}</value><type>STRING</type></attribute><attribute><name>details</name><value>rest/geostore/data/47320</value><type>STRING</type></attribute><attribute><name>featured</name><value>true</value><type>STRING</type></attribute><attribute><name>thumbnail</name><value>rest/geostore/data/21716/raw?decode=datauri&v=c363c6a0-990e-11eb-ba73-0fc9473ccf1f</value><type>STRING</type></attribute></Attributes></Resource>'
```

400 Error:
```
JAXBException occurred : Unexpected character '=' (code 61); expected a semi-colon after the reference for entity 'v'
 at [row,col {unknown-source}]: [1,573]. 
```

## How to reproduce

- login as admin
- open this [dashboard](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694)
- open the resource metadata details
- edit tags
- save

*Expected Result*

The save process completes without errors

*Current Result*

There is a 400 Error on the backend

Image

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

found in this review https://github.com/geosolutions-it/MapStore2/pull/10796#pullrequestreview-2606699815

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR review the payload for resources PUT request making sure the attribute value can support special chars.
As found here https://github.com/geosolutions-it/MapStore2/issues/10805#issuecomment-2650733366 the problem was related to the `&` char inside the thumbnail url in previous version of MS this was not happening because the request workflow was using other api functions.
There is also a fix related to the detailsSettings parameter not correctly parsed by the resources catalog api

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#10805

**What is the new behavior?**

It is possible to save resources with attributes with special chars

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

File: web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js [hunk 1]
```diff
@@ -104,7 +105,7 @@ export const computePendingChanges = (initialResource, resource, resourceData) =
     ];
     const categoryOptions = {
         'thumbnail': {
-            tail: '/raw?decode=datauri',
+            tail: `/raw?decode=datauri&v=${uuid()}`,
```
Comment (offtherailz) [inline web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js:108]: Why here using uuid? a sort of cache?
If so, let's specify in a comment the reason.

Comment (offtherailz) [inline web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js:108]:
```suggestion
            // this forces the reload the thumbnail image when updated
            tail: `/raw?decode=datauri&v=${uuid()}`,
```
