### PR TITLE
Fix #4195 Layer opacity issue for imported SHPs

### LINKED ISSUE #4195: Layer opacity issue for imported SHPs
### Description
If a SHP is imported into MapStore, you can change the layer's opacity as usual but if you save the map and then reload it the opacity isn't maintained.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open a map 
- Import a SHP (like the [one attached](https://github.com/geosolutions-it/MapStore2/files/3610419/Ciclabili.BZ.zip))
- Open the TOC
- Change the opacity of the imported layer
- Save the map 
- Reload the map

*Expected Result*

- The opacity of the SHP layer is maintained according to the previous modification

*Current Result*

- The layer's opacity state is maintained in the TOC but not in the map

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Maintain vector layer opacity on map refresh/initial loading

## Issues
 - #4195 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #4195 

**What is the new behavior?**
layer opacity is maintained on map refresh

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/leaflet/plugins/VectorLayer.jsx [hunk 1]
```diff
@@ -40,16 +40,28 @@ var createVectorLayer = function(options) {
         style: options.nativeStyle || options.style || defaultStyle // TODO ol nativeStyle should not be taken from the store
     });
     layer.setOpacity = (opacity) => {
-        const style = assign({}, layer.options.style || defaultStyle, {opacity: opacity, fillOpacity: opacity});
+        const style = assign({}, layer.options.style || defaultStyle, { opacity: opacity, fillOpacity: opacity });
         layer.setStyle(style);
         setOpacity(layer, opacity);
     };
+    layer.on('layeradd', () => {
+        layer.setOpacity(layer.opacity || options.opacity);
```
Comment (offtherailz) [inline web/client/components/map/leaflet/plugins/VectorLayer.jsx]: opacity is a number, so it can be 0. Please make it work also for 0 value, and provide a test for this.

File: web/client/components/map/leaflet/plugins/VectorLayer.jsx [hunk 2]
```diff
@@ -40,16 +40,28 @@ var createVectorLayer = function(options) {
...
     return layer;
 };
 
 Layers.registerType('vector', {
     create: (options) => {
-        return createVectorLayer(options);
+        const layer = createVectorLayer(options);
+        // layer.opacity will store the opacity value
+        // to be applied to layer style once the layer is ready
+        layer.opacity = options.opacity || 1.0;
```
Comment (offtherailz) [inline web/client/components/map/leaflet/plugins/VectorLayer.jsx]: Same as above, 0 can be a value and in this case opacity will become 1. Please make check it works for 0 value.

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to the stable branch 2019.02.xx?
