### PR TITLE
Fix #3696 Various fixes, utils and drawSupport

### LINKED ISSUE #3696: Various problems and improvements (warnings in console, draw marker, getGeoJSONExtent bug)
### Description
This issue lists some errors discovered in mapstore 2
 - there is an error here [getGeoJSONExtent](https://github.com/geosolutions-it/MapStore2/blob/cfd7417063ecf2a0967394514267aabb148eae47/web/client/utils/CoordinatesUtils.js#L508)
- some compoments misses the key prop when rendering items
- drawStatus "start" does not allow to draw a marker with a custom style

### In case of Bug (otherwise remove this paragraph)

*Browser Version Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Steps to reproduce*

- this errors are not reproducible

*Expected Result*

- you can draw markers "progammatically"
- you do not see many warnings in console (for developers)
- getGeoJSONExtent fixed problem 
*Current Result*

- Describe here the current behavior

### PR DESCRIPTION
**Pull request by MV88**
## Description
this pr provides fixes in CoordinateUtils, MapUtils, and it removes various warnings from console

## Issues
 - Fix #3696

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see issue

**What is the new behavior?**
you can draw marker from "start" drawStatus, and "Marker" DrawMethod
getGeoJSONExtent works with simple Feature

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
can cause conflicts with Annotations branch

### CODE REVIEW

File: web/client/plugins/Map.jsx [hunk 1]
```diff
@@ -281,7 +282,7 @@ class MapPlugin extends React.Component {
         const projection = this.props.map.projection || 'EPSG:3857';
         return [...this.props.layers, ...this.props.additionalLayers].filter(this.filterLayer).map((layer, index) => {
             return (
-                <plugins.Layer type={layer.type} srs={projection} position={index} key={layer.id || layer.name} options={layer} securityToken={this.props.securityToken}>
+                <plugins.Layer type={layer.type} srs={projection} position={index} key={layer.id || layer.name || uuidv1()} options={layer} securityToken={this.props.securityToken}>
```
Comment (mbarto) [inline web/client/plugins/Map.jsx]: What the use case for a layer without both id and name? Do you have an example?

Comment (MV88) [reply web/client/plugins/Map.jsx]: when you use a vector layer in the additionalLayers list

Comment (offtherailz) [reply web/client/plugins/Map.jsx]: I suggest to add unique id to every additional layer you create it.  I suggest to assign one on creation. If missing, please use a default one in reducer, @mbarto do you agree?

Comment (MV88) [reply web/client/plugins/Map.jsx]: @offtherailz i'm just passing a random value if it does not exist to the **key** prop to avoid have a warning in the console

Comment (offtherailz) [reply web/client/plugins/Map.jsx]: The warning, in that case, is correct. If some layer has id or name missing, probably you're doing something wrong, and it is better to be notified of this.
