### PR TITLE
Fix #3523 Fix #3548 Fix problems with coordinate editor for the search and GFI tools

### LINKED ISSUE #3523: Address and coordinate search
### Description
We would like to add to the search bar in the viewer the possibility to zoom to a specific point and place a marker in that point that will be the center of the map.
There will be two possible formats: aeronautical or decimal.

This button in the search toolbar will be disabled on mobile, showing only the search for addresses

by changing the config you can:
- hide this tool (active by default only in map viewer)
- change default zoom level (default 12)
- select the search tool active (default adddres)

### LINKED ISSUE #3548: GFI via coordinate input
### Description
Add the possibility to use a coordinate editor for the GFI tool.
With all coordinate valid using Enter from keyboard will perform the GFI search.

We will also add two flags:
* enabledCoordEditorButton set to true by default
* showCoordEditor set to false by default

### PR DESCRIPTION
**Pull request by MV88**
## Description
Fix the problems with coordinate editor with search and GFI tool

* also fix some problem with loading and displaying annotations with leaflet
* especially with text and the multiple draw of same ft.
* also updated limit stroek width for symbols

A few sentences describing the overall goals of the pull request' s commits.

## Issues
- Fix #3523
- Fix #3548

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
some editing problems with aeronautical and GFI panel and search tool
in search tool if you enter a valida aeronautical value then try to cancel the minutes and then click on clear X the inputs were not disabled correctly.

**What is the new behavior?**
- you can edit correctly aeronautical coord in GFI panel
- you can reset the aeronautical coord editor for 
- you can load correct font and colors for text annotation in leaflet
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/leaflet/Feature.jsx [hunk 1]
```diff
@@ -87,6 +90,10 @@ class Feature extends React.Component {
         }
     }
     addLayer(props, styles) {
+        /* it was not removing correctly the layer and it was adding to the
```
Comment (offtherailz) [inline web/client/components/map/leaflet/Feature.jsx]:
```suggestion
        /* remove the current layer
```

File: web/client/components/map/leaflet/Feature.jsx [hunk 2]
```diff
@@ -87,6 +90,10 @@ class Feature extends React.Component {
...
+        * map more feature causing the fillOpacity to be summed up
```
Comment (offtherailz) [inline web/client/components/map/leaflet/Feature.jsx]:
```suggestion
        * to avoid multiple features to overlap
```
