### PR TITLE
Fix #6025 Error page selecting "Display Legend" adding chart widget

### LINKED ISSUE #6025: Error page selecting "Display Legend" adding chart widget
## Description
Redirect the user to an error page when selecting "Display Legend" during the configuration of a new pie chart widget 

## How to reproduce

1. Install MapStore according to https://mapstore.readthedocs.io/en/latest/quick-start/ and release https://github.com/geosolutions-it/MapStore2/releases/tag/v2020.02.01
1. Login to home page (my local address: http://localhost:8082/mapstore/#/ ) 
1. Select new Dashboard 
image
1. _Add a widget to the dashboard_ 
image
1. Widget type: chart
1. Add layer 
image
1. Chart type: Pie Chart
1. Configure as follow:
image
1. Click on "Display Legend icon"

*Expected Result*

*Current Result*
Error page: 
image

- [] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| 86 |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Local OS: Windows 10 Home v. 2004

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Charts now handle objects as values in wps responses.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#6025 

**What is the current behavior?**

#6025 

**What is the new behavior?**
MapStore doesn't crash and correctly displays chart data.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/widgets/enhancers/wpsChart.js [hunk 1]
```diff
@@ -6,12 +6,26 @@
...
-    AggregationResults.map( (res) => ({
-        ...GroupByAttributes.reduce( (a, p, i) => ({...a, [p]: res[i]}), {}),
+    AggregationResults.map((res) => ({
+        ...GroupByAttributes.reduce((a, p, i) => {
+            let value = res[i];
+            if (isObject(value)) {
+                if (value.time) {
+                    value = (new Date(value.time)).toISOString();
+                } else {
+                    value = JSON.stringify(value.time);
```
Comment (offtherailz) [inline web/client/components/widgets/enhancers/wpsChart.js:21]: sorry, maybe here you should throw the error, so the error is shown on chart. 
My TODO in the comment didn't make sense. For instance here the format of the server is not expected

**Review by offtherailz — CHANGES_REQUESTED** [review]

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
Please @vlt1   backport to 2020.02.xx
