### PR TITLE
Fixed #1634 added support to custom search services and minor fixes

### LINKED ISSUE #1634: Extend the search plugin for supporting custom services
The search plugin now supports only search, via configuration, of wfs and nominatim services.
It should allow also the registration of 3rd party services. These services can require additional interactions to retrive geometry, so we should also implement support to some geometry service as well as the search services

### PR DESCRIPTION
**Pull request by MV88**
Added also the support for geomService.
Fixed minor things.

### CODE REVIEW

File: web/client/api/searchText.js [hunk 1]
```diff
@@ -9,40 +9,91 @@ const WFS = require('./WFS');
...
-                }, params))
+                maxFeatures: 10,
+                typeName,
+                outputFormat,
+                // create a filter like : `(ATTR ilike  '%word1%') AND (ATTR ilike '%word2%')`
+                cql_filter: filter
+            }, params))
             .then( response => response.features );
+    },
+    bzVie: (searchText, {pathname, lang}) => {
```
Comment (offtherailz) [inline web/client/api/searchText.js]: This is a custom service. Please remove it from pull request

File: web/client/api/searchText.js [hunk 2]
```diff
@@ -9,40 +9,91 @@ const WFS = require('./WFS');
...
+                            "code": item.codice,
+                            "desc": item.descrizione
+                        }
+                    };
+                });
+            }
+            return [];
+        });
+    },
+    bzCivico: (searchText, {pathname, item}) => {
```
Comment (offtherailz) [inline web/client/api/searchText.js]: remove this too

File: web/client/epics/search.js [hunk 3]
```diff
@@ -44,21 +43,26 @@ const searchEpic = action$ =>
...
+                        }
+                        return count + 1;
+                    }, 0))
+                ) // map
+            ) // from
             // merge all results from the streams
             .mergeAll()
             .scan( (oldRes, newRes) => [...oldRes, ...newRes].sort( (a, b) => get(b, "__PRIORITY__") - get(a, "__PRIORITY__") ) .slice(0, 15))
-            .map((results) => searchResultLoaded(results, false, services))
+            .map((results) => searchResultLoaded(results, false, API.Services))
```
Comment (offtherailz) [inline web/client/epics/search.js]: probably API.Services is not needed

File: web/client/epics/search.js [hunk 4]
```diff
@@ -44,21 +43,26 @@ const searchEpic = action$ =>
...
-            ))
+            Rx.Observable.from(
+                (action.services || [ {type: "nominatim"} ])
+                 // Create an stream for each Service
+                .map(
+                    (service) => Rx.Observable.defer(() => API.Utils.getService(service.type)(action.searchText, service.options)
+                    .then(
+                        (response= []) => response.map(result => ({...result, __SERVICE__: service, __PRIORITY__: service.priority || 0}))
+                    ))
+                    .retryWhen(errors => errors.delay(200).scan((count, err) => {
```
Comment (offtherailz) [inline web/client/epics/search.js]: indent back, retryWhen is applied to the Observable, not to the service's promise

File: web/client/epics/search.js [hunk 5]
```diff
@@ -78,42 +82,50 @@ const searchEpic = action$ =>
  * @memberof epics.search
  * @return {Observable}
  */
+
 const searchItemSelected = action$ =>
     action$.ofType(TEXT_SEARCH_ITEM_SELECTED)
     .switchMap(action => {
-        const item = action.item;
+        let itemSelectionStream = Rx.Observable.of(action.item)
+            // retrieve geometry from geomService or pass the item directly
```
Comment (offtherailz) [inline web/client/epics/search.js]: this comment is relative to the function code. Move inside the function

File: web/client/epics/search.js [hunk 6]
```diff
@@ -78,42 +82,50 @@ const searchEpic = action$ =>
  * @memberof epics.search
  * @return {Observable}
  */
+
 const searchItemSelected = action$ =>
     action$.ofType(TEXT_SEARCH_ITEM_SELECTED)
     .switchMap(action => {
-        const item = action.item;
+        let itemSelectionStream = Rx.Observable.of(action.item)
```
Comment (offtherailz) [inline web/client/epics/search.js]: You can comment `itemSelectionStream` with something like : 
```
// emits actions for zoom and marker add
```
