### PR TITLE
Fix #3927 Dashboard error in console when exporting a chart with no data

### LINKED ISSUE #3927: Dashboard error in console when exporting a chart with no data
### Description
there is an error in console when exporting a chart with no data

the app continues to work though

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard/5728) dashboard as admin
- move the map where no us states are visible
- click on export of the poulation per region chart
image

*Expected Result*

- export of empty widgets does not provoke any error (even if harmless)
- probably the export should be disabled while no data are there (and the "download chart data" tool too)

*Current Result*

in console it appears this

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Remove console error when exporting a chart with no data

## Issues
 - #3927 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3927 

**What is the new behavior?**
No console error

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/widgets/enhancers/tools/exportableWidget.js [hunk 1]
```diff
@@ -19,12 +19,14 @@ module.exports = () =>
                 glyphClassName: "exportCSV",
                 target: "menu",
                 textId: "widgets.widget.menu.downloadData",
+                visible: data && data.length,
```
Comment (MV88) [inline web/client/components/widgets/enhancers/tools/exportableWidget.js]: Hi, with this you have found solution that avoids the problem which can be good, but have you investigated the cause?

can you explain why hiding is better than disabling?

Comment (kasongoyo) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: Because I discovered the problem was in widget epic ` exportWidgetImage` https://github.com/geosolutions-it/MapStore2/blob/c6e014a7c071c977e20b1385a25ad26de8256c73/web/client/epics/widgets.js#L144 
If you look at the epic code, you can notice that the epic logic is expecting the chart to be exported to be available in the document and it works well when that condition is fulfilled. One soln was to modify that logic to include the condition when the chart is not available in the dom or leave as it is and prevent it to be called when the chart is not available. I thought the latter was more appropriate since it solve the problem from the root. Why should someone export empty data/image? There is no such use case.

Comment (MV88) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: i see, maybe we could also add a guard before start exporting to avoid the error

one other aspect is to leave the buttons visible but disabled and for this point i would ask confirmation of @tdipisa

Comment (kasongoyo) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: @MV88 sorry, I need to confess that I didn't understand your qn in the first place regarding why hiding and not disabling. You can ignore my last reply because it was answering something else. Well, back to your original question regarding hiding or disabling, I think it's a matter of preference and both ways works although I see more value on disabling only since it will give user knowledge that there is a possibility of exporting but it's only valid when there is data.

Comment (tdipisa) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: @kasongoyo disabling is better than hiding the button but maybe a tooltip should be shown to inform the user why the button is disabled.

Comment (MV88) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: @tdipisa i think that a disabled button has no possibility to show the tooltip

Comment (tdipisa) [reply web/client/components/widgets/enhancers/tools/exportableWidget.js]: ok

**Comment by tdipisa** [comment]
@kasongoyo please, can you backport this to 2019.02.xx stable branch ?
