### PR TITLE
Fix #2576. Avoid confirm window callback if not managed

### LINKED ISSUE #2576: Save as sometimes can not be closed
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*
- From the home page, login and click on new map
- Try to save the map with a name that already exists
- Wait for the editor
- Reopen "Save As..."
- try to close the modal with close button

*Expected Result*

- You can close the window

*Current Result*

- The window can not be closed anymore. You have an error in the window from the previous issue.

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
If the confirm window is not managed, you should close the Metadata modal anyway.

## Issues
 - Fix #2576

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
 - You couldn't close the save as dialog after an error on saving.

**What is the new behavior?**
- You can close the window

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

**Other information**:
IMHO Confirm dialog flag should be managed internally for the future

### CODE REVIEW

File: web/client/components/maps/modals/__tests__/MetaDataModal-test.jsx [hunk 1]
```diff
@@ -56,6 +57,42 @@ describe('This test for MetadataModal', () => {
...
+        let el = document.querySelector('#ms-resizable-modal .btn-group button');
+        expect(el).toExist();
+        ReactTestUtils.Simulate.click(el); // <-- trigger event callback
+        expect(spyonToggleUnsavedChangesModal).toHaveBeenCalled();
+        expect(spyonDisplayMetadataEdit).toNotHaveBeenCalled();
+        ReactDOM.render(<MetadataModal
+            show useModal map={map} id="MetadataModal"
+            onDisplayMetadataEdit={actions.onDisplayMetadataEdit} />, document.getElementById("container"));
+        el = document.querySelector('#ms-resizable-modal .btn-group button');
+        ReactTestUtils.Simulate.click(el);
```
Comment (MV88) [inline web/client/components/maps/modals/__tests__/MetaDataModal-test.jsx]: does it makes sense to had here 
expect(spyonToggleUnsavedChangesModal).toNotHaveBeenCalled(); ?

Comment (offtherailz) [reply web/client/components/maps/modals/__tests__/MetaDataModal-test.jsx]: no, because if it is passed it will be triggered instead of `onDisplayMetadataEdit`. See [this row](https://github.com/geosolutions-it/MapStore2/pull/2587/files/4c5000979838f872a9bf09838580be1bede8b009#diff-4b95be631fd0d83523ad56476a234ffaR167)
