### PR TITLE
#10489: Fix 10438: Problems with GeoStory map configurations merge process

### LINKED ISSUE #10489: Problems with GeoStory map configurations merge process
## Description

Legacy geostories used following configuration to store the difference between original resources and changes made to a map in a specific section:

original map resource
```
{
    "groups": [
        {
            "id": "group-02",
            "title": "over",
            "expanded": false
        },
        {
            "id": "group-01",
            "title": "base",
            "expanded": true
        }
    ],
    "layers": [
        {
            "id": "layer-01",
            "group": "group-01",
            "source": "osm",
            "name": "mapnik",
            "title": "Open Street Map",
            "type": "osm",
            "visibility": true
        },
        {
            "id": "layer-02",
            "format": "image/jpeg",
            "group": "group-02",
            "name": "workspace:layer",
            "opacity": 1,
            "title": "Layer",
            "type": "wms",
            "url": "/geoserver/wms",
            "visibility": false
        }
    ]
}
```

diff section map configuration
```js
{
    "groups": [
        null,
        {
            "expanded": false
        }
    ],
    "layers": [
        null,
        {
            "visibility": true
        }
    ]
}
```

The merging process of these two configuration has two steps:

- the diff configuration [was cleaned](https://github.com/geosolutions-it/MapStore2/blob/v2023.02.02/web/client/components/geostory/common/enhancers/map.jsx#L40) by replacing null layers with undefined
- then the [createMapObject](https://github.com/geosolutions-it/MapStore2/blob/v2023.02.02/web/client/utils/GeoStoryUtils.js#L176-L178) method was merging the two configuration so layers and groups array items were merged by index

This process had a problem in the step 1 because only null layers were converted but not group layers.

With the introduction of the new TOC the diff configuration for layers and groups was removed and this two field are cloned as soon there is a modification in the section. This introduced another problem described in this comment:

https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2176031801 

In conclusin we need to solve the issues described above:

- [ ] legacy geostory diff configuration should work also when groups are null
- [ ] new geostory diff configuration should not use the merge method for layers and groups becouse this two field are cloned using the new TOC

## How to reproduce

-  import this legacy geostory on MapStore: [legacy-geostory-with-null-groups.zip](https://github.com/user-attachments/files/16360425/legacy-geostory-with-null-groups.zip)

*Expected Result*

The geostory should be visible and working

*Current Result*

The application show the error message on full screen

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by mahmoudadel54**
## Description
This PR fixes the issue that was mentioned in (https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703). The issue was in this PR: https://github.com/geosolutions-it/MapStore2/pull/10438 in editing this part: 

https://github.com/geosolutions-it/MapStore2/blob/7b1e9b4cbdd960297587e28fe1450878567fcfb2/web/client/components/geostory/common/enhancers/map.jsx#L40-L44 

 plus 'createMapObject' method to handle legacy geostory. This editing was missing handling a case of editing layers single propery like layer's title/opacity/visibility ...etc.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703

**What is the current behavior?**
(https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703)

**What is the new behavior?**
The app doesn't crash.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/geostory/common/enhancers/map.jsx [hunk 1]
```diff
@@ -40,8 +40,11 @@ export default compose(
             const resource = find(resources, { id: resourceId }) || {};
             const baseMap = omit(resource.data, ['context']);
             const isLegacyGeostory = (map?.layers || [])?.indexOf(null) !== -1 || (map?.groups || [])?.indexOf(null) !== -1;
+            // 'layersGroupsHasEmptyItems' is a flag that indicates if the geostory 'map' object in section includes empty layers/groups
+            // the layers/groups array may include empty items in case change layer properties e.g: opacity,title ...etc
+            const layersGroupsHasEmptyItems = (map?.layers || []).includes(undefined) || (map?.groups || []).includes(undefined);
```
Comment (allyoucanmap) [inline web/client/components/geostory/common/enhancers/map.jsx:45]: This implementation seems to solve the problem but it introducing a new set of checks for a specific configuration caused from an inconsistency on the way we update layers/groups in the settings panel.

I would like to propose a change inside the [MapEditor](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/geostory/common/MapEditor.jsx#L105) instead. The `onChange` of the Editor component should update the layers or groups key of the map instead to target a specific index of the list of layers/groups. Something like the following code:

```js
<Editor
    closeNodeEditor={closeNodeEditor}
    editNode={editNode}
    map={map}
    onChange={(path, value) => {
        const config = set({ map: { ...map } }, path, value);
        const { layers, groups } = config?.map || {};
        if (path.includes('map.layers[')) {
            onChangeMap('layers', layers);
        } else {
            onChangeMap('groups', groups);
        }
    }}/>
```
By modifying the way we update the layers/groups keys of the map on the setting we are going to align it to the behaviour of the TOC. If we are introducing this change we don't need the `layersGroupsHasEmptyItems` introduced by this PR

**Review by allyoucanmap — CHANGES_REQUESTED** [review]

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this on dev and let us know when we can backport on 2024.02.xx, thanks

**Comment by ElenaGallo** [comment]
Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

**Comment by mahmoudadel54** [comment]
> Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

@ElenaGallo 
backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10539
