### PR TITLE
Fixes #2827 Add featured maps plugin

### LINKED ISSUE #2799: "Back to top" tooltip misaligned
### Description
see this:
image

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome 65.0.3325.181
- [x] Firefox
- [ ] Safari

*Browser Version Affected*
65.0.3325.181

*Steps to reproduce*

- go to the home
- scroll down
- position the mouse on the button "back to top"
- scroll down again

*Expected Result*

- tooltip follows the button

*Current Result*

- tooltip stays in the original position

### Other useful information (optional):

testing version at this [commit](https://github.com/geosolutions-it/MapStore2/tree/e0dec5fd436381b096105586d2f8a73660e6671e)

### LINKED ISSUE #2827: Add featured maps plugin
### Description
Add a plugin to show Featured maps.
here [mockup](https://demo.geo-solutions.it/mockups/mapstore2/#/featured-maps).

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
- Added Featured Maps plugin
- Partially updated Homepage layout
- Temporarily removed theme switcher (needs a new location)

## Issues
 - Fix #2827
 - Fix #2799

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Feature

**What is the current behavior?** (You can also link to an open issue here)
 issue #2827

**What is the new behavior?**
Added Featured maps plugin and did a minimal review of homepage

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

### CODE REVIEW

File: web/client/components/I18N/FlagButton.jsx [hunk 1]
```diff
@@ -27,7 +26,8 @@ class LangBar extends React.Component {
     static defaultProps = {
         locales: LocaleUtils.getSupportedLocales(),
         code: 'en-US',
-        onLanguageChange: function() {}
+        onLanguageChange: function() {},
+        onFlagSelected: () => {}
```
Comment (mbarto) [inline web/client/components/I18N/FlagButton.jsx]: What's the difference between the two events?

Comment (allyoucanmap) [reply web/client/components/I18N/FlagButton.jsx]: I don't think there is difference,
onLanguageChange and onFlagSelected was both there before I changed it.
I only added onFlagSelected in default to prevent error if missing.
Should I remove onLanguageChange?
it doesn't seem used by the component.

Comment (mbarto) [reply web/client/components/I18N/FlagButton.jsx]: ok, got it, I would it leave it there

File: web/client/localConfig.json [hunk 2]
```diff
@@ -477,7 +483,12 @@
                 "containerPosition": "header",
                 "className": "navbar shadow navbar-home"
             }
-        }, "ManagerMenu", "Login", "Language", "Attribution", {
+        }, "ManagerMenu", "Login", {
+            "name": "Language",
+            "cfg": {
+                "dropdown": true
```
Comment (offtherailz) [inline web/client/localConfig.json]: let's make it a default, if possible, and remove this config from localConfig

File: web/client/product/plugins/Attribution.jsx [hunk 3]
```diff
@@ -1,44 +1,104 @@
...
+const src = require("./attribution/geosolutions-brand-sm.png");
 const assign = require('object-assign');
+const tooltip = require('../../components/misc/enhancers/tooltip');
+const {isString, trimStart} = require('lodash');
+const {Nav, NavItem, Glyphicon} = require('react-bootstrap');
+const Img = tooltip(props => (<img {...props}/>));
+const ContainerDimensions = require('react-container-dimensions').default;
+const NavItemT = tooltip(NavItem);
 
 class Attribution extends React.Component {
```
Comment (offtherailz) [inline web/client/product/plugins/Attribution.jsx]: This plugin is both NavMenu and Attribution logo. We should separate the 2 concepts to render attribution (logo and so on) in NavMenu, and not vice-versa.
We want to use it in dependent projects that do not have the logo on top.
