### PR TITLE
Fix #2898 TOC moves down if Measure tool and print are opened

### LINKED ISSUE #2898: TOC moves down if Measure tool and print are opened
### Description

with measure tool opened
image

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- just open the measure or the print tool 

*Expected Result*
- toc button doesn't move

*Current Result*
- toc button moves down

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
Added top and left style position to avoid relative translation of TOC button

## Issues
 - Fix #2898

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
 issue #2898

**What is the new behavior?**
TOC button doesn't move if print measure modals are open

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/plugins/FloatingLegend.jsx [hunk 1]
```diff
@@ -61,7 +70,9 @@ class FloatingLegendComponent extends React.Component {
 
     render() {
         return (
-            <div style={{position: 'absolute', height: '100%'}}>
+            <div
+                className={this.props.className}
+                style={{...this.props.style}}>
```
Comment (MV88) [inline web/client/plugins/FloatingLegend.jsx]: why not ? 
 style={this.props.style}>
