### PR TITLE
Fix #2812 parseInitialState function 

### LINKED ISSUE #2812: Cannot customize initial state with array of strings
### Description
I tried to customize initial state with the default state of featuregrid reducer and ended up with an error that was raised on opening of the feature grid.
array of string are not handled correctly [here ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/app/StandardApp.jsx#L124)
it ended to transform the array ["ADMIN"] into {0: "ADMIN"}

there was also a problem with toChangesMap function in FeatureGridUtils because changes was an empty object instead of an array.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce* (on a local environment)

- Copy default state of feature grid reducer in localconfig
- try to open a map (nothing shows)

once you have fixed the FeatureGridUtils problem
- try to open the feature grid 

*Expected Result*

- the feature grid opened correctly with no errors

*Current Result*
- you have an error in the console

### Other useful information (optional):
here is the fix for FeatureGridUtils
```
const {isArray} = require('lodash');
const toChangesMap = (changesArray) => isArray(changesArray) ? changesArray.reduce((changes, c) => ({
    ...changes,
    [c.id]: {
        ...changes[c.id],
        ...c.updated
    }
}), {}) : {};
```

### PR DESCRIPTION
**Pull request by MV88**
## Description
Now it is possible to add ["string value"] inside initalState configuration
it is parsed correctly.

## Issues
 - Fix #2812

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see issue #2812

**What is the new behavior?**
Now it is possible for example to copy the default state of reducer from featureGrid to the initialState inside configuration with no error raising in the console.
it loads correctly the map if we do that.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/app/StandardApp.jsx [hunk 1]
```diff
@@ -120,9 +120,19 @@ class StandardApp extends React.Component {
             this.store.dispatch(action());
         });
     };
+    /**
+     * A function used to parse the initialState in the localConfig.json
+     * If an array of simple values is parsed then just return their values, otherwise return the recursive func
```
Comment (offtherailz) [inline web/client/components/app/StandardApp.jsx]: it doesn't return the recursive func:

It returns an object of the same structure of the `initialState` but replacing strings like `"{someExpression}"` with the result of the expression between brackets. 
state the object to parse
context context for expression
return the modified object.

File: web/client/utils/FeatureGridUtils.js [hunk 2]
```diff
@@ -35,13 +35,13 @@ const getRow = (i, rows) => rows[i];
 
 /* eslint-disable */
 
-const toChangesMap = (changesArray) => changesArray.reduce((changes, c) => ({
+const toChangesMap = (changesArray) => isArray(changesArray) ? changesArray.reduce((changes, c) => ({
```
Comment (offtherailz) [inline web/client/utils/FeatureGridUtils.js]: what's the reason of this change?

Comment (MV88) [reply web/client/utils/FeatureGridUtils.js]: because moving the reducer default state of featuregrid caused that changesArray to passed as empty object initially, this makes the map loading forever

Comment (offtherailz) [reply web/client/utils/FeatureGridUtils.js]: You may use a default = [] that seems to be more clear. 
Did you changed the initial state? It should be anyway consistent.
