### PR TITLE
Performance Optimization: Refactor Pending Changes Logic and Save Resource Selector #11476

### LINKED ISSUE #11435: Changes dialog show after resource is deleted
## Description
Changes dialog show immediately after a resource is deleted

## How to reproduce
- Create a new map resource
- Save the new resource with a name (Save As button)
- Click the Delete button in the top left of the navbar
- A dialog will open asking "Are you sure you want to delete this resource?" to confirm deletion.
- Immediately afterward, a second dialog will automatically appear (which is the bug):
"Are you sure to leave without applying your changes?"

*Expected Result*
Redirect to homepage

*Current Result*
Show changes dialog

https://github.com/user-attachments/assets/2e376c50-b8e3-4ba2-8318-4949f110c7e3

### LINKED ISSUE #11458: Issue with the Yellow Warning Dote on Save button
## Description

**Issue 1**
- login as admin
- Open a new map
*Current Result*
The yellow dote is preset on the Save As button, even any update it is done on the map.

https://github.com/user-attachments/assets/56e37d27-2d60-4bf2-9669-210562be8cc9

**Issue 2**
- login as admin
- Open a new map
- Add a layer from the Catolog
- Click on Save as
- Enter a tile
- Click on Create
*Current Result*
The yellow dote is preset on the Save button, even any update it is done on the map.

https://github.com/user-attachments/assets/44b50024-d6e6-48d0-abc1-3451be66bfaa

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### LINKED ISSUE #11476: Performance Optimization: Refactor Pending Changes Logic and Save Resource Selector
## Description

It has been observed that performance degrades when multiple there are huge number of layers, particularly affecting map/UI interaction. This slowness is caused by the logic for computing pending changes being placed inside a selector, which is called multiple times under heavy load.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Optimization
- [x] Refactoring (no functional changes, no api changes)

### Proposed Enhancements

1. **Separate Logic**
   - Move the logic for:
     - Computing **pending changes**.
     - Preparing the **resource to save**.
   - The resource preparation should be handled via a **selector** (without debounce) to avoid inconsistencies.

2. **Component-Based Optimization**
   - Shift the pending changes computation into a **connected component**.
   - Apply **debounce** to reduce frequent executions of heavy computations.
   - Optimize more if possible

3. **Store in State**
   - Save the computed **pending changes** in the **application state** for access by other components.

Ultimately, when performing map interaction on a map with a large number of layers (or has layer with heavy geometry), it should not block the JS main thread, causing the entire application to hang.

### PR DESCRIPTION
**Pull request by rowheat02**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Optimization
 - [x] Refactoring 

fixes #11476
fixes #11435
fixes #11458

**What is the current behavior?**

 #11476
 #11435
 #11458

**What is the new behavior?**

- More optimized than before, while doing UI/Map interaction.
- No pending change Prompt shown when the map is deleted when there are some pending changes on Map page.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information 

https://github.com/user-attachments/assets/a067e462-f3ff-4932-a7e1-e74dc3c14e03

- `compareMapChanges` is out of selector and is called using debounce logic. Managed in `useComputedPendingChanges`
  - By default, 
     - it waits for 500 ms before calling
     - if for 2000 ms, not called due to debouncing, it will be forced to call
 
- Another expensive function, ' saveMapConfiguration`, is only called on demand. Will not be called infinitely while doing UI/Map Interaction
- for Optimization, createSelector has been used on the main selector
- Also, now, while saving a new or existing map, the mapSave payload is calculated, unlike before, taking from the selector.

### CODE REVIEW

File: web/client/utils/__tests__/GeostoreUtils-test.js [hunk 1]
```diff
@@ -99,92 +104,42 @@ describe('GeostoreUtils', () => {
             name: 'Context'
         })).toEqual({ items: [{ type: 'icon', glyph: 'context', tooltipId: 'resourcesCatalog.mapUsesContext', tooltipParams: { contextName: 'Context' } }] });
     });
-    it('computePendingChanges', () => {
```
Comment (allyoucanmap) [inline web/client/utils/__tests__/GeostoreUtils-test.js:102]: all these removed cases must be rewritten using computeSaveResource and computePendingChanges

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
I pushed additional code that needs to be tested and reviewed in addition some tests are failing and they need to be reviewed

**Comment by allyoucanmap** [comment]
@ElenaGallo please test these fixes on dev and let use know if we can backport on 2025.01.xx, thanks.
Note there are 3 issue connected

**Comment by ElenaGallo** [comment]
Hi @rowheat02, the Yellow Warning Dote on Save button is still present on DEV MS:

- login as admin
- Open a new map

Current Result
The yellow dote is preset on the Save As button, even any update it is done on the map.

**Comment by ElenaGallo** [comment]
Test passed, @rowheat02 please backport to 2025.01.xx . Thanks
