### PR TITLE
Fix #3958 hide layer related buttons when removing a layer from the map

### LINKED ISSUE #3958: In dashboards, hide layer related buttons when removing a layer from the map widget
### Description
In dashboards, once a layer has been removed from a map widget, the `settings` and the `delete` buttons should be not visible.

delete_layer_dash

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- browser independent

*Steps to reproduce*

- open a dashboard (or create a new one from scratch)
- add an empty map widget
- add a layer to it
- select the layer
- delete it

*Expected Result*

- the `settings` and the `delete` buttons disappear after the layer has been removed

*Current Result*

- the `settings` and the `delete` buttons are still visible

### PR DESCRIPTION
**Pull request by kasongoyo**
fix #3958

## Description
Hide layer related buttons when removing a layer from the map widget

## Issues
 - #3958 
 - ...

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3958 

**What is the new behavior?**
The removed layer related buttons disappear on layer remove 

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/plugins/widgetbuilder/enhancers/__tests__/handleMapRemoveLayer-test.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+        setTimeout(done);
+    });
+
+    afterEach((done) => {
+        ReactDOM.unmountComponentAtNode(document.getElementById("container"));
+        document.body.innerHTML = '';
+        setTimeout(done);
+    });
+
+    it('should trigger onNodeSelect on remove layer', () => {
```
Comment (offtherailz) [inline web/client/plugins/widgetbuilder/enhancers/__tests__/handleMapRemoveLayer-test.js]:
```suggestion
    it('layer remove must also unselect the layers by triggering onNodeSelect ', () => {
```
