### PR TITLE
#9613: Fix for layer filtering resulting in lowercase titles

### LINKED ISSUE #9613: After filtering Layers, all Layer names are lower case
## Description
Layer can have uppercase names, e.g.
image

However, after filtering, all layer names are written in lower case
image

In some languages (e.g. German) this is more annoying than in others (e.g. Italian).

## How to reproduce
On any map 
* open the layer filtering tool in the top left corner
* type something in the filter-field, which matches at least one layername 

*Expected Result*
Even after filtering the names keep their original lower-upper-case writing and the matched strings are bold.

*Current Result*
After filtering the matched strings are bold, but all matched layer names are entirely lower case.

- [x] Not browser related

### PR DESCRIPTION
**Pull request by petra-schanz**
## Description
Should fix #9613: After filtering Layers, all Layer names are lower case

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features) (too small for specific test)
- [ ] Docs have been added / updated (for bug fixes / features) (too small for documentation)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [X] Bugfix

## Issue

**What is the current behavior?**
#9613

**What is the new behavior?**
After filtering layers the titles keep their lower and uppercase as before.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

File: web/client/components/TOC/fragments/Title.jsx [hunk 1]
```diff
@@ -38,14 +38,19 @@ class Title extends React.Component {
...
-        return this.props.filterText ? splitTitle.reduce((a, b, idx) => {
-            if (idx === splitTitle.length - 1) {
-                return [...a, b];
+        if (!this.props.filterText || !matches) {
+            return title;
+        }
+
+        return title.split(regularExpression).map((split, key) => {
+            if (key < matches.length) {
+                return [...split, <strong>{matches[key]}</strong>];
```
Comment (MV88) [inline web/client/components/TOC/fragments/Title.jsx:50]: i would call the index idx

```suggestion
        return title.split(regularExpression).map((split, idx) => {
            if (idx < matches.length) {
                return [...split, <strong key={idx}>{matches[idx]}</strong>];
```

**Review by MV88 — CHANGES_REQUESTED** [review]
All good, just one little thing

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Comment by petra-schanz** [comment]
@MV88 good idea, thank you!
