### PR TITLE
fixes #2173 #2174 removed empty filter, included 0 as value

### LINKED ISSUE #2173: Using zero as a value in a query filter will result in an "undefined" filter
To reproduce:
- Open the WFS search test map
- Open the query panel
- Input a filter "PERSONS = 0"
- Start the search

Expected result:  No results

Actual result: All the records

### PR DESCRIPTION
**Pull request by MV88**
fixes #2173 #2174

### CODE REVIEW

File: web/client/utils/FilterUtils.jsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ const ogcDateField = (attribute, operator, value, nsplaceholder) => {
 
 const ogcListField = (attribute, operator, value, nsplaceholder) => {
     let fieldFilter;
-    if (value) {
+    if ((value !== undefined || value !== null)) {
```
Comment (offtherailz) [inline web/client/utils/FilterUtils.jsx]: use isDefiled = v => v !== undefined || v !== null

**Comment by simboss** [comment]
Guys, where the test to show that we fixed an issue?

@MV88 I want to see proper unit tests **especially** when we are fixing a problem. I mean, I should not even say this.

File: web/client/utils/FilterUtils.jsx [hunk 2]
```diff
@@ -9,6 +9,12 @@
 const {processOGCGeometry, pointElement, polygonElement, lineStringElement } = require("./ogc/GML");
 const {wfsToGmlVersion} = require('./ogc/WFS/base');
 const {ogcComparisonOperators, ogcLogicalOperators, ogcSpatialOperators} = require("./ogc/Filter/operators");
+const {isNil, isUndefined} = require('lodash');
+
+const checkValidityValue = (value, operator) => {
```
Comment (offtherailz) [inline web/client/utils/FilterUtils.jsx]: checkOperatorValidity
