### PR TITLE
#9965 Mitigation of random test failures

### LINKED ISSUE #9965: Unit test for Cesium randomly fails
## Description

In github actions, a cesium test fails randomly. Probably related to some wrong async requests or some uncleaned test state, often cause of random fails.

Here an execution on github.
https://github.com/geosolutions-it/MapStore2/actions/runs/7831094091/attempts/1?pr=9962

## How to reproduce

- Check if can be reproduced locally running unint tests.

*Expected Result*
- Tests pass
*Current Result*
- Tests sometimes fail.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

```
 CesiumMap
    ✖ click on layer should return intersected features (slow: 0.724 secs)
      Chrome Headless 121.0.6167.139 (Linux x86_64)
    Error: Expected [] to equal [ { id: 'vector', features: [ { type: 'Feature', properties: { category: 'area' }, geometry: null }, { type: 'Feature', properties: { category: 'boundary' }, geometry: null } ] } ]
        at assert (webpack://mapstore2/./node_modules/expect/lib/assert.js?:29:9)
        at Expectation.toEqual (webpack://mapstore2/./node_modules/expect/lib/Expectation.js?:85:30)
        at Object.onClick (webpack://mapstore2/./web/client/components/map/cesium/__tests__/Map-test.jsx?:348:80)
        at CesiumMap.eval [as onClick] (webpack://mapstore2/./web/client/components/map/cesium/Map.jsx?:6349:22)
        at SafeSubscriber.eval [as _next] (webpack://mapstore2/./web/client/components/map/cesium/Map.jsx?:6726:21)
        at SafeSubscriber.__tryOrUnsub (webpack://mapstore2/./node_modules/rxjs/Subscriber.js?:234:16)
        at SafeSubscriber.next (webpack://mapstore2/./node_modules/rxjs/Subscriber.js?:183:22)
        at Subscriber._next (webpack://mapstore2/./node_modules/rxjs/Subscriber.js?:125:26)
        at Subscriber.next (webpack://mapstore2/./node_modules/rxjs/Subscriber.js?:89:18)
        at SwitchMapSubscriber.notifyNext (webpack://mapstore2/./node_modules/rxjs/operator/switchMap.js?:124:30)
        at InnerSubscriber._next (webpack://mapstore2/./node_modules/rxjs/InnerSubscriber.js?:23:21)
        at Subscriber.next (webpack://mapstore2/./node_modules/rxjs/Subscriber.js?:89:18)
 ```

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
The failing test is reproducible locally, failing 1 times on 5 attempts. Adding a `setTimeout` of 1 second, locally looks to solve the problem (tried several times and I didn't have the error anymore).
The solution is not optimal, we should check what to check exactly before to trigger the click event, but this can be a temporary fix to solve the build failures, that solves the build problems.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9965

**What is the new behavior?**
fix #9965 
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/map/cesium/__tests__/Map-test.jsx [hunk 1]
```diff
@@ -392,10 +392,12 @@ describe('CesiumMap', () => {
                 expect(dataSource.entities.values.length).toBe(4);
                 const mapCanvas = ref.map.canvas;
                 const { width, height } = mapCanvas.getBoundingClientRect();
-                simulateClick(mapCanvas, {
-                    clientX: width / 2,
-                    clientY: height / 2
-                });
+                setTimeout(() => { // this mitigates #9965 waiting for a better solution
```
Comment (allyoucanmap) [inline web/client/components/map/cesium/__tests__/Map-test.jsx:395]: I noticed that the `ref.map.dataSourceDisplay.ready` inside the waitFor changes between state true/false twice. I would like to propose an additional change by switching the waitFor statement by checking the display ready before the entities length. I think we should keep also the setTimeout as you are proposing to have a buffer time.

```js
let prevReady = false;
let countReady = 0;
// the data source switches twice from false to true
// here we are waiting the second render
const checkReadyDataSource = () => {
    const currentReady = ref.map.dataSourceDisplay.ready;
    if (currentReady !== prevReady) {
        if (currentReady) {
            countReady += 1;
        }
        prevReady = ref.map.dataSourceDisplay.ready;
    }
    if (countReady === 2) {
        return true;
    }
    return false;
};
// first we check we got data source ready twice
// then we verify that the dataSources entities are available
waitFor(() => expect(checkReadyDataSource()
&& !!ref.map.dataSources.get(0).entities.values.length).toBe(true), {
    timeout: 5000
})
    .then(() => {
        expect(ref.map.dataSources.length).toBe(1);
        const dataSource = ref.map.dataSources.get(0);
        expect(dataSource).toBeTruthy();
        expect(dataSource.entities.values.length).toBe(4);
        const mapCanvas = ref.map.canvas;
        const { width, height } = mapCanvas.getBoundingClientRect();
        // adding additional timeout to ensure the complete render
        setTimeout(() => {
            simulateClick(mapCanvas, {
                clientX: width / 2,
                clientY: height / 2
            });
        }, 1000);
    })
    .catch(done);
```

Comment (offtherailz) [reply web/client/components/map/cesium/__tests__/Map-test.jsx]: I tried to apply your suggestion inline.

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo this fix it's related to unit test so it cannot be tested on dev
