### PR TITLE
Fix #9867 background downsampling for thumbnail of backgrounds

### LINKED ISSUE #9867: Layer BG Selector - Implement size checks on uploaded images and downsampling
In the BG layer selector plugin users can upload an image as thumbnail to show in the buttons of the plugin. Images are stored within the map and context configuration as text (format base64).
In case users upload quite large or high resolutions images the parsed text will result in a very long string and this does have an impact on the resulting configuration JSON created (long loading times, crash on saves).

https://github.com/geosolutions-it/MapStore2/assets/14953970/cecc3d9b-aef8-4466-85e5-cbd6d7c3d3d7

AT THE MOMENT THE LIMIT OF THE IMAGE IS 500KB, which is already quite high for a thumbnail. 

The fix could have two actions:

1. Reduce the allowed limit in KB of the image the user can upload as a thumbnail (for example up to 50KB would seem to be enough)
2. Implement a mechanism to scale and save in base64 the uploaded image to a fixed scaled size, with the view to reduce the resulting string size.

### PR DESCRIPTION
**Pull request by MV88**
## Description

- add downsampling of images to 98x98 (preview size)
- make sure that temp layer is updated when editing and saving a thumbnail

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9867 
**What is the new behavior?**

see description above
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/background/BackgroundDialog.jsx [hunk 1]
```diff
@@ -323,6 +323,13 @@ export default class BackgroundDialog extends React.Component {
                     map={{
                         newThumbnail: get(this.state.thumbnail, 'url') || "NODATA"
                     }}
+                    thumbnailOptions={{
+                        width: 98,
+                        height: 98,
+                        type: 'image/jpeg',
+                        quality: 0.5,
+                        contain: false
```
Comment (allyoucanmap) [inline web/client/components/background/BackgroundDialog.jsx:331]: Maybe we could use 128px x 128px with 0.8 quality and change the UI to be squared, something like this:

image

We could also change the message into: `Size of images should be a square of 128px x 128px, max 500kb`

Just tested a conversion of a [colorful image](https://unsplash.com/photos/multicolored-painting-pCcGpVsOHoo) (original size ~ 3.4 MB) into a thumbnail 128px x 128px quality 0.8. The result is an image of ~ 8.4 KB

test

**Review by allyoucanmap — CHANGES_REQUESTED** [review]

**Review by allyoucanmap — APPROVED** [review]
