### PR TITLE
Fix #1660. Now results can fit to map size

### LINKED ISSUE #1660: Allow to fit search results to map size
Now search results do not fit to the window size, and even the z-index is wrong:
image

We should have something like this instead:
image

### PR DESCRIPTION
**Pull request by offtherailz**
- If results are too many, the result list become scrollable
 - The z-index is fixed to be above the toolbar

### CODE REVIEW

File: web/client/plugins/Search.jsx [hunk 1]
```diff
@@ -124,6 +125,7 @@ const SearchPlugin = connect((state) => ({
     selectedItems: state && state.search && state.search.selectedItems
 }))(React.createClass({
     propTypes: {
+        fitToResultsMapSize: React.PropTypes.bool,
```
Comment (mbarto) [inline web/client/plugins/Search.jsx]: fitResultsToMapSize
