### PR TITLE
Fix COG and FlatGeobuf layers support params for protected storage

### LINKED ISSUE #12162: COG and FlatGeobuf layers support params for protected storage
## Description
When adding a COG or FlatGeobuf source files The parameters defined in the localConfig section: requestsConfigurationRules are not passed in remote requests.
This prevents the opening of protected COG or FlatGeobuf files on remote storage.

This occurs at time to opening the catalog and also when adding layers to the map.

## How to reproduce
add some rules in section requestsConfigurationRules
(This is just an example. You need to use keys defined on the server that distributes the resources.)
```json
 {
      "urlPattern": "https://remote.storage/cog/.*",
      "params": {
          "sig": "574XQctJduYVZLpxS5I3yHBaMHFIIuCbYQZ1sXpr7iA="
      }
  },
  {
      "urlPattern": "https://remote.storage/flatgeobuf/.*",
      "params": {
          "sig": "m7ESsEudYbnzjGW3cD7fZNwNolPKzBbEDc2Y3tXrjEI="
      }
  }
```

*Expected Result*
loading remote resources using correct url parameters by config

*Current Result*
parameters defined in requestsConfigurationRules is ignored

- [x] Not browser related

### PR DESCRIPTION
**Pull request by stefanocudini**
Fix #12162 

- fix cog catalog sugin security params
- new function setSecurityParams
- added unit test for setSecurityParams
- secure params in 3D layers
- fix tests SecurityUtils

## Description
In short, in cases of datasets using custom rules in the requestsConfigurationRules section of localConfig.json, the URL parameters for resource addresses corresponding to COG and FlatGeobuf files were not being passed. See the issue for an example of rules to use for testing.

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue
Fix #12162 

**What is the current behavior?**

#<issue>

**What is the new behavior?**
A new method `setSecurityParams` has been added to avoid code replication that automatically appends parameters to the URL when necessary. In cases where no rules exist, the original URL is used

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
See the linked issue for bug reproducing details.
Geonode-client porting is required

### CODE REVIEW

File: web/client/api/FlatGeobuf.js [hunk 1]
```diff
@@ -45,7 +46,8 @@ export const getCapabilities = (url) => {
     return getFlatGeobufGeneric().then(flatgeobuf => {
         return axios.get(url, {
             adapter: config => {
-                return flatgeobuf.readMetadata(config.url);
+                const axiosUrl = setSecurityParams(config.url);
+                return flatgeobuf.readMetadata(axiosUrl);
```
Comment (allyoucanmap) [inline web/client/api/FlatGeobuf.js]: It seems possible to include also headers https://github.com/flatgeobuf/flatgeobuf/commit/ec78df6aa1c4e7df7e45fc25650c5c53e4f621ea#diff-b03111f7d0b3f8b9e9642ebf0ea8d6fbaff46d335a83257901ff5acb357f3a4cR187-R188.

Note the axios library is already including the params and headers based on security rules with the [addAuthenticationToAxios](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/libs/ajax.js#L49-L89) interceptor, could you verify if the config headers and params are already including needed information and use here directly url parse format without need of setSecurityParams?

File: web/client/components/map/cesium/plugins/COGLayer.js [hunk 2]
```diff
@@ -89,7 +90,7 @@ const createLayer = (options) => {
     if (!options.visibility) {
         return null;
     }
-    const url = options.url || options?.sources[0]?.url;
+    const url = setSecurityParams(options.url || options?.sources[0]?.url);
```
Comment (allyoucanmap) [inline web/client/components/map/cesium/plugins/COGLayer.js]: In this case I would prefer we use getRequestConfigurationByUrl and extract both headers and params and pass them to a cesium Resource class https://cesium.com/learn/cesiumjs/ref-doc/Resource.html. In the .fromUrl(url we should be able to pass the resource instead of the url.

File: web/client/components/map/cesium/plugins/FlatGeobufLayer.js [hunk 3]
```diff
@@ -70,7 +71,8 @@ const createLayer = (options, map) => {
 
         let rect = mapBbox();
 
-        for await (const feature of flatgeobuf.deserialize(options.url, rect)) {
+        const secureUrl = setSecurityParams(options.url);
+        for await (const feature of flatgeobuf.deserialize(secureUrl, rect)) {
```
Comment (allyoucanmap) [inline web/client/components/map/cesium/plugins/FlatGeobufLayer.js]: also in this case the headers are supported, let's include them https://github.com/flatgeobuf/flatgeobuf/blob/master/src/ts/geojson/featurecollection.ts#L55, please let's try to include them. I think the params and header can be computed outside the loadingBbox function.

File: web/client/components/map/openlayers/plugins/COGLayer.js [hunk 4]
```diff
@@ -13,16 +13,23 @@ import get from 'lodash/get';
...
 function create(options) {
+    let sources = [];
     let sourceOptions = {};
-    if (options.security && options.sources && options.sources.length > 0) {
+    if (options.sources && options.sources.length > 0) {
         const firstSource = options.sources[0];
-        const requestConfig = getRequestConfigurationByUrl(firstSource.url, null, options.security?.sourceId);
-        if (requestConfig.headers) {
-            sourceOptions.headers = requestConfig.headers;
+        const {headers} = getRequestConfigurationByUrl(firstSource.url, null, options.security?.sourceId);
```
Comment (allyoucanmap) [inline web/client/components/map/openlayers/plugins/COGLayer.js]: The params are already computed here. Could we extract the params from here and maybe use [updateUrlParams](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/URLUtils.js#L164-L169) from URLUtils ?

File: web/client/components/map/openlayers/plugins/FlatGeobufLayer.js [hunk 5]
```diff
@@ -47,14 +49,15 @@ const getWFSStyle = (layer, options, map) => {
 
 const createLoader = (source, options, strategy) => (extent, resolution, projection) => {
     getFlatGeobufOl().then(flatgeobuf => {
-        const loader = flatgeobuf.createLoader(source, options.url, 'EPSG:4326', strategy, true);
+        const secureUrl = setSecurityParams(options.url);
+        const loader = flatgeobuf.createLoader(source, secureUrl, 'EPSG:4326', strategy, true);
```
Comment (allyoucanmap) [inline web/client/components/map/openlayers/plugins/FlatGeobufLayer.js]: could we include also header in this case, they seems supported https://github.com/flatgeobuf/flatgeobuf/blob/master/src/ts/ol.ts#L87

File: web/client/utils/cog/LayerUtils.js [hunk 6]
```diff
@@ -47,9 +48,10 @@ export const fromUrl = (url, signal) => {
     if (signal?.aborted) {
         return abortError(Promise.reject);
     }
+    const secureUrl = setSecurityParams(url);
     return new Promise((resolve, reject) => {
         signal?.addEventListener("abort", () => abortError(reject));
-        return fromGeotiffUrl(url)
+        return fromGeotiffUrl(secureUrl)
```
Comment (allyoucanmap) [inline web/client/utils/cog/LayerUtils.js]: also in this case the headers seem supported, could you include them? https://geotiffjs.github.io/geotiff.js/functions/geotiff.fromUrl.html https://geotiffjs.github.io/geotiff.js/interfaces/geotiff.RemoteSourceOptions.html

File: web/client/utils/SecurityUtils.js [hunk 7]
```diff
@@ -356,6 +356,30 @@ export const  getRequestConfigurationByUrl = (url, securityToken, sourceId) => {
...
+            });
+            // we need to remove this to force the use of query
+            delete url.search;
+            return URL.format(url);
+        } catch (e) {
+            return sourceUrl;
+        }
+    }
+    return sourceUrl;
+}
```
Comment (allyoucanmap) [inline web/client/utils/SecurityUtils.js]: In most of the cases reviewed we need to extract both headers and params. My proposal in this case is to use:

- const { headers, params } = getRequestConfigurationByUrl(url, ...); to extract all at once
- then use [updateUrlParams](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/URLUtils.js#L164-L169)  to apply params when not supported natively

File: web/client/components/map/cesium/plugins/COGLayer.js (hunk 2 above)
Comment (allyoucanmap) [reply web/client/components/map/cesium/plugins/COGLayer.js]: Note all layers may recieve the options.security?.sourceId property that could be used with getRequestConfigurationByUrl

File: web/client/components/map/cesium/plugins/FlatGeobufLayer.js (hunk 3 above)
Comment (allyoucanmap) [reply web/client/components/map/cesium/plugins/FlatGeobufLayer.js]: Note all layers may recieve the options.security?.sourceId property that could be used with getRequestConfigurationByUrl

File: web/client/components/map/openlayers/plugins/FlatGeobufLayer.js (hunk 5 above)
Comment (allyoucanmap) [reply web/client/components/map/openlayers/plugins/FlatGeobufLayer.js]: Note all layers may recieve the options.security?.sourceId property that could be used with getRequestConfigurationByUrl

File: web/client/api/FlatGeobuf.js (hunk 1 above)
Comment (stefanocudini) [reply web/client/api/FlatGeobuf.js]: yes check axios juect return headers anche params

File: web/client/components/map/openlayers/plugins/COGLayer.js (hunk 4 above)
Comment (stefanocudini) [reply web/client/components/map/openlayers/plugins/COGLayer.js]: replaced all `setSecurityParams` with `updateUrlParams`

File: web/client/utils/cog/LayerUtils.js (hunk 6 above)
Comment (stefanocudini) [reply web/client/utils/cog/LayerUtils.js]: solved and linked 3d third party docs

File: web/client/utils/SecurityUtils.js (hunk 7 above)
Comment (stefanocudini) [reply web/client/utils/SecurityUtils.js]: removed setSecurityParams and it's tests

File: web/client/components/map/cesium/plugins/FlatGeobufLayer.js (hunk 3 above)
Comment (stefanocudini) [reply web/client/components/map/cesium/plugins/FlatGeobufLayer.js]: passed options.security

File: web/client/components/map/openlayers/plugins/FlatGeobufLayer.js (hunk 5 above)
Comment (stefanocudini) [reply web/client/components/map/openlayers/plugins/FlatGeobufLayer.js]: passed options.security and headers

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this fix on dev and let us know when we can backport, thanks

**Comment by offtherailz** [comment]
Successfully created backport PR for `2026.01.xx`:
- #12251
