### PR TITLE
Fix #3930 short height of query panel filter when opened in dashboard

### LINKED ISSUE #3930: Dashboard: when filter is opened the layout is not updated accordingly
### Description
The width of the filter panel is higher and the height is smaller causing this
image

also the spinner keeps loading after a widget is added to the dashboard or the only widgets is deleted and the dashboard is empty

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome 75.0.3770.100 
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open mapstore home and login as admin
- create a new dashboard
- add chart widgets
- select a layer
- create a filter

*Expected Result*

- the height to be the same as for the toc (at least), the body container to adapt to remaining space without hiding some widgets on the left
NOTE: this is cause to the fat that filter panel is added over the toc which where widgets are anchored

*Current Result*

- some layout glitch. see the image above

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix the query panel height when opened in dashboard context

## Issues
 - #3930 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3930 

**What is the new behavior?**
Screenshot 2019-08-23 at 15 07 33

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/plugins/QueryPanel.jsx [hunk 1]
```diff
@@ -179,16 +180,17 @@ const tocSelector = createSelector(
         (state) => state.layers && state.layers.settings || {expanded: false, options: {opacity: 1}},
         (state) => state.controls && state.controls.queryPanel && state.controls.queryPanel.enabled || false,
         state => mapLayoutValuesSelector(state, {height: true}),
+        isDashboardAvailable,
         appliedFilterSelector,
         storedFilterSelector,
         (state) => state && state.query && state.query.isLayerFilter,
         selectedLayerLoadingErrorSelector
-    ], (enabled, groups, settings, querypanelEnabled, layout, appliedFilter, storedFilter, advancedToolbar, loadingError) => ({
+    ], (enabled, groups, settings, querypanelEnabled, layoutHeight, dashboardAvailable, appliedFilter, storedFilter, advancedToolbar, loadingError) => ({
```
Comment (MV88) [inline web/client/plugins/QueryPanel.jsx]: Why did you changed the name here from layout to layoutHeight?

Comment (kasongoyo) [reply web/client/plugins/QueryPanel.jsx]: It was misleading; the property contains only layout height.

**Comment by kasongoyo** [comment]
> Hi, Please add a test for this fix

Adding a test for this plugin is overkill for the changes I only did.

File: web/client/plugins/QueryPanel.jsx (hunk 1 above)
Comment (MV88) [reply web/client/plugins/QueryPanel.jsx]: ok

**Comment by MV88** [comment]
> > Hi, Please add a test for this fix
> 
> Adding a test for this plugin is overkill for the changes I only did.

ok

**Comment by MV88** [comment]
@kasongoyo please backport this to 2019.02.xx
