### PR TITLE
Fix #10910 search bar overlap gfi panel

### LINKED ISSUE #10910: Conflict between search bar and GFI panel
## Description

On a map, the search bar covers the GFI panel when it is opened.

Image

## How to reproduce

-  Open a map
- Click a feature on map

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
## Description

I noticed that the value of isIdentifyInContext was incorrectly set to false and no longer being updated this was making the selector [isMapinfoOpen](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/selectors/mapInfo.js#L40) here  in the [mapLayout epic](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/maplayout.js#L125) to be false and therefore ignored for moving away the search bar with correct style properties 

I also fixed another error in console
image

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10910 

**What is the new behavior?**

it works fine, also tested by closing gfi and opening catalog

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 
The issue still persists
image

File: web/client/reducers/context.js [hunk 1]
```diff
@@ -34,10 +34,9 @@ import { migrateContextConfiguration } from '../utils/ContextCreatorUtils';
 export default (state = {}, action) => {
     switch (action.type) {
     case MAP_CONFIG_LOADED: {
-
-        return set('currentContext.userPlugins',
+        return action.config?.context?.userPlugins ?? state.resource?.data?.userPlugins ? set('currentContext.userPlugins',
```
Comment (dsuren1) [inline web/client/reducers/context.js:37]:
```suggestion
        const userPlugins = action.config?.context?.userPlugins ?? state.resource?.data?.userPlugins
        return  userPlugins ? set('currentContext.userPlugins', userPlugins, state) : state;
```

File: web/client/reducers/context.js [hunk 2]
```diff
@@ -34,10 +34,9 @@ import { migrateContextConfiguration } from '../utils/ContextCreatorUtils';
...
             action.config?.context?.userPlugins ?? state.resource?.data?.userPlugins
```
Comment (dsuren1) [inline web/client/reducers/context.js:38]:
```suggestion
```

File: web/client/reducers/context.js [hunk 3]
```diff
@@ -34,10 +34,9 @@ import { migrateContextConfiguration } from '../utils/ContextCreatorUtils';
...
-            , state);
+            , state) : state;
```
Comment (dsuren1) [inline web/client/reducers/context.js:39]:
```suggestion
```

File: web/client/selectors/context.js [hunk 4]
```diff
@@ -64,22 +64,26 @@ export const templatesSelector = createSelector(
...
-    currentContextSelector,
-    pluginsSelector,
-    (currentContext, contextPlugins = {}) => !currentContext ||
-        findIndex(get(contextPlugins, 'desktop', []), plugin => plugin.name === pluginName) > -1
-);
+export const isPluginInContext = pluginName => state => {
+    const currentContext = currentContextSelector(state);
+    const contextPlugins = pluginsSelector(state);
+    const result = !currentContext || findIndex(get(contextPlugins, 'desktop', []), plugin => plugin.name === pluginName) > -1;
+    return result;
```
Comment (dsuren1) [inline web/client/selectors/context.js:85]:
```suggestion
    return !currentContext || findIndex(get(contextPlugins, 'desktop', []), plugin => plugin.name === pluginName) > -1;
```

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 
I observe the overlapping behavior when initially loading GFI

https://github.com/user-attachments/assets/4da323e6-b945-4ec0-8777-b6ef0db04909

File: web/client/selectors/context.js [hunk 5]
```diff
@@ -74,12 +74,11 @@ export const pluginsSelector = state =>
  * and it has a specific plugin activated
  * @param {string} pluginName plugin name
  */
-export const isPluginInContext = pluginName => createSelector(
-    currentContextSelector,
-    pluginsSelector,
-    (currentContext, contextPlugins = {}) => !currentContext ||
-        findIndex(get(contextPlugins, 'desktop', []), plugin => plugin.name === pluginName) > -1
-);
+export const isPluginInContext = pluginName => state => {
```
[the remark this answers is not in the document]
Comment (MV88) [reply web/client/selectors/context.js:81]: we can revert

File: web/client/selectors/context.js (hunk 4 above)
Comment (MV88) [reply web/client/selectors/context.js:85]: for debugging purposes i used the committed solution we can keep it i guess

**Comment by MV88** [comment]
> @MV88 I observe the overlapping behavior when initially loading GFI
> 
>  overlap_gfi.mp4

This was present also before, i guess it can be done in a separate issue. waiting @tdipisa opinion about it

**Comment by tdipisa** [comment]
> > @MV88 I observe the overlapping behavior when initially loading GFI
> > overlap_gfi.mp4
> 
> This was present also before, i guess it can be done in a separate issue. waiting @tdipisa opinion about it

Hi @MV88 I'm sorry but I don't understand. The purpose of https://github.com/geosolutions-it/MapStore2/issues/10910 is indeed to fix that overlapping issue... another issue for what? Did I mess something?

**Comment by tdipisa** [comment]
@MV88 Thank you for the feedback

>if you check on prod the search bar is not moving out smoothly as well so it is something to take into account in a different issue

2024.02.02 differ from current master because it miss of new layout things we have recently implemented there. Indeed, in 2024.02.02 the Search is not moving smoothly, yes, but it is moving anyway when the GFI panel is expanded. On master instead it remains blocked over the GFI panel. We don't need to fix the behavior of 2024 series now since it is is working (even if not smoothly) and there aren't further releases expected for that series. Therefore, since you are going to fix the wrong behavior with this PR, no need of a new issue, I think.

**Comment by MV88** [comment]
> @MV88 Thank you for the feedback
> 
> > if you check on prod the search bar is not moving out smoothly as well so it is something to take into account in a different issue
> 
> 2024.02.02 differ from current master because it miss of new layout things we have recently implemented there. Indeed, in 2024.02.02 the Search is not moving smoothly, yes, but it is moving anyway when the GFI panel is expanded. On master instead it remains blocked over the GFI panel. We don't need to fix the behavior of 2024 series now since it is is working (even if not smoothly) and there aren't further releases expected for that series. Therefore, since you are going to fix the wrong behavior with this PR, no need of a new issue, I think.

we are merging then, thanks

**Comment by MV88** [comment]
@dsuren1 is this approvable?

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test in DEV when available, and consider the above exchanges during testing. Thanks!

**Comment by ElenaGallo** [comment]
Test passed, @MV88 please backport to 2025.01.xx. Thanks
