### PR TITLE
Fix #9120 Layer settings performance improvement

### LINKED ISSUE #9120: Improve layer settings performances
While implementing  #9099,  I noticed a performance problem in layer settings. (`TOCItemSettings`)

This is due basically to the current implementation and some forced rerenders of all the plugin forced to support the thematic layer plugin. These force re-render are due to some changes applied to the core objects only to support Thematic Layer

We need to refactor and cleanup the implementation of the plugin at least to allow to type data without visible performance issues.
Now a change causes 150ms-200ms re-rendering (this is masked basically by making the input boxes update the fields on blur, but we can not workorund this problem anymore). 
This have to be fixed if we want to type and change things live, and for handling easely the future changes to this tool, too. 

Here a sample of the warning.

https://user-images.githubusercontent.com/1279510/233379214-44cd2b7d-b182-4178-aeb5-62681cc385e5.mp4

### PR DESCRIPTION
**Pull request by offtherailz**
## Description

This PR is required for #9099 . It: 
- cleans up unnecessary code for handling some state that is not used anymore (initialSettings and originalSettings). 
- Remove core changes that forced re-render of the whole application on every change on layer settings.
- Refactor of thematic layer to not rely on old lazy load system, but using `Suspense` instead.
- Improves a little the management of TocItemsSettings tabs (not a complete rewrite, that could be more useful, but the one necessary to support thematic layer).

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#9120

**What is the new behavior?**

The warning is not present anymore. From test with direct editors ( that need to be added, are now fast enough to be usable).

https://user-images.githubusercontent.com/1279510/233392060-c3269be4-4cc7-4d8c-b9cd-4ca9a550e00e.mp4

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/selectors/controls.js [hunk 1]
```diff
@@ -28,7 +28,6 @@ export const printSelector = (state) => get(state, "controls.print.enabled");
 export const wfsDownloadSelector = state => !!get(state, "controls.layerdownload.enabled");
 export const widgetBuilderAvailable = state => get(state, "controls.widgetBuilder.available", false);
 export const widgetBuilderSelector = (state) => get(state, "controls.widgetBuilder.enabled");
-export const initialSettingsSelector = state => get(state, "controls.layersettings.initialSettings") || {};
 export const originalSettingsSelector = state => get(state, "controls.layersettings.originalSettings") || {};
```
Comment (allyoucanmap) [inline web/client/selectors/controls.js:31]: Should we remove also this selector?

Comment (offtherailz) [reply web/client/selectors/controls.js:31]: yes, correct, going to remove it too.

**Review by allyoucanmap — APPROVED** [review]
LGTM!

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV  ? Thank you
