### PR TITLE
Fix #9905 Clamp to ground issue found with WFS layer

### LINKED ISSUE #9905: Clamp to ground issue found with WFS layer
## Description

It seems the Clamp to ground functionality (WFS style editor) is not properly working in certain conditions

## How to reproduce

- Open this [map context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/genova/48184)  
- Ensure the _Depth test against terrain_ is disable on map settings
- Open the style editor of the layer AREE INTERVENTI FSC 
- Activate the _Clamp to ground_

*Expected Result*

The functionality works as expected as documented [here](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/layer-settings/#styling-of-vector-layer)

*Current Result*

The Cesium map is reporting a rendering error

Image

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

The problem happens when a polygon has all the coordinates with the exact same values, eg:

image

This PR adds an additional validation steps that remove all duplicated consecutive coordinates in this way polygons with all the same coordinates will be removed from the rendering. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#9905

**What is the new behavior?**

Polygons with all the same coordinates will be removed from the rendering to prevent errors

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

### CODE REVIEW

File: web/client/utils/cesium/GeoJSONStyledFeatures.js [hunk 1]
```diff
@@ -4,9 +4,13 @@ import omit from 'lodash/omit';
 import isArray from 'lodash/isArray';
 import uuid from 'uuid/v1';
 
-const validateCoordinatesValue = (coords) => {
+const validateCoordinatesValue = (coords, prevCoords) => {
```
Comment (MV88) [inline web/client/utils/cesium/GeoJSONStyledFeatures.js:7]: can you add jsdoc to the functions in this file? 

what is the structure of coords for example?

File: web/client/utils/cesium/__tests__/GeoJSONStyledFeatures-test.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * All rights reserved.
+ *
+ * This source code is licensed under the BSD-style license found in the
+ * LICENSE file in the root directory of this source tree.
+*/
+import expect from 'expect';
+import GeoJSONStyledFeatures from '../GeoJSONStyledFeatures';
+
+describe('Test GeoJSONStyledFeatures', () => {
+    it('it should exclude invalid features', () => {
```
Comment (MV88) [inline web/client/utils/cesium/__tests__/GeoJSONStyledFeatures-test.js:12]: can you add a test when instead it works?

**Review by MV88 — CHANGES_REQUESTED** [review]
it works, please just check my comments to see if we can improve a bit local doc and testing

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
@ElenaGallo please test it on DEV
