### PR TITLE
Fixes #2322 Custom WMTS gridsets are not supported, Fixes #2342 Tiles errors management

### LINKED ISSUE #2322: Custom WMTS gridsets are not supported
Layers using a custom gridset are incorrectly displayed on the map, even if the gridset information is available in the GetCapabilities document.

To reproduce:
 - Open a map
 - Open the catalog
 - Select the GeoSolutions DEMO WMTS service
 - Search for tasmania_test layer and add it to the map

Expected result: the Tasmania polygons are placed south of Australia, with the correct size.

Actual result: the Tasmania polygons are displayed spanning from Canada to Antarctica.

The tasmania_test layer is set to have a custom gridset with a boundary smaller than the projection maximum bounds.

### LINKED ISSUE #2342: Tiles errors management
We should improve the management of errors generated from tile loading.
Now the layer is disabled if all the tile loaded on screen throw an error but in some cases it doesn't mean that the layer is broken.
e.g. When some zoom levels are disabled from server

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description
Now custom gridset are loaded an displayed at the right dimension.
About tasmania_test:
I tried this fix with another custom grid set and the world grid set and it works with both (right position and size).
I noticed also an issue with the same layer in WMS (tasmania_test).
Could it be that the gridset isn't configured correctly?
Could it be that on high scale denominator there's a loss of precision in the gridset pyramid?
- About last question I noticed that at small scale denominator the precision increases.

## Issues
 - Fix #2322
 - Fix #2342 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Feature

**What is the current behavior?** (You can also link to an open issue here)
Cutsom WMTS grids are displayed world wide.
#2322
#2342 

**What is the new behavior?**
Cutsom WMTS grids are displayed at the correct position.
Try to reload layers with errors on zoom.

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

File: web/client/components/map/leaflet/__tests__/Layer-test.jsx [hunk 1]
```diff
@@ -189,7 +189,13 @@ describe('Leaflet layer', () => {
             "name": "nurc:Arc_Sample",
             "group": "Meteo",
             "format": "image/png",
-            "tileMatrixSet": "EPSG:900913",
+            "tileMatrixSet": [
+                {
+                    "TileMatrix": [],
+                    "ows:Identifier": "EPSG:4326",
```
Comment (mbarto) [inline web/client/components/map/leaflet/__tests__/Layer-test.jsx]: Is this a typo?
