### PR TITLE
Fix #1956 Tutorial autostart do not work anymore

### LINKED ISSUE #1956: Tutorial autostart do not work anymore
It seems due to the introduction of Tutorial for 3D Map. If you configure the autostart for tutorial in this way
```
 {
        "name": "Tutorial",
        "cfg": {

            "rawSteps": [{
                  "title": "drawerMenu",
                  "selector": "#intro-tutorial"
              },{
                  "translation": "drawerMenu",
                  "selector": "#drawer-menu-button"
              },
              {
                  "translation": "home",
                  "selector": "#home-button"
              },
              {
                  "translation": "searchButton",
                  "selector":"#search-help"
              },
              {
                  "translation": "burgerMenu",
                  "selector": "#mapstore-burger-menu"
              }]
        }
```
The tutorial intro page disappears once the map is loaded. (tested inside a map).

### PR DESCRIPTION
**Pull request by allyoucanmap**
Fix #1956 
rawSteps configuration causes autostart issues while using dynamic tutorial (e.g. switch between 2d and 3d map tutorials).
Instead of rawSteps we could override the the preset list of tutorial in MapStore2 with the presetList configuration as in this PR.
rawSteps has been removed.

This is the new configuration:
```
{
  "name": "Tutorial",
  "cfg": {
    "presetList": {
      "default_tutorial": [{
          "title": "Welcome",
          "selector": "#intro-tutorial"
        }, {
          "translation": "drawerMenu",
          "selector": "#drawer-menu-button"
        },
        {
          "translation": "home",
          "selector": "#home-button"
        },
        {
          "translation": "burgerMenu",
          "selector": "#mapstore-burger-menu"
        }
      ]
    }
  }
}
```

### CODE REVIEW

File: web/client/epics/tutorial.js [hunk 1]
```diff
@@ -36,19 +37,21 @@ const closeTutorialEpic = (action$) =>
 
 const switchTutorialEpic = (action$, store) =>
     action$.ofType(LOCATION_CHANGE)
-        .audit(() => action$.ofType(CHANGE_MAP_VIEW))
+        .audit(() => action$.ofType(MAPS_LIST_LOADED, CHANGE_MAP_VIEW))
```
Comment (offtherailz) [inline web/client/epics/tutorial.js]: please check if audit is correctly used in this context

File: web/client/actions/tutorial.js [hunk 2]
```diff
@@ -20,6 +21,18 @@ function startTutorial() {
     };
 }
 
+function initTutorial(id, steps, style, checkbox, defaultStep, presetList) {
```
Comment (offtherailz) [inline web/client/actions/tutorial.js]: please test
