### PR TITLE
fix #1263 FilterUtils wrong usage of this removed most of the places

### LINKED ISSUE #1263: FilterUtils wrong usage of this reference
Filter Utils refers to this in its static methods. This can cause side effects. 
see : https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/FilterUtils.jsx#L54

### PR DESCRIPTION
**Pull request by saidaipparla**

### CODE REVIEW

File: web/client/utils/FilterUtils.jsx [hunk 1]
```diff
@@ -513,12 +771,12 @@ const FilterUtils = {
     *   }}
     *   }
     */
-    processOGCCrossLayerFilter: function(crossLayerFilter) {
-        let ogc = this.ogcSpatialOperator[crossLayerFilter.operation].startTag;
+    processOGCCrossLayerFilter: function(crossLayerFilter, nsplaceholder) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: put a default value of "ogc" for nsplaceholder

File: web/client/utils/__tests__/FilterUtils-test.js [hunk 2]
```diff
@@ -486,7 +486,7 @@ describe('FilterUtils', () => {
         FilterUtils.nsplaceholder = "ogc";
         FilterUtils.setOperatorsPlaceholders("{namespace}", "ogc");
 
-        let filter = FilterUtils.processOGCCrossLayerFilter(crossLayerFilterObj);
+        let filter = FilterUtils.processOGCCrossLayerFilter(crossLayerFilterObj, "ogc");
```
Comment (mbarto) [inline web/client/utils/__tests__/FilterUtils-test.js]: Remove "ogc" argument, we cannot change public methods behaviour

File: web/client/utils/FilterUtils.jsx [hunk 3]
```diff
@@ -530,80 +788,24 @@ const FilterUtils = {
...
         if (crossLayerFilter.operation === "DWITHIN") {
-            ogc += '<' + this.nsplaceholder + ':Distance units="m">' + (crossLayerFilter.distance || 0) + '</' + this.nsplaceholder + ':Distance>';
+            ogc += '<' + nsplaceholder + ':Distance units="m">' + (crossLayerFilter.distance || 0) + '</' + nsplaceholder + ':Distance>';
         }
 
-        ogc += this.ogcSpatialOperator[crossLayerFilter.operation].endTag;
+        ogc += ogcSpatialOperator[crossLayerFilter.operation].endTag;
         return ogc;
     },
-    getGmlPointElement: function(coordinates, srsName, version) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: These methods were public, so they could be used elsewhere, removing them could break a lot of code

File: web/client/utils/FilterUtils.jsx [hunk 4]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
             }
         });
     },
-    getGetFeatureBase: function(version, pagination, hits, format) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 5]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ' +
-                    'xsi:schemaLocation="http://www.opengis.net/wfs/2.0 ' +
-                        'http://schemas.opengis.net/wfs/2.0/wfs.xsd ' +
-                        'http://www.opengis.net/gml/3.2 ' +
-                        'http://schemas.opengis.net/gml/3.2.1/gml.xsd">';
-        }
-
-        return getFeature;
-    },
-    processOGCFilterGroup: function(root) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 6]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-            subGroups.forEach((subGroup) => {
-                ogc += this.processOGCFilterGroup(subGroup);
-            });
-        }
-
-        ogc += this.ogcLogicalOperator[root.logic].endTag;
-
-        return ogc;
-    },
-    processOGCFilterFields: function(group) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 7]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                }
-                return arr;
-            }, []);
-
-            filter = filter.join("");
-        }
-
-        return filter;
-    },
-    processOGCSimpleFilterField: function(field) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 8]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                    filter += this.ogcLogicalOperator.OR.endTag;
-                }
-                break;
-            }
-            default:
-                break;
-        }
-        return filter;
-    },
-    ogcDateField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 9]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                                this.propertyTagReference[this.nsplaceholder].startTag +
-                                    attribute +
-                                this.propertyTagReference[this.nsplaceholder].endTag +
-                                "<" + this.nsplaceholder + ":Literal>" + value.startDate.toISOString() + "</" + this.nsplaceholder + ":Literal>" +
-                            this.ogcComparisonOperators[operator].endTag;
-            }
-        }
-        return fieldFilter;
-    },
-    ogcListField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 10]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                this.ogcComparisonOperators[operator].startTag +
-                    this.propertyTagReference[this.nsplaceholder].startTag +
-                        attribute +
-                    this.propertyTagReference[this.nsplaceholder].endTag +
-                    "<" + this.nsplaceholder + ":Literal>" + value + "</" + this.nsplaceholder + ":Literal>" +
-                this.ogcComparisonOperators[operator].endTag;
-        }
-        return fieldFilter;
-    },
-    ogcStringField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 11]
```diff
@@ -154,277 +641,30 @@ const FilterUtils = {
...
-                        this.propertyTagReference[this.nsplaceholder].startTag +
-                            attribute +
-                        this.propertyTagReference[this.nsplaceholder].endTag +
-                        "<" + this.nsplaceholder + ":Literal>*" + value + "*</" + this.nsplaceholder + ":Literal>" +
-                    this.ogcComparisonOperators[operator].endTag;
-            }
-        }
-        return fieldFilter;
-    },
-    ogcNumberField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 12]
```diff
@@ -513,29 +753,6 @@ const FilterUtils = {
     *   }}
     *   }
     */
-    processOGCCrossLayerFilter: function(crossLayerFilter) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 13]
```diff
@@ -559,51 +776,48 @@ const FilterUtils = {
         gmlPoint += '</gml:Point>';
         return gmlPoint;
     },
-    getGmlPolygonElement: function(coordinates, srsName, version) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 14]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-        if (this.objFilter.spatialField && this.objFilter.spatialField.geometry && this.objFilter.spatialField.operation) {
-            spatialFilter = this.processCQLSpatialFilter();
+        if (objFilter.spatialField && objFilter.spatialField.geometry && objFilter.spatialField.operation) {
+            spatialFilter = processCQLSpatialFilter(objFilter);
             filters.push(spatialFilter);
         }
 
         return "(" + (filters.length > 1 ? filters.join(") AND (") : filters[0]) + ")";
-    },
-    processCQLFilterGroup: function(root) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 15]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-                    filter.push(fieldFilter);
-                }
-            });
-
-            filter = filter.join(" " + group.logic + " ");
-        }
-
-        return filter;
-    },
-    processCQLSimpleFilterField: function(field) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 16]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-                }
-                break;
-            }
-            default:
-                break;
-        }
-
-        return (strFilter && strFilter.length > 0) ? strFilter : false;
-    },
-    cqlListField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 17]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-        return this.cqlStringField(attribute, operator, value);
-    },
-    cqlStringField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 18]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-                let val = "'%" + value.toLowerCase() + "%'";
-                fieldFilter = "strToLowerCase(" + attribute + ") LIKE " + val;
-            } else {
-                let val = "'%" + value + "%'";
-                fieldFilter = attribute + "LIKE " + val;
-            }
-        }
-        return fieldFilter;
-    },
-    cqlNumberField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 19]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-            }
-        } else {
-            let val = value && (value.lowBound !== null && value.lowBound !== undefined) ? value.lowBound : value;
-            if (val ) {
-                fieldFilter = attribute + operator + "'" + val + "'";
-            }
-        }
-        return fieldFilter;
-    },
-    cqlDateField: function(attribute, operator, value) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 20]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-                    "' AND " + attribute + "<='" + value.endDate.toISOString() + "')";
-            }
-        } else {
-            if (value.startDate) {
-                fieldFilter = attribute + operator + "'" + value.startDate.toISOString() + "'";
-            }
-        }
-        return fieldFilter;
-    },
-    processCQLSpatialFilter: function() {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 21]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-        let cql = this.objFilter.spatialField.operation + "(" +
-            this.objFilter.spatialField.attribute + ", ";
-
-        cql += this.getCQLGeometryElement(this.objFilter.spatialField.geometry.coordinates, this.objFilter.spatialField.geometry.type);
-
-        return cql + ")";
-    },
-    getCQLGeometryElement: function(coordinates, type) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/FilterUtils.jsx [hunk 22]
```diff
@@ -614,211 +828,12 @@ const FilterUtils = {
...
-                });
-                break;
-            default:
-                break;
-        }
-
-        geometry += ")";
-        return geometry;
-    },
-    findSubGroups: function(root, groups) {
```
Comment (mbarto) [inline web/client/utils/FilterUtils.jsx]: Also this one was public

File: web/client/utils/__tests__/FilterUtils-test.js [hunk 23]
```diff
@@ -484,7 +484,7 @@ describe('FilterUtils', () => {
         // this is a workarround for this issue : https://github.com/geosolutions-it/MapStore2/issues/1263
         // please remove when fixed
         FilterUtils.nsplaceholder = "ogc";
-        FilterUtils.setOperatorsPlaceholders("{namespace}", "ogc");
+        FilterUtils.setOperatorsPlaceholders("{namespace}", FilterUtils.nsplaceholder);
```
Comment (mbarto) [inline web/client/utils/__tests__/FilterUtils-test.js]: Not this way: the FilterUtils.setOperatorsPlaceholders function should have a default for the second argument:

setOperatorsPlaceholders: function(placeholder, replacement = "ogc") {
   ...
}
