### PR TITLE
#11779: FIX Setting the map projection freezes MapStore causing OOM if resolutions configured in new.json file with a different projection

### LINKED ISSUE #11779: Setting the map projection crashes MapStore if resolutions configured in new.json file with a different projection
## Description

Setting the map projection as admin causes MapStore to crash with error "Out of Memory" if there are some resolutions preset in new.json file with a different projection rather than the selected one.

## How to reproduce

-  in new.json file add resolutions array in map.mapOptions.view for a projection like: 3857
- add new map resource
- select a different CRS from CRS selector like: 4326
- the app will crash

*Expected Result*

Selection CRS should be done smoothly without any crash

*Current Result*

The mapstore crash

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by mahmoudadel54**
## Description

This PR includes:
- prevent OOM by enforcing projection-aware resolutions in new.json file in mapOptions.view
- Add strict check: only use configured resolutions if `view.projection` in **new.json file** matches target SRS in createView
- Eliminates infinite tile loading and out-of-memory crashes when switching to different CRS
- fix print file by passing the projection prop with resolutions to gurantee the above check

** the new edits includes -> a projection should be added to resolutions/scales in **mapOptions.view** in **new.json file** to be read properly. **

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#11779 

**What is the new behavior?**

The OOM behavior not happen now if a resolutions and projection provided in new.json file and user switch to different projection rather than the resolutions one.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
This new.json for test
```
{
  "version": 2,
  "map": {
    "projection": "EPSG:900913",
    "units": "m",
    "center": { "x": 1250000.0, "y": 5370000.0, "crs": "EPSG:900913" },
    "zoom": 5,
    "mapOptions": {
      "view": {
        "resolutions": [
          84666.66666666688,
          42333.33333333344,
          21166.66666666672,
          10583.33333333336,
          5291.66666666668,
          2645.83333333334,
          1322.91666666667,
          661.458333333335000,
          529.166666666668000,
          396.875000000001000,
          264.583333333334000,
          132.291666666667000,
          66.145833333333500,
          39.687500000000100,
          26.458333333333400,
          13.229166666666700,
          6.614583333333350,
          3.968750000000010,
          2.645833333333340,
          1.322916666666670,
          0.661458333333335
        ],
        "projection": "EPSG:3857"
      }
    },
    "maxExtent": [-20037508.34, -20037508.34, 20037508.34, 20037508.34],
    "layers": [
      {
        "format": "image/jpeg",
        "group": "background",
        "name": "osm:osm_simple_light",
        "opacity": 1,
        "title": "OSM Simple Light",
        "thumbURL": "product/assets/img/osm-simple-light.jpg",
        "type": "wms",
        "url": [
          "https://maps1.geosolutionsgroup.com/geoserver/wms",
          "https://maps2.geosolutionsgroup.com/geoserver/wms",
          "https://maps3.geosolutionsgroup.com/geoserver/wms",
          "https://maps4.geosolutionsgroup.com/geoserver/wms",
          "https://maps5.geosolutionsgroup.com/geoserver/wms",
          "https://maps6.geosolutionsgroup.com/geoserver/wms"
        ],
        "tileSize": 512,
        "visibility": false,
        "singleTile": false,
        "credits": {
          "title": "OSM Simple Light | Rendering <a href=\"https://www.geo-solutions.it/\">GeoSolutions</a> | Data © <a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a> contributors, <a href=\"http://www.openstreetmap.org/copyright\">ODbL</a>"
        }
      },
      {
        "format": "image/jpeg",
        "group": "background",
        "name": "osm:osm_simple_dark",
        "opacity": 1,
        "title": "OSM Simple Dark",
        "thumbURL": "product/assets/img/osm-simple-dark.jpg",
        "type": "wms",
        "url": [
          "https://maps6.geosolutionsgroup.com/geoserver/wms",
          "https://maps3.geosolutionsgroup.com/geoserver/wms",
          "https://maps1.geosolutionsgroup.com/geoserver/wms",
          "https://maps4.geosolutionsgroup.com/geoserver/wms",
          "https://maps2.geosolutionsgroup.com/geoserver/wms",
          "https://maps5.geosolutionsgroup.com/geoserver/wms"
        ],
        "tileSize": 512,
        "visibility": false,
        "singleTile": false,
        "credits": {
          "title": "OSM Simple Dark | Rendering <a href=\"https://www.geo-solutions.it/\">GeoSolutions</a> | Data © <a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a> contributors, <a href=\"http://www.openstreetmap.org/copyright\">ODbL</a>"
        }
      },
      {
        "format": "image/jpeg",
        "group": "background",
        "name": "osm:osm",
        "opacity": 1,
        "title": "OSM Bright",
        "thumbURL": "product/assets/img/osm-bright.jpg",
        "type": "wms",
        "url": [
          "https://maps1.geosolutionsgroup.com/geoserver/wms",
          "https://maps2.geosolutionsgroup.com/geoserver/wms",
          "https://maps3.geosolutionsgroup.com/geoserver/wms",
          "https://maps4.geosolutionsgroup.com/geoserver/wms",
          "https://maps5.geosolutionsgroup.com/geoserver/wms",
          "https://maps6.geosolutionsgroup.com/geoserver/wms"
        ],
        "tileSize": 512,
        "visibility": true,
        "singleTile": false,
        "credits": {
          "title": "OSM Bright | Rendering <a href=\"https://www.geo-solutions.it/\">GeoSolutions</a> | Data © <a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a> contributors, <a href=\"http://www.openstreetmap.org/copyright\">ODbL</a>"
        }
      },
      {
        "format": "image/jpeg",
        "group": "background",
        "name": "ne:ne-political",
        "opacity": 1,
        "title": "NE Political",
        "thumbURL": "product/assets/img/ne-political.jpg",
        "type": "wms",
        "url": [
          "https://maps1.geosolutionsgroup.com/geoserver/wms",
          "https://maps2.geosolutionsgroup.com/geoserver/wms",
          "https://maps3.geosolutionsgroup.com/geoserver/wms",
          "https://maps4.geosolutionsgroup.com/geoserver/wms",
          "https://maps5.geosolutionsgroup.com/geoserver/wms",
          "https://maps6.geosolutionsgroup.com/geoserver/wms"
        ],
        "tileSize": 512,
        "visibility": false,
        "singleTile": false,
        "credits": {
          "title": "<p></p>\n"
        }
      },
      {
        "format": "image/jpeg",
        "group": "background",
        "name": "s2cloudless:s2cloudless",
        "opacity": 1,
        "title": "Sentinel 2 Cloudless",
        "type": "wms",
        "url": [
          "https://maps1.geosolutionsgroup.com/geoserver/wms",
          "https://maps2.geosolutionsgroup.com/geoserver/wms",
          "https://maps3.geosolutionsgroup.com/geoserver/wms",
          "https://maps4.geosolutionsgroup.com/geoserver/wms",
          "https://maps5.geosolutionsgroup.com/geoserver/wms",
          "https://maps6.geosolutionsgroup.com/geoserver/wms"
        ],
        "tileSize": 512,
        "source": "s2cloudless",
        "singleTile": false,
        "visibility": false
      },
      {
        "type": "osm",
        "title": "Open Street Map",
        "name": "mapnik",
        "source": "osm",
        "group": "background",
        "visibility": false
      },
      {
        "source": "ol",
        "group": "background",
        "title": "Empty Background",
        "fixed": true,
        "type": "empty",
        "visibility": false
      }
    ]
  }
}

```

I think guides should be added for this edit

### CODE REVIEW

**Review by tdipisa — COMMENTED** [review]
@mahmoudadel54 what about old maps having the old configuration? Probably we should at least automatically update the map state at loading time so that the new logic is applied and when the map is saved the new configuration is also persisted. All in a transparent and automated way ensuring also a good backward compatibility. What do you think @MV88? Up to you to review.

File: web/client/components/map/openlayers/Map.jsx [hunk 1]
```diff
@@ -516,22 +536,39 @@ class OpenlayersMap extends React.Component {
...
-            // allow to zoom to level 0 and see world wrapping
-            multiWorld: true,
-            // does not allow intermediary zoom levels
-            // we need this at true to set correctly the scale box
-            constrainResolution: true,
-            resolutions: this.getResolutions(normalizeSRS(projection))
-        }, newOptions || {});
+        const viewOptions = Object.assign(
+            {},
+            newOptions || {},
```
Comment (MV88) [inline web/client/components/map/openlayers/Map.jsx]: i have some concerns about the fact that here you are greatly changing the order of merging of params. is this really needed? maybe only put resolutions at the end to make sure it will not be overridden?

**Review by MV88 — CHANGES_REQUESTED** [review]
@mahmoudadel54 not much to say, but one thing to be sure

**Comment by tdipisa** [comment]
> @mahmoudadel54 not much to say, but one thing to be sure

What about https://github.com/geosolutions-it/MapStore2/pull/11788#pullrequestreview-3567817241 @MV88?

File: web/client/components/map/openlayers/Map.jsx (hunk 1 above)
Comment (mahmoudadel54) [reply web/client/components/map/openlayers/Map.jsx]: I think resolutions and projection 
Will check

**Review by MV88 — APPROVED** [review]
LGTM

**Comment by tdipisa** [comment]
@ElenaGallo waiting for you for before merging the backport

**Comment by tdipisa** [comment]
> > @mahmoudadel54 not much to say, but one thing to be sure
> 
> What about [#11788 (review)](https://github.com/geosolutions-it/MapStore2/pull/11788#pullrequestreview-3567817241) @MV88?

@MV88 I saw you have merged, but can I have an answer to this please?

**Comment by ElenaGallo** [comment]
Test passed, @tdipisa backport can be merged

**Comment by MV88** [comment]
> Test passed, @tdipisa backport can be merged

we have noticed that current implementation might require an additional effort in order to cover all cases, see here https://github.com/geosolutions-it/MapStore2/issues/11779#issuecomment-3654978544

i'll revert this

**Comment by offtherailz** [comment]
Successfully created backport PR for `2026.01.xx`:
- #12394
