### PR TITLE
Fix #4397 Layers/backgrounds default format is not selectable

### LINKED ISSUE #4397: Layers/backgrounds default format is not selectable
### Description
Creating a new catalog service or editing an existing one, on Advanced settings is impossible to choose the default format of backgrounds/layers. If you choose an option from the dropdown menu the choice is not mantained.

service
 
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open mapstore
- Login as admin
- Open a new map
- Add a new background
- Add a new service in catalog
- Type valid url and title
- Expand advanced settings
- Try to change the format
**1**
- Change the format in image/jpg
- Click on save
- Add a background to the map
**2**

*Expected Result*

**1** The format changes
**2** The default format should be image/jpg

*Current Result*

**1** The format doesn't change
**2** The default format ism't image jpg

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Default format now works.

## Issues
 - #4397 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#4397 

**What is the new behavior?**
In the description

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

File: web/client/components/catalog/Catalog.jsx [hunk 1]
```diff
@@ -530,9 +534,10 @@ class Catalog extends React.Component {
                                     </Col >
                                     <Col xs={6}>
                                         <Select
-                                            value="image/png"
-                                            clearable={false}
-                                            options={this.props.formatOptions}/>
+                                            value={this.props.newService && this.props.newService.format}
```
Comment (offtherailz) [inline web/client/components/catalog/Catalog.jsx]: please add a test for handler to be called and value to be correctly set

File: web/client/reducers/catalog.js [hunk 2]
```diff
@@ -129,6 +130,8 @@ function catalog(state = {
         return set("newService.url", action.url, state);
     case CHANGE_AUTOLOAD:
         return set("newService.autoload", action.autoload, state);
+    case CHANGE_SERVICE_FORMAT:
```
Comment (offtherailz) [inline web/client/reducers/catalog.js]: other parts has test, this should be have it too.

I know testing reducers by themself, when this are so simple like this, is a little boring and seems useless. But we need them to ensure to keep the same interface. 

editor's note: In other places, to make these tests more useful I used to apply to use actionCreators and selector, so I test the integration between them and so all the state cicle (event creation --> state mutation --> state slice getter). If you prefer, you can use this approch
